"""Build the bounded, source-backed documentation audit; no matrices downloaded."""
import csv, hashlib, json
from pathlib import Path
BASE=Path(__file__).resolve().parent
S=BASE/'snapshots'
GH='716c27dccba847875f85be63103e2245acaa3320'
HF=json.loads((S/'hf_dataset_info.json').read_text())['sha']
DATE='2026-09-14'
def dump(name,x):(BASE/name).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
def rows(name):return list(csv.DictReader((S/name).open(encoding='utf-8-sig')))
def source(id,file,url,status='inspected_document'):
 p=S/file
 return {'source_id':id,'url':url,'snapshot_path':str(p.relative_to(BASE.parent.parent.parent)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'retrieved_on':DATE,'evidence_status':status}
sources=[source('paper_v2','paper_v2.html','https://arxiv.org/html/2505.14725v2'),source('github_readme','github_readme.md',f'https://github.com/XuejunSun98/HR-VILAGE-3K3M/blob/{GH}/README.md'),source('hf_card','hf_readme.md',f'https://huggingface.co/datasets/xuejun72/HR-VILAGE-3K3M/blob/{HF}/README.md'),source('hf_variables','hf__Meta_variable_description.csv',f'https://huggingface.co/datasets/xuejun72/HR-VILAGE-3K3M/blob/{HF}/Meta_variable_description.csv','inspected_small_table'),source('hf_studies','hf__study_meta.csv',f'https://huggingface.co/datasets/xuejun72/HR-VILAGE-3K3M/blob/{HF}/study_meta.csv','inspected_small_table'),source('gh_studies','study_meta.csv',f'https://github.com/XuejunSun98/HR-VILAGE-3K3M/blob/{GH}/study_meta.csv','inspected_small_table'),source('hf_citations','hf__study_citations.csv',f'https://huggingface.co/datasets/xuejun72/HR-VILAGE-3K3M/blob/{HF}/study_citations.csv','inspected_small_table'),source('hf_example_meta','hf__example_dataset__GSE194378_meta_sample.csv',f'https://huggingface.co/datasets/xuejun72/HR-VILAGE-3K3M/blob/{HF}/example_dataset/GSE194378_meta_sample.csv','inspected_small_table'),source('hf_example_antibody','hf__example_dataset__GSE194378_antibody_sample.csv',f'https://huggingface.co/datasets/xuejun72/HR-VILAGE-3K3M/blob/{HF}/example_dataset/GSE194378_antibody_sample.csv','inspected_small_table')]
for name in ['Affymetrix_microarray_process','Illumina_microarray_process','RNAseq_Process','Single_cell_merge_data_demo','Meta_preprocess_demo']:
 sources.append(source(name,'docs__'+name+'.qmd',f'https://github.com/XuejunSun98/HR-VILAGE-3K3M/blob/{GH}/docs/{name}.qmd'))
sources.append(source('merge_code','code__Merge_Plot_Demo.py',f'https://github.com/XuejunSun98/HR-VILAGE-3K3M/blob/{GH}/code/Merge_Plot_Demo.py','inspected_code_not_executed'))
dump('sources.json',{'retrieved_on':DATE,'sources':sources,'snapshot_policy':'Public primary-source documentation and small tables only; no instrument-raw files or full expression matrices downloaded. HTML-to-text files are local reading derivatives, not additional independent sources.'})
units={'age':'years','BMI':'kg/m²','Height_cm':'cm','Weight_kg':'kg','Duration_of_symptoms':'days','days.since.covid.19.diagnosis':'days','MFC':'dimensionless ratio','Enrollment_year':'calendar year','influenza.vaccination.count..previous.10.years.':'count'}
notes={'ID':'Unique only within a study according to the author dictionary; repeat across longitudinal sample rows is expected. Qualify with study_ID before joining.', 'geo_accession':'Often GSM, but repository-specific or synthetic row identifiers must be preserved; do not force every study identifier into a GEO accession.', 'timepoint':'Author dictionary says exact time/day after vaccination or infection, without a universal unit or event anchor. Retain original text and resolve units and day zero per source study before merging.', 'timepoint_group':'Derived category; never substitute for exact source collection time.', 'MFC':'Derived outcome; do not mix antibody assays, antigens, visit denominators, or censoring rules. Study-level provenance required.', 'responder':'Derived response category, not directly measured antibody level; preserve responder_original separately.', 'viral_shedding':'Presence or quantitative result depending on study. Assay, specimen, threshold and units remain study-specific.', 'Total_DSS':'Composite symptom score; instrument, scale, aggregation window, weighting and missing-item rules remain study-specific.', 'vaccine_dose':'Author dictionary describes ordinal dose number; this is not a mass or volume dose.', 'seroconversion':'May encode category or quantitative definition; source assay and threshold required.', 'symptom_group_previous_covid':'Historical COVID outcome; not current influenza challenge symptoms.', 'turbo_reatment':'Preserve published misspelling as source field; a normalized alias may be added separately.'}
fields=[]
for r in rows('hf__Meta_variable_description.csv'):
 n=r['Variable Name']; fields.append({'name':n,'author_definition':r['Description'],'definition_source_id':'hf_variables','units':units.get(n),'missing_semantics':'NA or empty means unavailable/not populated, never negative or zero; reason not uniformly encoded','dictionary_caution':notes.get(n),'value_type':'source_preserving_string; parse only after study-specific validation'})
studydefs={'study_ID':'Harmonized study or cohort label; may split one source accession into pathogen or tissue cohorts.','platform':'Broad transcriptomic assay class.','platform_detail':'Source platform accession, instrument or array description.','study_type':'Author exposure category; inoculation, vaccine and mixed exposure do not by themselves prove a wild-type influenza challenge.','pathogen':'Author labels, sometimes semicolon-delimited multiple pathogens.','vaccine':'Vaccine label; missing is not proof of no vaccination.','tissue':'Study-level specimen summary; resolve finer sample and cell-level distinctions.','raw_data':'Legacy author yes/no flag. It is not a current downloadable-file inventory, instrument-raw guarantee or verified source availability.','antibody':'Author flag for antibody availability; source tables and current links require separate verification.','num_subjects':'Author study-level participant count; do not sum as unique persons across related cohorts.','num_observations':'Author number of expression profiles/observations, not independent participants.','num_cells':'Author single-cell count; not specimens or persons.','num_observed_genes':'Author number of observed genes per study; differs from padded shared gene-column count.','number_of_timepoints median(min, max)':'Formatted within-study summary; do not infer a universal common sampling schedule.','observed_timepoints':'Text list of observed time labels; day zero, baseline and exact units must be interpreted per study.','meta_variable_list':'Semicolon-delimited list of metadata variables available for the study; h5ad rows may instead point to obs.'}
met=rows('hf__example_dataset__GSE194378_meta_sample.csv'); ant=rows('hf__example_dataset__GSE194378_antibody_sample.csv')
example={'source_ids':['hf_example_meta','hf_example_antibody'],'metadata_rows':len(met),'metadata_distinct_sample_row_ids':len(set(r[''] for r in met)),'metadata_distinct_subject_ids':len(set(r['ID'] for r in met)),'antibody_rows':len(ant),'antibody_distinct_subject_ids':len(set(r['ID'] for r in ant)),'metadata_columns':len(met[0]),'antibody_columns':len(ant[0]),'all_metadata_row_names_equal_geo_accession':all(r['']==r['geo_accession'] for r in met),'antibody_ids_missing_from_metadata':sorted(set(r['ID'] for r in ant)-set(r['ID'] for r in met)),'scope':'Downloaded example files only; not proof of current full matrices or cohort enrollment counts.'}
schema={'schema_version':'1.0.0','resource':'HR-VILAGE-3K3M','observed_on':DATE,'github_revision':GH,'huggingface_revision':HF,'status':'documentation_and_small_table_audit; full matrix structures not inspected','tables':[
 {'table':'study_meta.csv','grain':'One harmonized study/cohort per row','key':['study_ID'],'fields':[{'name':n,'definition':d,'source_id':'hf_studies','evidence_status':'inspected_header;definition_inferred_from_author_documentation'} for n,d in studydefs.items()]},
 {'table':'study_citations.csv','grain':'One provenance row per harmonized study/cohort','key':['study_ID'],'fields':[{'name':n,'definition':d,'source_id':'hf_citations'} for n,d in {'study_ID':'Join to study_meta.study_ID','source_paper_citation':'Citation of originating scientific publication','data_citation':'Citation of repository deposition','transcriptomic_data_link':'Original transcriptomic record URL; may contain raw and processed assets','metadata_link':'Original record or supplementary location for metadata','antibody_link':'Source antibody location, unavailable marker or not-applicable marker'}.items()]},
 {'table':'meta/<study_ID>_meta.csv','grain':'One expression observation/sample row, with participant-level fields repeated over visits','key':['study_ID','source_row_name'],'fields':[{'name':'source_row_name','source_header':'','definition':'Unnamed leading CSV index; preserve exactly for expression joins','source_id':'hf_example_meta'}]+fields,'join_rule':'Join expression source row names to metadata row names within the same study and revision. Require unique keys and report unmatched rows; never align by current row order.'},
 {'table':'bulk_gene_expr/<study_ID>_gene_expr.csv','grain':'Sample × gene matrix','row_key':['study_ID','source_row_name'],'column_key':'HGNC-oriented gene label, including harmonized padding columns','value_units':'Study- and processing-specific; unresolved until per-file provenance checked','source_ids':['hf_card','paper_v2','RNAseq_Process','Illumina_microarray_process'],'status':'Author documented sample-by-gene; complete matrices not read in this lane','missing_semantics':'Missing padded/unobserved genes must not become expression zeros; 41,667 shared columns and 9,004 universally nonmissing genes are author claims, not independently counted here.'},
 {'table':'antibody/<study_ID>_antibody.csv','grain':'Study-specific table; inspected example has one participant row and antigen/assay/time columns plus derived outcomes','key':['study_ID','ID'],'source_ids':['hf_card','hf_example_antibody'],'fields':[{'name':n,'definition':'Within-study participant identifier' if n=='ID' else 'Derived maximum fold change' if n=='MFC' else 'Derived response category' if n=='responder' else 'Study-specific antibody endpoint; preserve exact label; explicit assay and unit unresolved here','units':'dimensionless ratio' if n=='MFC' else None} for n in ant[0]],'join_rule':'Within-study subject-level join is one-to-many to longitudinal metadata. For a long measurement table also key by assay, antigen, visit and replicate. Do not join independently only on a day number.','missing_semantics':'NA is not zero, below-detection, no immunity, or uninfected. Preserve censored strings and unit conventions.'},
 {'table':'singel_cell_gene_expr/<study_ID>.h5ad','grain':'Cell × gene matrix with linked per-cell obs and per-gene var; directory spelling is literal','key':['dataset','source_obs_name'],'source_ids':['hf_card','merge_code','Meta_preprocess_demo','Single_cell_merge_data_demo'],'status':'Documented objects/code inspected; H5AD bytes not downloaded','fields':[{'name':n,'definition':d} for n,d in {'X':'Primary expression matrix; rawness must be inspected per artifact/layer','obs.sample_id':'Sample identifier, sometimes a BioSample accession','obs.donor_id':'Participant ID within source cohort','obs.dataset':'Source dataset label; may require explicit map to study_ID','obs.time_point_day':'Harmonized nominal day; can be derived from pooled labels','obs.cell_type':'Author cell annotation; method/version context required','obs.sex':'Source participant sex label; published demo contains mixed forms and missing strings','obs.age':'Participant age; may be numeric-looking string','obs.tissue':'Cell/sample specimen; demo includes PBMC, LN, Nasal and blood','obs.study_type':'Exposure group descriptor','obs.covid_status':'COVID-specific status, not influenza status','var_names':'Gene identifiers; versions and uniqueness transformations should be retained','layers':'Alternative count/normalized/scaled matrices, presence and exact semantics artifact-specific','raw':'AnnData raw slot; name does not guarantee instrument-raw or unnormalized values','obsm.X_pca / obsm.X_umap':'Derived dimension reductions','obsp.connectivities / obsp.distances':'Derived neighbor graphs'}.items()]}
 ],'example_checks':example,'global_join_rules':['Use study-qualified participant IDs; stable cross-study person equivalence requires source evidence.','GEO series may contain several harmonized cohorts; source accession is not a unique cohort key.','Keep longitudinal specimens, technical replicates, cells and participant counts distinct.','Do not sum paired bulk/single-cell studies or tissue subsets as independent subjects.','Do not infer clinical challenge from a pathogen or mixed-exposure tag alone.'], 'sources_file':'sources.json'}
dump('schema.json',schema)
trans=[
 {'id':'TR_AFFY','modality':'Affymetrix microarray','instrument_raw_examples':['CEL files'],'author_pipeline_summary':'CEL processing, probe mapping and gene selection, followed by distribution normalization.','inspected_demo':'GSE74816: ReadAffy; rma(normalize=FALSE); HGNChelper mapping; retain maximum median probe per symbol; omit missing rows; normalize.quantiles.','source_ids':['paper_v2','Affymetrix_microarray_process'],'output_rawness':'Processed gene-level intensities. RMA is already a transformed summary; do not re-log merely from generic paper wording. Demo code is illustrative, not an execution ledger for all matrices.'},
 {'id':'TR_ILLUMINA','modality':'Illumina microarray','instrument_raw_examples':['IDAT files'],'author_pipeline_summary':'Often starts with study-provided intensity tables because IDAT is unavailable.','inspected_demo':'GSE101710 CSV; map ILMN probes through HGNChelper; select highest median probe; quantile normalize. log2(Value+1) appears in plotting, while the illustrated saved processed object precedes that plot transform.','source_ids':['paper_v2','Illumina_microarray_process'],'output_rawness':'Harmonized gene intensities; neither a study-provided intensity table nor the processed CSV is equivalent to an IDAT.'},
 {'id':'TR_BULKRNA','modality':'Bulk RNA sequencing','instrument_raw_examples':['FASTQ/read files in source archive'],'author_pipeline_summary':'Gene mapping and count generation or reuse of source counts.','inspected_demo':'GSE190001 starts from a CSV, maps Ensembl genes with biomaRt, sums rows by HGNC symbol, then uses edgeR cpm. log2(Value+1) is used for plotting.','source_ids':['paper_v2','RNAseq_Process'],'output_rawness':'Counts are quantified measurements; CPM is additionally normalized. Current card calls bulk files processed/normalized. Do not apply an integer-count model or assume FASTQ-equivalence without per-file checks. Alignment reference, quantifier version and exact per-study path not established here.'},
 {'id':'TR_SCRNA','modality':'Single-cell RNA sequencing','instrument_raw_examples':['Sequencing read files'],'author_pipeline_summary':'Inputs include AnnData, 10x matrices and R objects; metadata alignment, gene filtering, normalization and log transformation are described.','inspected_demo':'Merger uses existing X; only if missing tries counts, raw_counts, log_norm, then raw.X. Takes intersection of genes, suffixes observation names, coerces metadata to strings and concatenates. The exploration object has log1p metadata, embeddings and neighbor graphs.','source_ids':['paper_v2','merge_code','Single_cell_merge_data_demo'],'output_rawness':'Gene-by-cell counts already follow alignment, barcode/UMI processing and cell calling. X, layers and raw must be assessed independently; a fallback can be normalized. Merged visualization object is derived. H5AD contents themselves remain uninspected.'},
 {'id':'TR_META','modality':'Metadata/time','instrument_raw_examples':[],'inspected_demo':'GSE195673 metadata example maps d28+d35 to the mean day 31.5, maps BioSample to sample_id, and retains donor IDs. Merging can turn missing values into literal strings and discard duplicate column names.','source_ids':['Meta_preprocess_demo','merge_code','hf_variables'],'output_rawness':'Curated/derived metadata. Preserve original pooled time, lower/upper day bounds and representative-time rule; day 31.5 is not evidence of a draw at 31.5 days. Blank, NA, nan and <NA> require explicit missingness mapping.'},
 {'id':'TR_ANTIBODY','modality':'Antibody measurements/outcomes','instrument_raw_examples':['Assay instrument readout files, when supplied by originating study'],'inspected_demo':'GSE194378 example mixes antigen/time endpoint columns with computed MFC and responder. Binding-type decimal endpoints and dilution-like titers must not be assumed to share an assay or unit.','source_ids':['hf_card','hf_example_antibody','hf_variables','paper_v2'],'output_rawness':'Author raw-antibody label denotes supplied measured endpoint tables, not guaranteed plate-reader/flow/instrument output. Assay units, censoring, baseline denominator and strain-specific rules must be resolved in source supplements.'}
]
dump('transformations.json',{'version':'1.0.0','transformations':trans,'interpretation_rule':'Keep instrument raw, quantified measurements, normalized values, curated metadata and derived outcomes as distinct processing levels; use unknown when artifact-specific evidence is absent.'})
# Explicit source-documented relationships, not new inferred identity claims.
relations=[{'retained':['GSE73072_H3N2_DEE2','GSE73072_H1N1_DEE4'],'excluded_related':'GSE52428','relationship':'author-reported overlapping duplicate cohorts'},{'retained':['GSE73072_H3N2_DEE2'],'excluded_related':'GSE30550','relationship':'author-reported overlapping duplicate cohort'},{'retained':['GSE73072_HRV_UVA','GSE73072_RSV_DEE1','GSE73072_H3N2_DEE2'],'excluded_related':'GSE17156','relationship':'author-reported overlapping duplicate cohorts'},{'studies':['GSE201533','GSE201534'],'relationship':'author-reported paired bulk/single-cell subjects'},{'studies':['GSE246525','GSE246937'],'relationship':'author-reported paired bulk/single-cell subjects'}]
leads=[]
citations={r['study_ID']:r for r in rows('hf__study_citations.csv')}
for r in rows('hf__study_meta.csv'):
 if (r['study_type']=='inoculation' and r['pathogen'] in ['H1N1','H3N2','influenza']) or (r['study_type']=='mixed exposure' and 'influenza' in r['pathogen'].lower()):
  leads.append({'study_ID':r['study_ID'],'source_study_type':r['study_type'],'pathogen':r['pathogen'],'num_subjects_author':int(r['num_subjects']),'num_observations_author':int(r['num_observations']),'source_links':citations.get(r['study_ID']),'screening_status':'HR-VILAGE influenza inoculation lead; confirm source trial/strain/arm' if r['study_type']=='inoculation' else 'Mixed-exposure context; not confirmed influenza challenge from HR-VILAGE label','source_ids':['hf_studies','hf_citations']})
versions={'observed_on':DATE,'paper_version':'arXiv 2505.14725v2, 31 May 2026','github_revision':GH,'huggingface_revision':HF,'current_dataset_version_author':'V3, 28 August 2026','dataset_doi':'10.57967/hf/9892','current_license_author':'CC-BY-4.0; underlying studies retain original source terms','changes':[{'date':'2025-09-09','author_statement':'Corrected GSE194378, GSE199750 and GSE276544 expression files.'},{'date':'2025-10-13','author_statement':'V2 updates GSE169159; adds GSE230494 antibodies and metadata; adds gene/time summaries and variable definitions.'},{'date':'2026-08-28','author_statement':'V3 removes bulk_gene_expr_raw; adds study_citations and dataset DOI/CC-BY-4.0.'}],'version_cautions':[{'issue':'Paper versus current release','finding':'May 2026 paper describes raw files redistributed; August 2026 V3 says raw source expression files were removed. Use current file inventory and source-record links.'},{'issue':'Two study_meta copies','finding':'Current HF study_meta has 16 columns including gene/time summaries; current GitHub study_meta has 13 columns. Both have 66 rows. They are not interchangeable snapshots.'},{'issue':'Example counts','finding':f'Current downloaded HF example metadata has {len(met)} rows and {len(set(r["ID"] for r in met))} distinct subjects; antibody has {len(ant)} rows. Card says 386/72. These are examples, not full study totals.'},{'issue':'Raw count claims','finding':'README X count claim and paper/demo transformations do not establish every current H5AD layer. Per-artifact inspection required.'},{'issue':'Legacy raw_data flag','finding':'Retained in current study_meta despite removal of raw-expression folder; do not treat as a resolved availability status.'},{'issue':'Loader version','finding':'README offers revision=script, whereas inventory is main revision. Pin exact revisions; no remote loader code executed in this audit.'}],'source_ids':['paper_v2','github_readme','hf_card','hf_studies','gh_studies','hf_example_meta','hf_example_antibody'],'relationships':relations,'relationship_source_id':'github_readme','influenza_leads':leads,'limits':['This lane audits HR-VILAGE documentation, code and small tables. It is not a census of all influenza challenge studies.','Author count 3178 does not prove 3178 distinct independent persons after paired modalities, repeated challenges or cross-source duplication.','Same research group and similar pipelines do not prove negligible batch effects.','Study citations locate records, not a verified complete list of retrievable raw assets.']}
dump('version_notes.json',versions)
print(json.dumps({'fields':len(fields),'sources':len(sources),'example_checks':example,'influenza_leads':len(leads)},indent=2))
# Locators link inferred rules back to exact inspected fields or code blocks.
schema=json.loads((BASE/'schema.json').read_text())
for t in schema['tables']:
 if t['table']=='meta/<study_ID>_meta.csv':
  for i,f in enumerate(t['fields']):
   if i: f['source_locator']=f"Meta_variable_description.csv, row {i+1} (header is row 1), Variable Name={f['name']}"
   else:f['source_locator']='example_dataset/GSE194378_meta_sample.csv, leading unnamed header and sample index'
 elif t['table']=='study_meta.csv':
  for f in t['fields']:f['source_locator']=f"study_meta.csv, header column {f['name']}"
 elif t['table']=='study_citations.csv':
  for f in t['fields']:f['source_locator']=f"study_citations.csv, header column {f['name']}"
 elif t['table']=='bulk_gene_expr/<study_ID>_gene_expr.csv':t['source_locators']=['HF README.md, Data Structure, bulk_gene_expr bullet','Paper v2, Methods, Data processing; platform-specific demos as transformation records']
 elif t['table']=='antibody/<study_ID>_antibody.csv':
  for f in t['fields']:f['source_locator']=f"example_dataset/GSE194378_antibody_sample.csv, header column {f['name']}"
 elif t['table'].startswith('singel_cell'):
  for f in t['fields']:f['source_locator']='HF README.md, Single cell gene expression data; docs/Single_cell_merge_data_demo.qmd, output Out[2]; code/Merge_Plot_Demo.py, ensure_sparse_X and common_fields'
dump('schema.json',schema)
trans=json.loads((BASE/'transformations.json').read_text())
locs={'TR_AFFY':[('docs__Affymetrix_microarray_process.qmd.text',102,'RMA call; gene mapping starts below; quantile normalization at line 143')], 'TR_ILLUMINA':[('docs__Illumina_microarray_process.qmd.text',129,'QN call; later plot-only log transformation')], 'TR_BULKRNA':[('docs__RNAseq_Process.qmd.text',133,'CPM call after gene-level sum; later plot-only log transformation')], 'TR_SCRNA':[('code__Merge_Plot_Demo.py',43,'ensure_sparse_X fallback'),('code__Merge_Plot_Demo.py',74,'common gene intersection'),('docs__Single_cell_merge_data_demo.qmd.text',101,'Displayed AnnData object and derived slots')], 'TR_META':[('docs__Meta_preprocess_demo.qmd.text',276,'parse_gse195673_time averaged pooled day labels'),('code__Merge_Plot_Demo.py',103,'NA addition; metadata string coercion at 114')], 'TR_ANTIBODY':[('hf__example_dataset__GSE194378_antibody_sample.csv',1,'Endpoint headers and derived MFC/responder')]}
for t in trans['transformations']:
 t['source_locators']=[{'snapshot_path':str((S/p).relative_to(BASE.parent.parent.parent)),'line':line,'description':desc,'is_derived_text':p.endswith('.text')} for p,line,desc in locs[t['id']]]
dump('transformations.json',trans)
v=json.loads((BASE/'version_notes.json').read_text())
v['source_locators']=['HF README.md lines44–55: release history; lines60–91: data descriptions and example count claims','GitHub README.md lines151–166: duplicate/pair relations','study_meta.csv: keyed source rows specified in influenza_leads; cited fields are author-study summaries','study_citations.csv: keyed rows specified in influenza_leads']
dump('version_notes.json',v)
# Preserve readable derivatives with a hash binding to the public originals.
manifest=json.loads((BASE/'sources.json').read_text())
manifest['reading_derivatives']=[]
for p in S.glob('*.text'):
 original=p.with_name(p.name[:-5])
 manifest['reading_derivatives'].append({'path':str(p.relative_to(BASE.parent.parent.parent)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'derived_from':str(original.relative_to(BASE.parent.parent.parent)),'original_sha256':hashlib.sha256(original.read_bytes()).hexdigest(),'transform':'Python HTMLParser removed script/style contents and inserted tag-boundary newlines; no source meaning added.'})
dump('sources.json',manifest)
