import json,re,hashlib
from pathlib import Path
P=Path('data_dictionary/sources/influenza');S=P/'snapshots';records=json.load(open(P/'studies.json'))
def base(a,title,url,modality,prep,availability,paths):
 return {'id':a,'accession':a,'title':title,'repository':'primary publication / linked repository','source_url':url,'eligibility':'included_human_influenza_challenge','eligibility_reason':'Primary source describes deliberate influenza inoculation of human volunteers.','eligibility_evidence':{'snapshot_path':paths[0],'locator':'Study design / Methods / data availability'},'organism':'Homo sapiens','pathogen':'Influenza A virus','strain':None,'study_design':'Human influenza challenge; retain original study/arm/participant IDs.','preparation':prep,'modality':modality,'sample_count_repository':None,'participant_count':None,'raw_data':{'availability':availability,'description':'See record-specific details.'},'processed_data':{'availability':'unverified','description':'See files and paper supplements.'},'files':[],'file_formats':[],'relationships':[],'cohort_reuse':[],'missing_info':[],'citations':[url],'source_paths':paths,'retrieved_on':'2026-09-14','curation_status':'source_checked_catalogue_pending_review'}
for a in ['E-MTAB-13038','E-MTAB-13041']:
 x=json.load(open(S/(a+'.json')));attrs={v['name']:v.get('value') for v in x['section']['attributes']}
 r=base(a,attrs['Title'],'https://www.ebi.ac.uk/biostudies/arrayexpress/studies/'+a,['bulk RNA-seq'],'nasal scrape' if a.endswith('038') else 'whole blood','unverified' if a.endswith('038') else 'controlled',[str(S/(a+'.json')),str(S/'PMC11608262.html'),str(S/'PMC13375583.html')]);r['repository']='ArrayExpress / BioStudies';r['strain']='A/Belgium/4217/2015 (H3N2)';r['study_design']=attrs['Description'];r['processed_data']={'availability':'public','description':'Repository explicitly lists processed expression counts and IDF/SDRF metadata.'};r['raw_data']['description']='Blood raw RNA-seq is controlled in EGAD50000000956; nasal raw-read repository not established from the inspected sources.';r['relationships']=['EGAD50000000956','NCT02755948','NCT04204993'];r['cohort_reuse']=['Nasal/blood records overlap Imperial H3N2 challenge cohorts and 2024/2026 publications; they are modalities of related cohorts, not independent studies.'];r['file_formats']=['TXT','CSV','IDF','SDRF'];
 def walk(v):
  if isinstance(v,dict):
   if v.get('type')=='file' and 'path' in v:r['files'].append({'name':v['path'],'size_bytes':v.get('size'),'data_level':'metadata' if '.idf.' in v['path'] or '.sdrf.' in v['path'] else 'processed_expression','availability':'public','url':r['source_url'],'repository_file_path':v['path'],'verification':'listed_in_repository_API; payload not downloaded'})
   for vv in v.values():walk(vv)
  elif isinstance(v,list):
   for vv in v:walk(vv)
 walk(x);r['missing_info']=['Public catalogue listing verified; processed matrix payload not downloaded. Exact participant overlap must use SDRF identifiers.'];records.append(r)
a='EGAD50000000956';r=base(a,'Longitudinal whole-blood RNA-seq following controlled influenza H3N2 inoculation','https://ega-archive.org/datasets/'+a,['bulk RNA-seq'],'whole blood','controlled',[str(S/(a+'.html')),str(S/'PMC11608262.html')]);r.update(repository='European Genome-phenome Archive',strain='A/Belgium/4217/2015 (H3N2)',participant_count=19,file_formats=['FASTQ.GZ']);r['raw_data']['description']='Managed-access sequencing files are listed publicly; access requires approved data use within participant consent and a data access agreement.';r['relationships']=['EGAS50000000679','E-MTAB-13041','E-MTAB-13038'];r['cohort_reuse']=['Raw blood modality of the Imperial H3N2 challenge; not an extra independent cohort.'];r['files']=[{'url':r['source_url'],'name':'EGA controlled FASTQ file manifest','data_level':'raw_reads','availability':'controlled','format':'FASTQ.GZ','verification':'dataset page lists EGAF files; no controlled data downloaded'}];r['missing_info']=['DAC approval not requested; participant-level records not downloaded.'];records.append(r)
r=base('FR-FCM-Z2NZ','Landscape of coordinated immune responses to H1N1 challenge in humans','https://flowrepository.org/id/FR-FCM-Z2NZ',['mass cytometry','CBC','viral qRT-PCR','HA/stalk antibody ELISA','symptom scores'],'peripheral blood / nasopharyngeal swabs','public',[str(S/'JCI137265.html')]);r.update(repository='FlowRepository',strain='A/California/2009 (H1N1)',participant_count=35,sample_count_repository=381,file_formats=['FCS','supplementary tables']);r['raw_data']={'availability':'public','description':'Primary paper states study data and code are public in FR-FCM-Z2NZ. Direct repository TLS certificate expired during retrieval; raw FCS member inventory remains unverified.'};r['files']=[{'url':r['source_url'],'data_level':'single_cell_cytometry_data','availability':'public','verification':'primary_paper_declaration; repository retrieval failed expired certificate','format':'FCS (measurement workflow; exact deposited members not inspected)'}];r['relationships']=['NCT04106817'];r['cohort_reuse']=['Reanalyzed as Study A in 2026 Flu-Day-Prediction paper.'];r['missing_info']=['Validate current repository transport and enumerate deposited FCS/raw versus normalized files. Clinical/antibody/viral-load participant-level supplement inventory not yet expanded.'];records.append(r)
r=base('MCILWAIN2021_CHALLENGE','Human influenza virus challenge identifies cellular correlates of protection for oral vaccination','https://doi.org/10.1016/j.chom.2021.10.009',['mass cytometry','HAI','microneutralization','ELISPOT','viral qRT-PCR','Flu-PRO symptoms'],'whole blood; serum; nasopharyngeal swabs','request_only',[str(S/'PMC8665113.html')]);r.update(strain='A/California/2009 (H1N1)',participant_count=141,file_formats=['FCS','XLSX']);r['study_design']='Oral VXA-A1.1, injected IIV, or placebo vaccination followed by influenza inoculation >=90 days later; analysed cellular pre/post-vaccination data linked to subsequent challenge outcomes.';r['raw_data']['description']='Primary paper states raw data, processed data and source code available from lead contact upon reasonable request; no request sent.';r['processed_data']={'availability':'public','description':'Supplementary XLSX tables provide selected analyses; not proof full raw cytometry is publicly downloadable.'};r['relationships']=['NCT02918006'];r['cohort_reuse']=['Parent vaccine-challenge trial from Liebowitz et al.; related cohort reused by 2026 Flu-Day-Prediction.'];r['files']=[{'url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC8665113/','name':'Supplementary XLSX tables','availability':'public','data_level':'processed_summary','verification':'primary PMC article lists supplement files'}];r['missing_info']=['Full deposited FCS and participant-level clinical raw files require a data request.'];records.append(r)
r=base('BURKE2017_NPL','Nasopharyngeal Protein Biomarkers of Acute Respiratory Virus Infection','https://doi.org/10.1016/j.ebiom.2017.02.015',['2D-LC-MS/MS discovery proteomics','targeted MRM proteomics'],'nasopharyngeal lavage','unverified',[str(S/'PMC5360578.html')]);r['strain']='H3N2; exact strain cohort specific';r['study_design']='Human influenza H3N2 and rhinovirus challenge cohorts; discovery pooled lavage and separate individual targeted MRM measurements.';r['mixed_study_rule']='Include two H3N2 cohorts only; keep HRV cohorts separate; pooled proteomic discovery is not individual sample abundance.';r['raw_data']['description']='Primary Methods document mass-spectrometry measurements, but no raw instrument-file repository accession found in inspected full article.';r['processed_data']={'availability':'public','description':'Supplementary data linked from PMC article; exact complete feature matrix contents not yet enumerated.'};r['files']=[{'url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC5360578/','name':'Supplementary material','availability':'public','data_level':'supplementary_processed_or_protocol','verification':'listed_in_primary_article; binary supplement not inspected'}];r['cohort_reuse']=['Duke challenge participants overlap the GSE73072 research programme; do not count as independent transcriptomic validation without sample crosswalk.'];r['missing_info']=['Raw mass-spectrometer files and stable repository accession unresolved.'];records.append(r)
r=base('FLU_DAY_PREDICTION2026','Estimating time since influenza virus exposure using single-cell proteomic data','https://doi.org/10.3389/fimmu.2026.1787198',['mass cytometry derived cell populations','viral shedding','challenge day'],'whole blood','unverified',[str(S/'PMC13044454.html')]);r['strain']='A/California/2009 (H1N1)';r['repository']='Primary publication / GitHub';r['processed_data']={'availability':'public','description':'Model-building data are in Supplementary Tables 3 and 4; code on GitHub.'};r['raw_data']['description']='Reanalysis: do not treat model tables called raw/un-normalized as original FCS instrument data. Follow original source cohorts.';r['files']=[{'url':'https://github.com/davemcilwain/Flu-Day-Prediction','data_level':'code_and_derived_model_data','availability':'public','verification':'primary_paper_link; repository tree not inspected'},{'url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC13044454/','name':'Supplementary Tables 3 and 4','data_level':'processed_model_inputs','availability':'public','verification':'primary_paper_data_availability'}];r['cohort_reuse']=['Reuses NCT04106817 (Rahil2020) and NCT02918006 (Liebowitz2020) cohorts; no new independent challenge cohort.'];r['relationships']=['FR-FCM-Z2NZ','MCILWAIN2021_CHALLENGE','NCT04106817','NCT02918006'];r['missing_info']=['Repository and supplementary table field inventories pending.'];records.append(r)
r=base('IMPERIAL_H3N2_MULTIMODAL2026','Innate immune responsiveness predicts enhanced cellular immunity and symptomatic disease after controlled human influenza infection','https://doi.org/10.1038/s41591-026-04483-7',['flow cytometry','functional immune assays','antibody assays','viral qRT-PCR','symptom diaries','bulk RNA-seq'],'blood; nasal samples; respiratory immune samples','request_only',[str(S/'PMC13375583.html')]);r['strain']='A/Belgium/4217/2015 (H3N2)';r['study_design']='Combined two sequential human inoculation cohorts NCT02755948 and NCT04204993; nasal dose 5e5 TCID50, quarantine to day10, follow-up days14/28/180.';r['raw_data']={'availability':'request_only','description':'Deidentified participant data for individual-participant meta-analysis available only from 12 months through 5 years after publication upon written request and data agreement. Published 2026-07-01, so this request window has not opened as of 2026-09-14. Raw blood RNA is already managed under EGAD50000000956.','request_window_begins':'2027-07-01','request_window_ends':'2031-07-01'};r['processed_data']={'availability':'public','description':'Nasal RNA counts E-MTAB-13038 and selected supplementary tables; broader clinical/immune raw data request restricted.'};r['files']=[{'url':'https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-13038','data_level':'processed_nasal_expression','availability':'public','verification':'primary_article_and_repository_metadata'},{'url':'https://ega-archive.org/datasets/EGAD50000000956','data_level':'raw_blood_RNA_reads','availability':'controlled','verification':'primary_article_and_repository_metadata'}];r['relationships']=['NCT02755948','NCT04204993','EGAD50000000956','E-MTAB-13038','E-MTAB-13041'];r['cohort_reuse']=['Same Imperial challenge programme as 2024 Rosenheim biomarker analysis; preserve cohort and specimen crosswalk.'];r['missing_info']=['Full raw cytometry and clinical participant datasets not currently public; future request window explicitly limited to IPD meta-analysis.'];records.append(r)
# Upgrade only verified raw sequence link, never from count-file name.
for r in records:
 if r['id']=='GSE299820':
  r['raw_data']={'availability':'public','description':'Representative GEO sample GSM9046530 explicitly links SRA experiment SRX29176614; full run manifest not yet enumerated.'};r['files'].append({'url':'https://www.ncbi.nlm.nih.gov/sra?term=SRX29176614','name':'SRX29176614','data_level':'raw_RNA_reads','availability':'public','verification':'representative_GEO_sample_SRA_relation; experiment/run download not performed'});r['source_paths'].append(str(S/'GSM9046530.soft.txt'));r['relationships'].append('NCT03883113');r['missing_info']=[m for m in r['missing_info'] if 'no SRA' not in m];r['missing_info'].append('Linked primary paper additionally reports single-cell RNA, ATAC and methylation; these repositories require follow-up and are not assumed to reside in this bulk accession.')
 if r['id']=='GSE175551':r['source_paths'].append(str(S/'GSM5341480.soft.txt'));r['missing_info'].append('Representative sample is labelled SRA but provides only a BioSample relation; actual raw experiment/run accession remains unresolved.')
 r['source_hashes']={p:hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in r['source_paths']}
json.dump(records,open(P/'studies.json','w'),indent=2)
print(len(records),'records')
