import json,re,copy,hashlib,csv
from pathlib import Path
from html.parser import HTMLParser
from urllib.parse import urljoin
P=Path('data_dictionary/sources/influenza');S=P/'snapshots';recs=json.load(open(P/'studies.json'))
def base(a,title,url,prep,mods,raw,paths):
 r=copy.deepcopy(next(x for x in recs if x['id']=='BURKE2017_NPL'));r.update(id=a,accession=a,title=title,source_url=url,preparation=prep,modality=mods,source_paths=paths,strain=None,participant_count=None,sample_count_repository=None,files=[],file_formats=[],relationships=[],cohort_reuse=[],missing_info=[],citations=[url],raw_data={'availability':raw,'description':''},processed_data={'availability':'unverified','description':''},eligibility_evidence={'snapshot_path':paths[0],'locator':'Study design / Methods / Data availability'});r.pop('mixed_study_rule',None);r.pop('source_hashes',None);return r
for a,prep in [('GSE253685','PBMC'),('GSE253686','nasal epithelium')]:
 t=(S/(a+'.soft.txt')).read_text();title=re.search(r'!Series_title = (.*)',t).group(1);r=base(a,title,'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc='+a,prep,['expression microarray'],'public',[str(S/(a+'.soft.txt')),str(S/'PMC12375958.html')]);r['repository']='NCBI GEO';r['strain']='A/Bethesda/MM2/H1N1';r['study_design']='NIH human influenza H1N1 challenge, vaccinated/unvaccinated cohorts with complex pre-existing immunity; NCT01971255.';r['relationships']=['NCT01971255','KAW2025STM','WALTERS2025_IMMUNE'];r['cohort_reuse']=['PBMC and nasal arrays, repertoire and protein/antibody profiles are paired modalities from the same challenge study; do not count as separate participant cohorts.'];r['sample_count_repository']=len(re.findall(r'!Series_sample_id = ',t));r['raw_data']['description']='GEO lists original raw archive; member files not downloaded.';r['processed_data']={'availability':'public','description':'Normalized expression workbook explicitly listed in GEO.'}
 for u in re.findall(r'!Series_supplementary_file = (.*)',t):r['files'].append({'url':u.replace('ftp://','https://'),'name':u.rsplit('/',1)[-1],'data_level':'raw_array_archive' if 'RAW.tar' in u else 'normalized_expression','availability':'public','verification':'listed_in_GEO_series_metadata'})
 r['file_formats']=['TAR','XLSX'];r['missing_info']=['Array archive members and sample-to-clinical participant crosswalk not expanded.'];recs.append(r)
r=base('KAW2025STM','Adaptive B and T cell VDJ immunosequencing from NIH influenza challenge','https://doi.org/10.21417/KAW2025STM','blood immune repertoire',['BCR sequencing','TCR sequencing'],'unverified',[str(S/'PMC12375958.html'),str(S/'KAW2025STM.html')]);r['repository']='Adaptive immuneACCESS';r['strain']='A/Bethesda/MM2/H1N1';r['study_design']='B/T repertoire measurements in vaccinated and unvaccinated NIH human challenge participants.';r['raw_data']['description']='Primary paper declares VDJ immunosequencing data at immuneACCESS; landing page retrieved but downloadable read-level versus repertoire-level files not enumerated.';r['processed_data']={'availability':'public','description':'Public repertoire dataset declared by paper; table-level schema/access restrictions must be inspected.'};r['files']=[{'url':'https://clients.adaptivebiotech.com/pub/walters-2025-stm','data_level':'repertoire_data_unspecified_processing','availability':'public','verification':'primary_paper_declaration_and_landing_page; file listing not inspected'}];r['relationships']=['NCT01971255','GSE253685','GSE253686','WALTERS2025_IMMUNE'];r['cohort_reuse']=['Same NIH cohort as the two GEO transcriptomic accessions.'];r['missing_info']=['Determine whether original FASTQ or only processed clonotype tables can be obtained, plus registration/license requirements.'];recs.append(r)
r=base('WALTERS2025_IMMUNE','Nasal and systemic immune responses correlate with viral shedding after influenza challenge in people with complex preexisting immunity','https://pmc.ncbi.nlm.nih.gov/articles/PMC12375958/','nasal mucosa, blood and serum',['Olink inflammation proteins','antibody HAI/neutralization','viral shedding','symptoms','BCR/TCR repertoire'],'unverified',[str(S/'PMC12375958.html')]);r['strain']='A/Bethesda/MM2/H1N1';r['study_design']='80 participants enrolled (40 vaccinated/40 unvaccinated); analysed modality subsets differ. Retain per-assay N; nasal protein profile illustrated for 66 participants.';r['relationships']=['NCT01971255','GSE253685','GSE253686','KAW2025STM'];r['raw_data']['description']='Article declares all associated data in paper/supplements, but instrument-level Olink assay output is not established. NPX protein values are normalized and are not absolute concentration.';r['processed_data']={'availability':'public','description':'Extensive XLSX supplement tables include protein, antibody and clinical analyses; table field inventory pending.'};r['cohort_reuse']=['Same NIH human challenge cohort across both GEO arrays and immuneACCESS repertoire data.'];r['missing_info']=['Enumerate supplement columns and participant crosswalk; original instrument raw files are not confirmed.'];r['file_formats']=['XLSX','PDF'];
html=(S/'PMC12375958.html').read_text()
for u in sorted(set(re.findall(r'href="([^"]+supplement[^\"]+\.(?:xlsx|pdf))"',html))):r['files'].append({'url':urljoin(r['source_url'],u),'name':u.rsplit('/',1)[-1],'data_level':'supplementary_processed_or_protocol','availability':'public','verification':'listed_in_primary_article; binary payload not downloaded'})
recs.append(r)
sra=json.load(open(S/'sra_viral_summaries_all.json'))['result'];manifest=[]
for k in sra['uids']:
 v=sra[k];e=v['expxml'];study=re.search(r'<Study acc="([^"]+)"',e).group(1);exp=re.search(r'<Experiment acc="([^"]+)"',e).group(1);proj=re.search(r'<Bioproject>(.*?)</Bioproject>',e).group(1);title=re.search(r'<Title>(.*?)</Title>',e).group(1)
 for run in re.findall(r'<Run acc="([^"]+)"',v['runs']):manifest.append({'sra_uid':k,'study_accession':study,'bioproject':proj,'experiment_accession':exp,'run_accession':run,'title':title,'availability':'public','data_level':'raw_sequence_reads','source_url':'https://www.ncbi.nlm.nih.gov/sra/'+run,'source_path':str(S/'sra_viral_summaries_all.json')})
json.dump(manifest,open(P/'viral_sequence_runs.json','w'),indent=2)
for a,study,pmc,title,strain in [('SRP091397','SRP091397','PMC5126380','Deep sequencing of influenza A from a human challenge study','A/Wisconsin/67/2005 (H3N2)'),('PRJNA528931','SRP189350','PMC6652224','Deep sequencing of 2009 influenza H1N1 from challenge participants and natural infections','GMP-manufactured A/California/04/2009 (H1N1)pdm challenge virus')]:
 r=base(a,title,'https://www.ncbi.nlm.nih.gov/sra?term='+a,'nasal wash and challenge-virus stock',['viral RNA sequencing'],'public',[str(S/(pmc+'.html')),str(S/'sra_viral_summaries_all.json')]);r['repository']='NCBI SRA';r['strain']=strain;r['organism']='Influenza A virus sequenced from human participants or inoculum';r['raw_data']['description']='Public SRA run records verified; raw read files not downloaded. Expanded current repository may contain more sequencing experiments than the original paper subset.';r['files']=[dict(x,url=x['source_url'],name=x['run_accession'],verification='public_SRA_metadata') for x in manifest if x['study_accession']==study];r['file_formats']=['SRA','FASTQ via SRA export'];r['relationships']=[study]+sorted(set(x['bioproject'] for x in manifest if x['study_accession']==study));r['missing_info']=['Distinguish inoculum, human post-challenge samples, natural infection, passage controls, amplicon/resequencing replicates; repository run counts are not participant counts.'];r['study_design']='Deliberate human influenza infection plus sequencing controls; preserve biological origin of every viral sample.';r['mixed_study_rule']='Retain only challenge participant and explicitly designated inoculum/control samples; do not pool natural infection cases.' if a=='PRJNA528931' else 'Primary paper specifies SRR4416113–SRR4416125 (13 runs), while current study includes additional deposited runs; retain original-paper subset separately.';r['cohort_reuse']=['Duke/DARPA H3N2 challenge series may overlap GSE30550/GSE73072; subject mapping pending.'] if a=='SRP091397' else ['NIH challenge sequencing mixed with natural infection samples; mapping to other NIH cohorts requires explicit identifiers.'];recs.append(r)
x=json.load(open(S/'E-MTAB-15137.json'));attrs={a['name']:a.get('value') for a in x['section']['attributes']}
r=base('E-MTAB-15137',attrs['Title'],'https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-15137','whole blood aliquots with/without ex vivo BCG lux',['bulk RNA-seq','mycobacterial growth inhibition','cytokines','cellular assays'],'controlled',[str(S/'E-MTAB-15137.json'),str(S/'INFLUENZA_BCG2026.html')]);r['repository']='ArrayExpress / BioStudies';r['strain']='Influenza A H3N2';r['study_design']=attrs['Description'];r['mixed_study_rule']='Influenza challenge occurs in humans; BCG exposure is ex vivo in blood aliquots, not a human mycobacterial infection challenge.';r['raw_data']['description']='Raw RNA managed via EGA study EGAS50000001677 / dataset EGAD50000002407.';r['processed_data']={'availability':'public','description':'Processed RNA and metadata explicitly deposited in BioStudies; source data provided with publication.'};r['relationships']=['EGAS50000001677','EGAD50000002407'];r['cohort_reuse']=['Imperial influenza challenge cohort; longitudinal blood split into ex vivo BCG/control incubations, which are repeated conditions not independent participants.'];r['missing_info']=['Crosswalk to other Imperial datasets and per-assay participant/raw cytokine/cytometry files pending.'];
def walk(v):
 if isinstance(v,dict):
  if v.get('type')=='file' and 'path'in v:r['files'].append({'url':r['source_url'],'name':v['path'],'size_bytes':v.get('size'),'data_level':'metadata' if '.idf.' in v['path'] or '.sdrf.' in v['path'] else 'processed_expression','availability':'public','verification':'listed_in_repository_API'})
  for vv in v.values():walk(vv)
 elif isinstance(v,list):
  for vv in v:walk(vv)
walk(x);recs.append(r)
r=base('EGAD50000002407','Raw RNA sequencing for human influenza challenge / ex vivo BCG response','https://ega-archive.org/datasets/EGAD50000002407','whole blood aliquots with/without ex vivo BCG lux',['bulk RNA-seq'],'controlled',[str(S/'EGAS50000001677.html'),str(S/'INFLUENZA_BCG2026.html')]);r['repository']='European Genome-phenome Archive';r['strain']='Influenza A H3N2';r['raw_data']['description']='Parent EGA study page lists dataset EGAD50000002407; primary paper specifies managed access subject to participant consent and data agreement.';r['files']=[{'url':r['source_url'],'data_level':'raw_reads','availability':'controlled','verification':'parent_study_dataset_link_and_primary_paper; individual file inventory pending'}];r['relationships']=['EGAS50000001677','E-MTAB-15137'];r['cohort_reuse']=['Raw counterpart of E-MTAB-15137; same cohort and ex vivo conditions.'];r['missing_info']=['Individual controlled-file manifest not retrieved; no access application sent.'];recs.append(r)
r=base('MCCLAIN2016_CYTOKINES','Differential evolution of peripheral cytokine levels in symptomatic and asymptomatic responses to experimental influenza virus challenge','https://pmc.ncbi.nlm.nih.gov/articles/PMC4750592/','serum / peripheral blood',['25-plex cytokine assay','viral shedding','symptom scores'],'unverified',[str(S/'PMC4750592.html')]);r.update(strain='A/Wisconsin/67/2005 (H3N2)',participant_count=17);r['study_design']='Human inoculation with serial blood sampling, cytokines by Invitrogen human 25-plex assay; 9/17 symptomatic.';r['raw_data']['description']='Original assay acquisition files and complete subject-by-time cytokine matrix repository not identified in inspected article.';r['processed_data']={'availability':'public','description':'Paper figures and supporting PDF; not established as complete analyte-by-subject data table.'};r['cohort_reuse']=['17-subject H3N2 Duke challenge linked to previous transcriptomic work; likely overlaps GSE30550/H3N2 DEE2, require explicit crosswalk.'];r['relationships']=['GSE30550','GSE73072'];r['missing_info']=['Retrieve complete calibrated concentration tables, detection limits, and instrument raw files if publicly deposited or available upon request.'];recs.append(r)
for r in recs:
 if r['id']=='PRJNA528931':
  r['participant_count']=20;r['challenge_participant_count']=15;r['natural_infection_participant_count']=5
  r['study_design']='Nasal wash from 15 deliberately challenged human volunteers and five naturally infected 2009-pandemic patients; viral-targeted hybridization enrichment and deep sequencing. Counts from primary abstract, not SRA run count.'
 if r['id']=='GSE299820':
  r['raw_data'].update(verification_level='representative_GEO_sample_SRA_link',coverage='representative_experiment_only',complete_raw_file_manifest=False)
 if r['id']=='GSE175551':
  r['raw_data'].update(verification_level='GEO_sample_without_SRA_experiment_link',coverage='raw_read_access_unresolved',complete_raw_file_manifest=False)
 if r['id']=='FR-FCM-Z2NZ':
  r['raw_data'].update(verification_level='primary_paper_public_declaration',current_repository_access='unverified_due_to_expired_TLS_certificate',complete_raw_file_manifest=False)
 if r['id']=='IMPERIAL_H3N2_MULTIMODAL2026':
  r['raw_data'].update(request_status='not_yet_open',currently_requestable=False,availability_as_of='2026-09-14',scope='broader_deidentified_participant_data; separately_listed_RNA_access_is_already_available')
 if r['id'] in ['SRP091397','PRJNA528931']:
  r['raw_data'].update(verification_level='complete_returned_SRA_run_metadata',coverage='current_accession_run_manifest',complete_run_manifest=True,complete_raw_file_manifest=False,raw_file_payloads_downloaded=False)
 r['source_hashes']={p:hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in r['source_paths']}
assert len({r['id'] for r in recs})==len(recs)
json.dump(recs,open(P/'studies.json','w'),indent=2)
logs=json.load(open(P/'searches.json'))
for i,q in enumerate(['"human influenza challenge" "SRA"','"influenza challenge" "GenBank"','"influenza challenge" "cytokines" "data availability"','"influenza challenge" "metabolomics" human data deposit'],23):logs.append({'search_id':'FLU_WEB_%03d'%i,'searched_on':'2026-09-14','database':'web search','query':q,'total_hits':None,'retrieval_cap':'tool-ranked; no numerical cap exposed','screening':'Primary-paper hits followed, recovering NIH multiomics and viral sequencing datasets.'})
logs += [{'search_id':'FLU_SRA_002','searched_on':'2026-09-14','database':'NCBI SRA via Entrez skill','query':'SRP091397 OR PRJNA528931','total_hits':265,'initial_cap':100,'final_retrieval_cap':265,'returned_ids':265,'metadata_summarized':265,'raw_path':str(S/'sra_search_viral_all.json'),'screening':'Accession membership verified from all experiment summaries; not all individual runs assigned human challenge versus controls/natural infection.'},{'search_id':'FLU_CITATION_FOLLOWUP','searched_on':'2026-09-14','database':'Primary article data availability / repository lookups','query':'GSE253685; GSE253686; KAW2025STM; E-MTAB-15137; EGAS50000001677','screening':'Followed actual data availability statements; GEO human challenge and EGA managed access verified.'}]
logs=list({entry['search_id']:entry for entry in logs}.values())
json.dump(logs,open(P/'searches.json','w'),indent=2)
print(len(recs),'catalogue records,',len(manifest),'public SRA runs,',len(logs),'searches/lookups')
