import json, hashlib, re
from pathlib import Path
from datetime import datetime, timezone
from html.parser import HTMLParser

ROOT=Path(__file__).resolve().parent
BASE='research/mechanisms_antigen/'
NOW=lambda: datetime.now(timezone.utc).isoformat()
START='2026-09-13T19:19:19+00:00'
U='unavailable'
class Meta(HTMLParser):
    def __init__(self): super().__init__(); self.data={}
    def handle_starttag(self,tag,attrs):
        d=dict(attrs)
        if tag=='meta' and d.get('name','').startswith('citation_'):
            self.data.setdefault(d['name'],[]).append(d.get('content'))

source_specs=[
 ('MP_S001','MP_Restifo1996','https://pmc.ncbi.nlm.nih.gov/articles/PMC2248456/',1996,'Homo sapiens; Mus musculus in separate recipient assays','PMC author manuscript; NIHMS38285; final article 1996-01-17'),
 ('MP_S002','MP_deLaSalle1999','https://www.jci.org/articles/view/5687',1999,'Homo sapiens','Publisher version 1, 1999-03-01'),
 ('MP_S003','MP_deLaSalle2002','https://pmc.ncbi.nlm.nih.gov/articles/PMC1906261/',2002,'Homo sapiens; nonhuman primate COS cells in separate antigen assignment assay','PMC full text of published article'),
 ('MP_S004','MP_Landmann2001','https://pmc.ncbi.nlm.nih.gov/articles/PMC2193505/',2001,'Homo sapiens; Mus musculus experiments separate','PMC full text of published article'),
 ('MP_S005','MP_ERAP2021','https://pmc.ncbi.nlm.nih.gov/articles/PMC7611875/',2021,'Homo sapiens target cells and recombinant ERAP1; Mus musculus T-hybridoma recipient','PMC author manuscript; EMS133687; final article 2021-09-27'),
 ('MP_S006','MP_Kuilman2025','https://www.nature.com/articles/s41467-024-55420-6',2025,'Homo sapiens B-cell and Jurkat hosts; engineered TCR constant domains are murine','Publisher article 2025-01-14; supplementary information MOESM1'),
 ('MP_S007','MP_He2025','https://pmc.ncbi.nlm.nih.gov/articles/PMC12732238/',2025,'Homo sapiens primary B cells/PBMCs and cell lines; mouse T-hybridoma recipient in reporter assays','PMC full text of published article 2025-12-16'),
]
sources=[]
for sid,stem,url,year,species,version in source_specs:
    p=ROOT/'snapshots'/f'{stem}.html'; m=Meta();m.feed(p.read_text());d=m.data
    sources.append(dict(source_id=sid,title=d['citation_title'][0],authors=d.get('citation_author',U),year=year,url=url,doi=d['citation_doi'][0],pmid=d.get('citation_pmid',['39809767' if sid=='MP_S006' else U])[0],source_type='primary_study',version=version,retrieved_at=datetime.fromtimestamp(p.stat().st_mtime,timezone.utc).isoformat(),access_level='full_text_methods_results_inspected',snapshot_path=BASE+f'snapshots/{stem}.html',species=species,notes='Local parsed text is a companion locator; selected Methods and Results inspected. No independent or human review performed. Raw article access succeeded after web-tool access failures.',companion_snapshot_path=BASE+f'snapshots/{stem}.txt',correction_retraction_check='DOI-specific ranked searches and article notice/version areas checked on 2026-09-13; no relevant correction/retraction identified; absence is not certified.'))
sources[5]['additional_snapshots']=[BASE+'snapshots/MP_Kuilman2025_supplement.pdf',BASE+'snapshots/MP_Kuilman2025_supplement.txt',BASE+'snapshots/MP_Kuilman2025_supplement_p8.png',BASE+'snapshots/MP_Kuilman2025_supplement_p12.png']
sources[0]['additional_snapshots']=[BASE+'snapshots/MP_Restifo1996_fig5.jpg']
for s in sources: s['additional_snapshot_paths']=[s['companion_snapshot_path']]+s.get('additional_snapshots',[])
sources[6]['notes']+=' The published Methods contain HG00131/HG00313 and 1%-FDR/0.1-filename inconsistencies. No raw immunopeptidomics reanalysis performed.'

cohorts=[]
def cohort(cid,sid,tissue,cell,participants,counts=U,donors=U,parent=U,intervention=U,notes=U,accession=U):
    x=dict(cohort_id=cid,dataset_id=cid,accession=accession,study_id=sid,participants=participants,ancestry=U,species='Homo sapiens',tissue=tissue,cell_type=cell,disease=U,intervention=intervention,sample_count=counts,donor_count=donors,parent_cohort=parent,related_publications=[sid],independence_status='unresolved',notes=notes);cohorts.append(x);return x
cohort('MP_C001','MP_S001','subcutaneous melanoma deposits; lymph node','patient-derived melanoma cultures','five melanoma patients','five selected deficient lines from five patients',5,intervention='B2M-expressing recombinant vaccinia versus control',notes='Four selected lines from 13 successfully established cultures among 40 consecutively sampled patients; 1074mel separately derived outside that 40-person cohort. No prevalence inference from five selected deficient lines.')
cohort('MP_C002','MP_S001','subcutaneous melanoma deposit; donor TIL tissue unavailable','1074mel target plus expanded human HLA-A2.1-restricted anti-melanoma CD8 T-cell effectors','target patient 1074, age 26, female; effector donor(s) unavailable','one target line; effector sample count unavailable',U,'MP_C001','B2M replacement','Target is a nonimmune tumor culture. Human effectors are not autologous: article explicitly lacked autologous TILs for these tumors. Effector expansion IL-2 6000 U/mL for 30–70 days.')
cohort('MP_C003','MP_S001','human metastatic tumors; mouse spleen','human melanoma or H82 target; BALB/c vaccinia-specific CD8 T-cell recipient','human lines plus female BALB/c mice age 6–8 weeks',notes='Cross-species assay uses mouse H-2Kd expressed in human targets and murine CTLs. Not human-recipient evidence.')['species']='Homo sapiens target; Mus musculus recipient'
cohort('MP_C004','MP_S002','peripheral blood origin','TND-3 EBV-transformed B-cell target','patient 2; Japanese patient; controls include hemizygous sibling','one patient-derived target line',1,intervention='TAP1 versus TAP2 recombinant vaccinia',notes='TND-3 is immortalized, not a primary B-cell preparation. Separate Italian patient-derived fibroblast BRE experiment is not transported to B cells.')
cohort('MP_C005','MP_S003','peripheral blood','HA-L EBV-transformed B-cell target; autologous expanded CD8 alpha-beta T cells','patient 2, 30-year-old asymptomatic woman; HA-T heterozygous parent','one usable patient EBV-B line and autologous CTL preparation',1,intervention='TAP2 complementation or uncomplemented EBV-target recognition',notes='The second patient-derived EBV-B line had excessive dead cells and was not used. Patient 2 supplies functional assays. HA-T is a family control, not an independent unrelated cohort.')
cohort('MP_C006','MP_S003','peripheral blood','primary PBMCs','two siblings (46-year-old man; 30-year-old woman) and parents','two patient PBMC preparations plus family controls',2,notes='PBMC staining is distinct from EBV-B target/CTL assay; source labels HAL/HA-L denote patient 2 in the Methods. Geographic affiliation does not establish ancestry.')
cohort('MP_C007','MP_S003','COS culture; human peripheral blood','transfected COS cells plus patient-2 human CTL clone','COS cells (nonhuman primate); human CTL from MP_C005',parent='MP_C005',notes='Antigen assignment experiment is not a human source-cell assay. Methods and Fig5 legend differ on CTL coculture and TNF assay timing; retain discrepancy, no harmonization.')['species']='nonhuman primate COS target (species unavailable in article); Homo sapiens recipient'
cohort('MP_C008','MP_S004','blood buffy coat origin','primary-human-monocyte-derived cultured dendritic cells','blood-transfusion buffy coat donors','Fig1 flow two independent experiments; RNA three; no donor counts',U,intervention='six-day GM-CSF/IL-4 differentiation; LPS 10 ng/mL maturation',notes='Donor overlap between RNA, immunoblot, surface, and chromatin experiments unavailable. Experiment counts are not donor counts. Mouse knockout/DC experiments are not imported.')
cohort('MP_C009','MP_S005','melanoma cell culture','WM793 and WM278 melanoma clones; mouse T-hybridoma expressing human Vα3S1/Vβ13S1 TCR','two human cell lines; two ERAP1 knockout clones per line; one reused TCR specificity','technical replicates nested in two or three independent experiments',U,intervention='ERAP1 knockout and Hap2/Hap10 reconstitution',notes='Cell lines are melanoma, not primary melanocytes or primary immune cells. TCR originates from one lesional psoriatic clone; receptor reused in MP_S007. DT-9 cross-reactivity explicitly recorded in assertions.',accession='SAMN03471796 (article links WM278/WM793 cell-line context)')['species']='Homo sapiens target; Mus musculus recipient'
cohort('MP_C010','MP_S005','cell-free biochemical reaction','purified recombinant human ERAP1 and synthetic ADAMTSL5 peptide','no cellular cohort','three independent biochemical experiments',U,intervention='Hap2 versus Hap10 digestion of 11mer',notes='Not donor replication; no transfer of these digests to the cellular TCR assay demonstrated.')
cohort('MP_C011','MP_S005','HEK293T culture','engineered HEK293T target; mouse T-hybridoma recipient','cell-line clones; no new patient TCR','two independent experiments with technical replicates',U,intervention='ERAP1 knockout/reconstitution and HLA-C*06:02 plus precursor peptide plasmids',notes='HEK293T is not an immune APC. Heterologous reporter recipient remains mouse.')['species']='Homo sapiens target; Mus musculus recipient'
cohort('MP_C012','MP_S006','MEL9 tumor and peripheral blood; Jurkat culture','BCL6/BCL-xL/CD40L-immortalized autologous human B cells; engineered human Jurkat reporter','MEL9 patient supplies B cells and tumor TCR repertoire; Jurkat host distinct','two biological replicates per supplemental HLA-restriction test',1,intervention='B2M Cas9 RNP knockout or IVA12 HLA-II block',notes='Autologous refers to antigen-library B cells relative to patient TCR origin, not Jurkat host. TCR alpha/beta constant regions are mouse-derived. No primary effector killing or post-KO surface-HLA measurement extracted.')
cohort('MP_C013','MP_S007','peripheral blood','primary PBMCs, B-cell-depleted and autologous-B-cell-reconstituted PBMCs','HLA-C*06:02-positive psoriasis patients and healthy controls','seven patients and seven healthy controls; triplicate wells',14,intervention='B-cell depletion/add-back; W6/32 blockade in separate assay',notes='Fig3A–C linked paired subject measurements. Exact overlap of Fig3D antibody assays with A–C unavailable without supplemental subject table.')
cohort('MP_C014','MP_S007','peripheral blood','CFSE-labeled primary PBMC subsets','17 psoriasis patients and 9 healthy controls','duplicates per person',26,notes='Fig3E CFSE assay. Individual overlap with MP_C013 is unavailable; do not infer B-cell depletion effect specifically on CD8 cells from this separate assay.')
cohort('MP_C015','MP_S007','tonsils','primary tonsillar B cells plus reused mouse TCR hybridoma','three HLA-C*06:02-positive patients with streptococcal-tonsillopharyngitis-associated psoriasis; subsets from two','three tonsils; fractionation two',3,intervention='B-cell fractionation; IFNG; W6/32',notes='Human B-cell source; mouse reporter recipient. Tonsils reused from cited earlier study [23]; no independent cohort claim. Single psoriatic TCR lineage reused from MP_S005 and earlier discovery study.')['species']='Homo sapiens source; Mus musculus recipient'
cohort('MP_C016','MP_S007','EBV-B-cell culture','four HLA-C*06:02-homozygous EBV-transformed B-cell lines','GM20771, GM11930, HG00131, HG00142','four cultures expanded to 1e9 cells each',U,intervention='W6/32 pan-HLA ligand purification and mass spectrometry',notes='Nonprimary immune lines. Methods later list HG00313 instead of HG00131; unresolved. HLA-C assignments computational, not allele-specific immunoprecipitation. Raw FDR-file naming inconsistent.')
cohort('MP_C017','MP_S002;MP_S003','blood/fibroblast culture','ST-EMO EBV-B and STF-1 fibroblast controls','previous TAP2-deficient patient EMO',notes='ST-EMO is reused across MP_S002 and MP_S003 and earlier de la Salle studies, and is not independent replication. Same named control identity inspected in both Methods.')['related_publications']=['MP_S002','MP_S003','de la Salle et al., cited earlier TAP2-deficiency studies']

FIELDS='assertion_id subject subject_type predicate object object_type subject_layer object_layer measurement evidence_tier direction source_id cohort_id source_locator evidence_summary species ancestry age sex tissue disease disease_severity treatment_status cell_type cell_state developmental_state stimulation dose duration assay genomic_background time_point effect_size effect_unit uncertainty causal_directness limitations contradiction_group candidate_path qc_status qualitative_confidence'.split()
assertions=[]
def add(num,sid,cid,subject,obj,layers,measurement,direction,loc,summary,**kw):
    c=next(x for x in cohorts if x['cohort_id']==cid)
    a={k:U for k in FIELDS}; a.update(assertion_id=f'MP_A{num:03}',subject=subject,subject_type='experimental_intervention',predicate='changes_measured_readout',object=obj,object_type='measured_readout',subject_layer=layers[0],object_layer=layers[1],measurement=measurement,evidence_tier='perturbational',direction=direction,source_id=sid,cohort_id=cid,source_locator=loc,evidence_summary=summary,species=c['species'],tissue=c['tissue'],cell_type=c['cell_type'],qc_status='extracted_pending_review',qualitative_confidence='moderate',causal_directness='Perturbation with measured endpoint; limited to the specified preparation.',limitations='No primary-cell or cross-context transport assumed.',candidate_path=U)
    a.update(kw);a['source_cell_taxon']=a.pop('source_taxon','Homo sapiens');a['recipient_cell_taxon']=a.pop('recipient_taxon','not_applicable_no_recipient_assay');a['supporting_snapshot_paths']=[next(s['companion_snapshot_path'] for s in sources if s['source_id']==sid)];assertions.append(a);return a

add(1,'MP_S001','MP_C002','B2M-expressing vaccinia','intracellular immunoreactive B2M in 1074mel','GP','protein_abundance','increase','Fig3; Methods Western Blot Analyses; parsed text lines 116–117,230–233','B2M vector restores immunoreactive B2M in 1074mel relative to control vaccinia.',age=26,sex='female (target)',genomic_background='HLA-A2.1-positive; functional B2M deficient',assay='HB159 immunoblot',candidate_path='MP_M001')
add(2,'MP_S001','MP_C001','B2M-expressing vaccinia','surface folded HLA class I','GP','protein_abundance','increase','Fig1; Methods Cytofluorography; Results after Fig3','B2M replacement raises W6/32-reactive surface class I on all five deficient melanoma lines.',assay='W6/32 flow cytometry',limitations='Pan-class-I conformational abundance; no peptide identity or epitope-specific occupancy measurement. Fig1 and Fig5 aliquot linkage unavailable.',candidate_path='MP_M001')
add(3,'MP_S001','MP_C002','B2M-expressing vaccinia','1074mel lysis by HLA-A2.1-restricted human antimelanoma CD8 T cells','GF','cellular_phenotype','increase','Fig5; Methods Cytotoxic T Lymphocytes and Microcytotoxicity Assays; Results preceding Fig5','B2M replacement restores lysis of 1074mel by HLA-compatible human antimelanoma CD8 effectors.',age=26,sex='female (target)',recipient_taxon='Homo sapiens',assay='6-hour 51Cr release',dose='10 plaque-forming units per target cell; Fig5 E:T titration',duration='vaccinia 60–90 min, 51Cr loading 1 h, then coculture 6 h',genomic_background='1074mel HLA-A2.1 positive',limitations='Human effectors are allogeneic, not autologous; exact antigen/peptide and effector donor number unavailable. Specific HLA intermediate was not separately blocked in this assay.',candidate_path='MP_M001')
add(4,'MP_S001','MP_C001','B2M-expressing vaccinia in HLA-A2.1-negative 1259mel','lysis by HLA-A2.1-restricted human antimelanoma CD8 T cells','GF','cellular_phenotype','null','Fig5 caption and visually inspected Fig5 image; Methods Microcytotoxicity Assays','The B2M-reconstituted HLA-mismatched 1259mel control remains near background lysis in Fig5.',recipient_taxon='Homo sapiens',assay='6-hour 51Cr release; qualitative graph inspection',genomic_background='1259mel HLA-A2.1 negative',uncertainty='No formal equivalence test; graph not digitized.',limitations='Context-specific negative control, not universal absence of all T-cell recognition.',contradiction_group='MP_X001',candidate_path='MP_M001')
add(5,'MP_S001','MP_C003','B2M replacement plus mouse H-2Kd vaccinia in human targets','vaccinia-specific murine CD8-mediated target lysis','GF','cellular_phenotype','mixed','Fig4; Methods Cytotoxic T Lymphocytes and Microcytotoxicity Assays','B2M restoration enables viral-antigen recognition of five melanoma lines, but does not rescue the H82 small-cell-lung-cancer control.',recipient_taxon='Mus musculus',assay='6-hour 51Cr release',limitations='Mouse MHC restriction and mouse recipient prevent interpretation as a human T-cell pathway. H82 has another processing defect.',candidate_path='MP_M001_mouse_contrast')
add(6,'MP_S002','MP_C004','TAP1-expressing vaccinia','surface HLA class I on TND-3','GP','protein_abundance','increase','Fig2b; Methods Cell lines and recombinant vaccinia viruses; Results TAP1 complementation','TAP1 complementation restores W6/32 staining on a fraction of TAP1-deficient TND-3 EBV-B cells.',duration='overnight infection',assay='W6/32 flow cytometry',effect_size=40,effect_unit='percent of EBV-B cells reported with restored surface expression',limitations='Infection efficiency limits restoration fraction; direct T-cell function not measured in this experiment.',candidate_path='MP_M002')
add(7,'MP_S002','MP_C004','TAP2-expressing vaccinia','surface HLA class I on TAP1-deficient TND-3','GP','protein_abundance','null','Fig2b; Results TAP1/TAP2 complementation','TAP2-vector control does not restore TND-3 class I staining.',duration='overnight infection',assay='W6/32 flow cytometry',limitations='Gene-specific complementation control; no downstream functional inference.',contradiction_group='MP_X002',candidate_path='MP_M002')
add(8,'MP_S003','MP_C005','TAP2 intron IX splice-acceptor G>A (article numbering)','TAP2 cDNA lacking G at coding nucleotide 1635','GT','splicing','association','Fig3; Methods Mutation analysis; Results mutation characterization','Patient genomic and cDNA sequencing links the splice-site substitution to a one-base-shifted transcript.',subject_type='genomic_variant',evidence_tier='observational',genomic_background='Homozygous TAP2 intron IX splice-acceptor change; modern genome coordinate unavailable',assay='genomic PCR and RT-PCR sequencing',causal_directness='Patient genotype/cDNA co-observation; gene complementation elsewhere supports TAP2 defect, not precise nucleotide editing.',limitations='No isolated allele-editing experiment; truncated TAP2 protein is predicted, not a measured protein output.',candidate_path='MP_M003')
add(9,'MP_S003','MP_C005','TAP2-expressing vaccinia','surface HLA class I on HA-L','GP','protein_abundance','increase','Fig2a; Methods Complementation assay; Results mutation section','TAP2, but not TAP1, complementation restores surface class I toward TAP-sufficient levels.',assay='W6/32 flow cytometry',genomic_background='HA-L TAP2 deficient',limitations='No CTL comparison after complementation; rescue is a surface-protein result.',candidate_path='MP_M003')
add(10,'MP_S003','MP_C006','TAP2-deficient patient-2 PBMCs','surface HLA class I versus heterozygous-parent PBMCs','GP','protein_abundance','decrease','Fig1a; Methods Cytometry; Results HLA class I phenotype','Patient-2 PBMC class I staining is lower than the parent control.',subject_type='genetic_context',evidence_tier='observational',age=30,sex='female',assay='W6/32 and B1G6 flow cytometry',effect_size=10,effect_unit='fold lower staining, source reported PBMC comparison',limitations='Family comparison; primary mixed PBMCs are distinct from transformed B-cell functional targets.',candidate_path='MP_M003')
add(11,'MP_S003','MP_C005','uncomplemented autologous TAP2-deficient HA-L EBV-B targets','lysis by patient-2 expanded CD8 alpha-beta T cells','CF','cellular_phenotype','increase','Fig5a; Methods Anti-EBV T-cell responses; Results Anti-EBV T-cell response','Patient-2 CD8 effectors lyse autologous HA-L and compatible normal EBV-B targets despite TAP2 deficiency; mismatched/Daudi controls are not lysed.',subject_type='antigen_presenting_cell_context',recipient_taxon='Homo sapiens',assay='chromium-release cytotoxicity',age=30,sex='female',genomic_background='HA-L HLA-A*03011/B*07021/Cw*0702; TAP2 deficient',limitations='One expanded patient CTL population; no direct ligand measurement and no restoration-versus-loss CTL comparison. Does not prove general antiviral protection.',contradiction_group='MP_X003',candidate_path='MP_M003')
add(12,'MP_S003','MP_C007','HLA-B*0702 plus EBV BMRF1 expression in COS cells','TNF-sensitive WEHI164 cytotoxic bioactivity of patient-2 CTL supernatant','GF','cellular_phenotype','increase','Fig5b; Methods Anti-EBV T-cell responses','Combined BMRF1 and HLA-B*0702 expression stimulates the patient CTL clone; single constructs and irrelevant BZLF1 controls do not.',source_taxon='nonhuman primate COS host; exact taxon unavailable in inspected article',recipient_taxon='Homo sapiens',assay='TNF-sensitive WEHI164 cytotoxicity bioassay of supernatant',duration='Methods: COS transfection 48 h, then CTL 6 h; Fig5b legend differs (48 h/18 h); unresolved',limitations='Antigen assignment is in a nonhuman target-cell host. Bioassay reports TNF activity rather than immunoassay-quantified specific protein. Do not transport target context to primary human B cells.',candidate_path='MP_M003_antigen_assignment')
add(13,'MP_S004','MP_C008','LPS maturation','CIITA type-I/type-III RNA','PT','RNA_abundance','decrease','Fig3B–E; Methods DCs, RPA, Real Time PCR','LPS rapidly lowers CIITA RNA in human monocyte-derived DCs.',dose='10 ng/mL',duration='1–24 h; early plateau about 3–5 h',assay='RPA and quantitative RT-PCR',effect_size='80–90% decrease by 3 h',effect_unit='source-reported relative RNA',limitations='RNA abundance is not protein. No donor count or donor-level pairing across modalities reported.',candidate_path='MP_M004')
add(14,'MP_S004','MP_C008','LPS maturation','CIITA protein isoforms','PP','protein_abundance','decrease','Fig2C; Methods Immunoprecipitation and Immunoblotting','CIITA protein falls after maturation, with residual protein dominated by the 121-kDa isoform.',dose='10 ng/mL',duration='24 h maturation protocol',assay='anti-CIITA-C immunoprecipitation; anti-CIITA-N immunoblot',effect_size='eightfold decrease; residual about 95% 121-kDa isoform',effect_unit='source-reported protein comparison',limitations='Relative RNA-to-isoform translation efficiencies and protein stability unavailable; no direct transcript-to-protein quantitative link.',candidate_path='MP_M004')
add(15,'MP_S004','MP_C008','LPS maturation','HLA-DRA RNA','PT','RNA_abundance','mixed','Fig1C–D; Methods DCs and Real Time PCR','DRA RNA increases transiently at 3 h, then declines at 24–48 h.',dose='10 ng/mL',duration='3,24,48 h',assay='RPA and quantitative RT-PCR',effect_size='about 140%,35%,23% of baseline at 3,24,48 h',effect_unit='source-reported relative RNA abundance',candidate_path='MP_M004')
add(16,'MP_S004','MP_C008','LPS maturation','cell-surface HLA-DR','PP','protein_abundance','increase','Fig1A–B; Methods DCs and Cytofluorometry','Surface HLA-DR increases at 24 h while DRA RNA is lower in the same experimental preparation type.',dose='10 ng/mL',duration='24 h',assay='G46-6 HLA-DR flow cytometry',limitations='Separate modality experiments; exact donor overlap unavailable. No antigen-specific CD4 function measured here.',contradiction_group='MP_X004',candidate_path='MP_M004')
add(17,'MP_S004','MP_C008','trichostatin A during LPS maturation','CIITA RNA','PT','RNA_abundance','increase','Fig8A; Methods DCs; Results The Entire Regulatory Region...','TSA attenuates LPS-induced CIITA RNA downregulation.',dose='TSA 100 ng/mL with LPS 10 ng/mL',duration='24 h',assay='quantitative RT-PCR',limitations='Broad deacetylase inhibitor; not CIITA-locus-specific. No surface/function endpoint after TSA extracted.',candidate_path='MP_M004')
add(18,'MP_S005','MP_C009','ERAP1 knockout','DT-9-reactive surface HLA-C-enriched signal','GP','protein_abundance','decrease','Fig1A–J; Methods Evaluation of HLA expression; Results ERAP1 controls cell surface-expression','ERAP1 knockout lowers surface DT-9 signal in WM793/WM278 while total HLA-C immunoblot signal remains similar.',assay='DT-9/W6-32 flow; total HLA-C immunoblot',effect_size='greater than 50% reduction in DT-9 surface staining',effect_unit='source-reported relative surface staining',limitations='DT-9 cross-reacts with some HLA-A/B alleles and HLA-E; source checked HLA-E and used WM278 as a specificity contrast. Surface abundance is not peptide-specific occupancy.',candidate_path='MP_M005')
add(19,'MP_S005','MP_C009','ERAP1 knockout','activation of human-TCR-expressing mouse hybridoma by melanoma targets','GF','cellular_phenotype','decrease','Fig3A–B; Methods reporter stimulation','ERAP1 knockout reduces sGFP reporter activation by WM793 and WM278.',recipient_taxon='Mus musculus',assay='NFAT-sGFP positive mouse hybridoma fraction by flow',dose='WM278 IFNG 1 ng/mL; WM793 no IFNG requirement stated',duration='target preparation 24 h; coculture 24 h',limitations='Mouse reporter with human TCR, not primary human CD8 function; ADAMTSL5 RNA/protein remained comparable in Fig3E–G.',candidate_path='MP_M005')
add(20,'MP_S005','MP_C009','ERAP1 Hap2 versus Hap10 reconstitution of ERAP1-null WM793','activation of human-TCR-expressing mouse hybridoma','GF','cellular_phenotype','increase','Fig2A and Fig3C–D; Methods Plasmid-based transfection','Hap2 restores reporter stimulation more strongly than Hap10 at comparable ERAP1 immunoblot expression.',recipient_taxon='Mus musculus',assay='NFAT-sGFP positive hybridoma fraction',dose='100 ng reconstitution plasmid',duration='24 h transfection, then 24 h coculture',limitations='Two engineered WM793 clones; expression rescue supports an ERAP1-dependent reporter mechanism but not clinical penetrance or human effector activity.',candidate_path='MP_M005')
add(21,'MP_S005','MP_C010','purified human ERAP1 Hap2 versus Hap10','ADAMTSL5 11mer trimming products','PP','protein_activity','increase','Fig5A–C; Methods In vitro peptide digestion assays','Hap2 trims the synthetic 11mer faster than Hap10 in cell-free reactions.',source_taxon='not_applicable_cell_free_human_protein',assay='reversed-phase HPLC',dose='20 nM peptide; 2 micrograms ERAP1 as reported',duration='37°C, up to 2 h',effect_size='at 1 h: Hap2 89% substrate trimmed; Hap10 69% substrate remained',effect_unit='source-reported substrate fraction',limitations='HPLC does not resolve the 9mer from 8mer sufficiently; cell-surface peptide quantity not measured and digestion mixture not transferred to reporter cultures.',candidate_path='MP_M005')
add(22,'MP_S005','MP_C011','ERAP1 knockout with ADAMTSL5 precursor-length variation','mouse TCR-hybridoma sGFP activation','GF','cellular_phenotype','mixed','Fig4A–C; Methods Plasmid-based transfection; Results Generation of the autoantigenic epitope','Longer encoded precursors lose activity after ERAP1 knockout, whereas encoded 8mer retains strong stimulation; ERAP1 reconstitution restores precursor responses.',recipient_taxon='Mus musculus',assay='NFAT-sGFP reporter flow',dose='75 ng each HLA-C, peptide and ERAP1/vector construct',duration='24 h transfection plus 24 h coculture',limitations='Encoded peptides retain uncertain N-terminal methionine processing. Hap2/Hap10 difference for 12mer was not significant. No direct surface peptide measurement.',contradiction_group='MP_X005',candidate_path='MP_M005')
add(23,'MP_S006','MP_C012','B2M knockout in matched-TMG MEL9 B cells','MEL9 TCR1 Jurkat CD69 activation','GF','cellular_phenotype','decrease','Supplementary Fig4i (PDF pp8–9); Methods Antigen presentation/additional engineering and T cell activation assays','B2M knockout lowers matched-antigen activation of the TCR1 reporter.',recipient_taxon='Homo sapiens (Jurkat host; engineered TCR has murine constant domains)',assay='CD69 flow cytometry; two biological replicates',dose='three B2M gRNAs as RNPs; IL21 50 ng/mL during B-cell expansion',duration='20–24 h coculture at 1:1 reporter/APC',limitations='Immortalized B-cell and Jurkat hosts. No surface-class-I validation or knockout rescue extracted; no cytotoxicity.',candidate_path='MP_M006')
add(24,'MP_S006','MP_C012','B2M knockout in matched-TMG MEL9 B cells','MEL9 TCR22 Jurkat CD69 activation','GF','cellular_phenotype','null','Supplementary Fig4i (PDF pp8–9); main Results HLA restriction','TCR22 reporter activation is retained after B2M knockout.',recipient_taxon='Homo sapiens (Jurkat host; engineered TCR has murine constant domains)',assay='CD69 flow cytometry; qualitative figure comparison',duration='20–24 h coculture at 1:1 reporter/APC',uncertainty='No equivalence statistic; retained qualitative response.',limitations='TCR22 is HLA-II restricted; retention is specificity-dependent, not evidence against class-I dependence of TCR1.',contradiction_group='MP_X006',candidate_path='MP_M006')
add(25,'MP_S006','MP_C012','IVA12 HLA-class-II blocking antibody','MEL9 TCR22 Jurkat CD69 activation','PF','cellular_phenotype','decrease','Supplementary Fig4i (PDF pp8–9); Methods T cell activation and TCR characterization assays','IVA12 inhibits the TCR22 response that persists under B2M knockout.',recipient_taxon='Homo sapiens (Jurkat host; engineered TCR has murine constant domains)',dose='120 micrograms/mL',duration='20–24 h coculture',assay='CD69 flow cytometry',limitations='Antibody blockade supports class-II restriction; precise restricting allele and epitope density not extracted.',candidate_path='MP_M006')
add(26,'MP_S007','MP_C013','B-cell depletion from patient PBMCs','bulk autologous PBMC proliferation','CF','cellular_phenotype','decrease','Fig3B; Methods 2.7; Results 3.4','Removing B cells reduces spontaneous DNA incorporation in psoriasis PBMC cultures.',assay='3H-thymidine incorporation',duration='pulse day4 overnight; harvest day5',limitations='Bulk PBMC proliferation, not a B-depletion-specific CD8 readout and not antigen-specific T-cell activation.',candidate_path='MP_M007')
add(27,'MP_S007','MP_C013','autologous B-cell re-addition to B-depleted PBMCs','bulk autologous PBMC proliferation','CF','cellular_phenotype','increase','Fig3B; Methods 2.7; Results 3.4','Autologous B-cell add-back restores the reduced PBMC DNA-incorporation response.',assay='3H-thymidine incorporation',duration='pulse day4 overnight; harvest day5',limitations='Supports B-cell contribution to bulk spontaneous proliferation; effector identity and peptide specificity not determined by this assay.',candidate_path='MP_M007')
add(28,'MP_S007','MP_C013','W6/32 pan-HLA-class-I blockade','bulk psoriasis PBMC proliferation','PF','cellular_phenotype','decrease','Fig3D; Methods 2.7; Results 3.4','Pan-class-I blockade lowers bulk PBMC BrdU incorporation relative to isotype control.',assay='BrdU incorporation assay',duration='4-hour BrdU pulse on day4',dose=U,limitations='W6/32 acts on all class-I-bearing cells; B-cell-specific HLA dependence and exact donor overlap with depletion/add-back assays unavailable.',candidate_path='MP_M007')
add(29,'MP_S007','MP_C014','psoriasis versus healthy donor PBMC context','CD8-positive-cell proliferation','CF','cellular_phenotype','increase','Fig3E; Methods 2.7; Results 3.4','CD8 CFSE dilution is greater in psoriasis samples; CD4, CD3 and B-cell comparisons are not significant.',subject_type='disease_context',evidence_tier='observational',assay='CFSE dilution within phenotyped PBMC subsets',duration='5 days',limitations='Distinct sample counts from depletion/add-back experiment; no defined antigen or intervention-specific CD8 endpoint.',candidate_path='MP_M007')
add(30,'MP_S007','MP_C015','W6/32 blockade of primary tonsillar B-cell/hybridoma coculture','Vα3S1/Vβ13S1 mouse T-hybridoma activation','PF','cellular_phenotype','decrease','Fig1C; Methods 2.5–2.6; Results 3.1','Pan-HLA-I antibody inhibits reporter stimulation by primary psoriatic tonsillar B cells.',recipient_taxon='Mus musculus (human psoriatic TCR)',assay='sGFP reporter flow',dose='W6/32 10 micrograms/mL; 2e4 source cells and 1e4 reporter cells/well',duration='24 h coculture',limitations='Primary human source but mouse recipient; one repeatedly used TCR specificity. Does not identify the antigen of the human autologous proliferation assay.',candidate_path='MP_M008')
add(31,'MP_S007','MP_C016','four HLA-C*06:02-homozygous EBV-B ligand preparations','detected ADAMTSL5 autoantigen peptide','CP','protein_abundance','null','Methods 2.9–2.12; Results 3.6','The melanocyte ADAMTSL5 peptide was not detected in these four B-cell-line immunopeptidomes.',subject_type='biological_preparation',evidence_tier='observational',assay='W6/32 pan-HLA purification; LC-MS/MS; computational HLA assignment',limitations='Nondetection is not absence. Pan-HLA isolation does not directly establish allele-specific binding; cell-line identifier and FDR-file discrepancies unresolved.',contradiction_group='MP_X007',candidate_path='MP_M008')

for a in assertions:
    if a['source_id']=='MP_S001' and a['assertion_id'] in ['MP_A003','MP_A004']:
        a['supporting_snapshot_paths'].append(BASE+'snapshots/MP_Restifo1996_fig5.jpg')
    if a['source_id']=='MP_S006':a['supporting_snapshot_paths'] += sources[5]['additional_snapshots'][:3]
    a['tested_hypothesis']='The stated intervention/context changes the stated measured endpoint in the stated preparation.'
    a['evidence_relation']='context_specific_null' if a['direction']=='null' else 'supports_narrow_observation'

qs=[
('MP_BATCH01','Restifo 1996 loss functional beta2 microglobulin metastatic melanoma immunotherapy gene transfer T cells',['MP_S001'],U),
('MP_BATCH01','TAP2 deficient patient lymphoblastoid antigen presentation cytotoxic T lymphocyte gene transfection rescue',['MP_S003'],U),
('MP_BATCH01','ERAP1 polymorphism human antigen specific T cells rescue immunopeptidome primary study',[],U),
('MP_BATCH02','CIITA human monocyte dendritic cell knockdown antigen specific T cell HLA DR primary',['MP_S004'],'MP_search_batch2.json'),
('MP_BATCH02','ERAP1 psoriasis melanocyte ADAMTSL5 autoantigen T cell recognition ERAP1 2020',['MP_S005'],'MP_search_batch2.json'),
('MP_BATCH02','TAP deficient EBV BMRF1 B0702 asymptomatic deficiency antigen processing full text',['MP_S003'],'MP_search_batch2.json'),
('MP_BATCH02','B2M loss rescue autologous T cells melanoma Sade Feldman 2017 resistance',[],'MP_search_batch2.json'),
('MP_BATCH03','"B2M" "T-cell" "Restifo" "correction"',['MP_S006'],'MP_search_batch3.json'),
('MP_BATCH03','"Loss of Functional" "Beta2-Microglobulin" "retraction"',[],'MP_search_batch3.json'),
('MP_BATCH03','"Asymptomatic deficiency" "TAP" "Villard"',['MP_S002'],'MP_search_batch3.json'),
('MP_BATCH03','"B Cells Can Trigger" "Melanocytes" psoriasis 2025',['MP_S007'],'MP_search_batch3.json'),
('MP_BATCH04','"Maturation of Dendritic Cells" "Rapid Transcriptional" CIITA JEM',['MP_S004'],'MP_search_batch4.json'),
('MP_BATCH04','"Asymptomatic deficiency in the peptide transporter" de la Salle 2002 full',['MP_S003'],'MP_search_batch4.json'),
('MP_BATCH04','"Loss of Functional Beta2-Microglobulin" Restifo 1996 pdf',['MP_S001'],'MP_search_batch4.json'),
]
for i,s in enumerate(sources):
    qs.append(('MP_CORR01' if i<4 else 'MP_CORR02',f'"{s["doi"]}" (correction OR erratum OR retraction)',[s['source_id']], 'MP_correction_search1.json' if i<4 else 'MP_correction_search2.json'))
searches=[]
for i,(batch,q,ids,snap) in enumerate(qs,1):
    searches.append(dict(search_id=f'MP_Q{i:03}',batch_id=batch,lane='antigen processing/presentation',query=q,database='web ranked search',searched_at='2026-09-13',result_source_ids=ids,screening_notes='Bounded ranked retrieval, not exhaustive. Multiquery tool response combines results; listed source IDs are batch-level relevant candidates and do not imply known per-query rank or coverage.',snapshot_path=BASE+'snapshots/'+snap if snap!=U else U))

gaps=[
 dict(gap_id='MP_G001',description='Surface HLA abundance does not quantify a specific peptide-HLA complex; no selective surface-HLA mediation test between B2M replacement and human CTL lysis in S001.'),
 dict(gap_id='MP_G002',description='TAP2 sequence-to-aberrant RNA observation lacks measured mutant TAP2 protein. HLA rescue and residual CTL experiments use different intervention states.'),
 dict(gap_id='MP_G003',description='CIITA RNA, protein isoforms and surface HLA-DR measured in separate experiments with donor overlap unavailable; no antigen-specific human CD4 endpoint.'),
 dict(gap_id='MP_G004',description='ERAP1 biochemical digestion does not determine exact 8mer versus 9mer surface product or direct transfer into the reporter assay. Mouse recipient assays cannot establish human primary-CD8 function.'),
 dict(gap_id='MP_G005',description='He2025 depletion/add-back bulk proliferation and CD8 CFSE assays have different cohort sizes with unresolved individual overlap. Antigen specificity of the primary-human proliferation endpoint is unmeasured.'),
 dict(gap_id='MP_G006',description='He2025 Methods HG00131/HG00313 and Results 1%-FDR versus filename FDR_0.1 are unresolved. W6/32 pan-HLA immunoprecipitation plus prediction must not be labeled direct HLA-C*06:02 ligand isolation.'),
 dict(gap_id='MP_G007',description='No independent or human review yet. Ranked web retrieval does not provide exhaustive recall; corrections/retractions may be missed. Modern effectors/autologous B2M rescue and additional primary human APC variant studies remain follow-up priorities.'),
]
pack=dict(sources=sources,cohorts=cohorts,assertions=assertions,searches=searches,gaps=gaps,synthesis='Seven primary articles broaden immune evidence to antigen processing, presentation, and recognition. The strongest human-effector restoration result is B2M replacement in HLA-compatible melanoma. Primary human DCs demonstrate opposing RNA and surface-HLA trends, and patient TAP2-deficient EBV-B targets retain selected autologous CTL recognition. ERAP1 and recent B-cell experiments add perturbational, peptide, and reporter evidence with explicit preparation/species limits. These are pending-review assertions and connection proposals, not a frozen pathway or a prior model.')
(ROOT/'pack.json').write_text(json.dumps(pack,ensure_ascii=False,indent=2)+'\n')

def write(name,data): (ROOT/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
write('run.json',dict(run_id='MP_RUN_20260913_01',agent_role='evidence_extractor_not_independent_reviewer',timestamp_start=START,timestamp_end=NOW(),timezone='UTC (runtime timestamps); user timezone America/New_York',LLM_provider='OpenAI',LLM_model=U,model_snapshot_if_available=U,reasoning_mode=U,protocol_version='0.3.0 mechanism-candidate phase',agent_prompt_version='parent antigen lane task; EXTRACTION_CONTRACT_0.3.md plus original extraction contract',instruction_bundle_hash=U,source_versions={s['source_id']:s['version'] for s in sources},retrieval_queries=[s['search_id'] for s in searches],retrieval_dates=['2026-09-13'],source_hashes='computed centrally by coordinator',code_commit=U,environment_hash=U,output_hash=U,critic_run_ids=[],independent_review='pending_user_trigger',human_review='pending',human_edits=U,skills_read=['life-science-research:research-router-skill','life-science-research:ncbi-entrez-skill (no Entrez calls used)','pdf:pdf'],access_failures=['Initial PMC web opens returned browser challenges','Europe PMC web route returned403/unsafe errors','Initial sandbox Python URL retrieval failed DNS; authorized direct primary-source retrieval succeeded','fitz not installed; bundled Poppler used successfully'],actions_excluded=['independent review','numeric priors','production edits','freeze'],scope='Broad immune antigen-processing/presentation mechanisms; no cytokine priority set; human and nonhuman preparations explicitly separated.'))
print(json.dumps({'sources':len(sources),'cohorts':len(cohorts),'assertions':len(assertions),'queries':len(searches)}))
