import json, hashlib, re
from pathlib import Path

B=Path('research/cytokine_expansion')
U='unavailable'
DATE='2026-09-13'
sources=[]; cohorts=[]; assertions=[]
def source(n,title,pmc,year=U,doi=U,pmid=U,snapshot='search01.json',access='primary_source_search_excerpt',notes='Full article methods not independently inspected; no full-text review claimed.'):
    sources.append(dict(source_id=f'XCI-S{n:02}',title=title,authors=U,year=year,url=f'https://pmc.ncbi.nlm.nih.gov/articles/{pmc}/',doi=doi,pmid=pmid,source_type='primary_study',version=pmc+' repository record; version details unavailable',retrieved_at=DATE,access_level=access,snapshot_path=str(B/'snapshots'/snapshot),species='Homo sapiens',notes=notes))
def cohort(n,src,**kw):
    d={k:U for k in 'dataset_id accession participants ancestry tissue cell_type disease intervention sample_count donor_count parent_cohort notes'.split()}
    d.update(cohort_id=f'XCI-CO{n:02}',study_id=f'XCI-S{src:02}',dataset_id=f'XCI-D{n:02}',species='Homo sapiens',related_publications=[f'XCI-S{src:02}'],independence_status='unresolved');d.update(kw);cohorts.append(d)
fields='assertion_id subject subject_type predicate object object_type subject_layer object_layer measurement evidence_tier direction source_id cohort_id source_locator evidence_summary species ancestry age sex tissue disease disease_severity treatment_status cell_type cell_state developmental_state stimulation dose duration assay genomic_background time_point effect_size effect_unit uncertainty causal_directness limitations contradiction_group candidate_path qc_status qualitative_confidence'.split()
def a(n,src,co,sub,obj,pred,measurement,direction,summary,locator,hypothesis,**kw):
    d={k:U for k in fields}
    d.update(assertion_id=f'XCI-A{n:02}',source_id=f'XCI-S{src:02}',cohort_id=f'XCI-CO{co:02}',subject=sub,subject_type='protein',object=obj,object_type='protein',subject_layer='P',object_layer='P',predicate=pred,measurement=measurement,direction=direction,evidence_summary=summary,source_locator=locator,species='Homo sapiens',evidence_tier='P2',qc_status='needs_full_text',qualitative_confidence='low')
    d.update(kw)
    null=direction=='null'
    d['scoring_annotation']={'tested_hypothesis':hypothesis,'evidence_relation':'inconclusive' if null else 'supports','null_adequacy':'No equivalence bound, confidence interval or justified absence threshold available; not adequate to support relationship absence.' if null else 'not_applicable','rationale':('Qualitative nondetection is retained as an observation, not evidence of an absent relationship.' if null else 'The recorded contrast supports this narrow hypothesis in the assayed context only.')+' Pending independent review; needs_full_text records remain ineligible for default prior scoring.'}
    assertions.append(d)

source(1,'Cross-Talk between ICAM-1 and Granulocyte-Macrophage Colony-Stimulating Factor Receptor Signaling Modulates Eosinophil Survival and Activation','PMC4465562',2008,'10.4049/jimmunol.180.6.4182','18322230','open01.json','full_text_sections_via_web_tool','Methods and Results through Figure2 retrieved. Later Figure7 survival result is available only in search01.json. No raw donor data or complete supplement reviewed.')
sources[-1]['authors']=['Konrad Pazdrak','Travis W Young','Susan Stafford','Barbara Olszewska-Pazdrak','Christof Straub','Vitaliy Starosta','Allan Brasier','Alexander Kurosky']
source(2,'An Interleukin 5 Mutant Distinguishes between Two Functional Responses in Human Eosinophils','PMC2198963')
source(3,'CD25 and protein phosphatase 2A cooperate to enhance IL-2R signaling in human regulatory T cells','PMC6581624')
source(4,'Time-Dependent Regulation of IL-2R α-Chain (CD25) Expression by TCR Signal Strength and IL-2-Induced STAT5 Signaling in Activated Human Blood T Lymphocytes','PMC5172478')
source(5,'Gene Expression Profiling of IL-17A-Treated Synovial Fibroblasts from the Human Temporomandibular Joint','PMC4709758')
source(6,'IL-1R1 signaling facilitates Munro’s microabscess formation in psoriasiform imiquimod-induced skin inflammation','PMC3656131',snapshot='search02.json',notes='Mixed human/mouse publication. Only explicitly human primary-keratinocyte experiments extracted; mouse IL1R1 knockout results not transported to human cells.')
sources[-1]['species']=['Homo sapiens','Mus musculus']
source(7,'Dermal fibroblasts are the key sensors of aseptic skin inflammation through interleukin 1 release by lesioned keratinocytes','PMC9576869',snapshot='search02.json',notes='Mixed human/mouse study. Only the explicitly human primary-keratinocyte comparator extracted. Fibroblast donor origin and receptor-blockade experiment context require full methods before further extraction.')
sources[-1]['species']=['Homo sapiens','Mus musculus']
source(8,'Human mid-gestation amniotic fluid contains interleukin-16 bioactivity','PMC2673366',notes='Source-only candidate: detailed chemotaxis Methods retrieved, but no result passage sufficient to assert an IL16 effect. Await full results; no biological edge extracted.')
cohort(1,1,participants='healthy nonallergic blood volunteers',tissue='peripheral blood',cell_type='purified eosinophil',disease='healthy; nonallergic',intervention='GM-CSF 10 ng/mL, up to 48 h; ICAM1 perturbations in distinct arms',notes='Eosinophil purity >=99%; total unique donor number not given in inspected sections. Repeated time points, cytokine outputs and inhibition arms are not independent cohorts.')
cohort(2,2,tissue='peripheral blood',cell_type='purified human eosinophil',intervention='wild-type IL5 and recombinant IL5(E12K); neutralizing TRFK-5 antibody',donor_count='Fig5A six different blood donors; Fig5B at least three experiments, unique donors unavailable',sample_count='Fig5A six independent experiments; Fig5B at least three',notes='E. coli expression refers to the mutant cytokine reagent, not the human target cells. Survival and neutralization arms share study context; overlap unresolved.')
cohort(3,3,tissue='peripheral blood',cell_type='human CD4+ T cells with CD25/Foxp3-defined subsets',intervention='IL2 stimulation for 15 min',notes='Paper also studies YT cells; only explicitly human primary CD4 T-cell results retained. Donor number unavailable in excerpt.')
cohort(4,4,tissue='peripheral blood',cell_type='quiescent primary human T lymphocyte',intervention='IL2 alone versus TCR stimulation contexts',notes='Excerpt does not supply dose, assay or time points for cell-cycle result. Keep provisional and do not pool with the separate PP2A/CD25 study.')
cohort(5,5,participants='patients with temporomandibular disorder',tissue='temporomandibular joint synovium',cell_type='synovial fibroblast',disease='temporomandibular disorder',intervention='IL17A 10 ng/mL; signaling inhibitor pretreatment',donor_count='Fig7 three patients (TMJ1-3); Fig8 donor basis unavailable',sample_count='Fig7 n=6 measurements; Fig8 n=4 measurements; do not interpret as donor counts',notes='Three donor-derived samples are explicit in Fig7; inhibitor experiments need full methods for donor and replicate identity.')
cohort(6,6,tissue='skin',cell_type='primary human keratinocyte',intervention='imiquimod; human IL1A; anti-human IL1A neutralization',notes='Human in-vitro arm only. Mouse knockout and imiquimod skin phenotypes excluded. Donor number and cell-source demographics unavailable in saved excerpt.')
cohort(7,7,tissue='skin',cell_type='primary human keratinocyte',intervention='recombinant IL1A concentration response',notes='Only explicitly human keratinocyte comparator in Fig3B retained. No inferred donor identity from fibroblast or mouse arms.')
cohort(8,8,participants='healthy adult blood donors; amniotic-fluid sample donors separately unresolved',tissue='peripheral blood; amniotic fluid',cell_type='purified CD4+CD3+ T cells',intervention='recombinant human IL16 or amniotic fluid in micro-Boyden chemotaxis assay',notes='Methods report >95% purified target cells and two-hour migration assay. Results not extracted; source/cohort only, no functional assertion.')

gm=dict(tissue='peripheral blood',cell_type='purified eosinophil',disease='healthy; nonallergic',stimulation='CSF2 (GM-CSF)',dose='10 ng/mL',assay='Western blot of total eosinophil cell lysates',causal_directness='Purified cytokine exposure with directly measured protein abundance.',uncertainty='Qualitative time-course result; numerical fold changes and donor-level uncertainty unavailable.',limitations='Total lysate protein, not surface abundance or binding availability. No direct downstream function inferred from receptor abundance.',qc_status='reviewed_extraction',qualitative_confidence='moderate')
a(1,1,1,'CSF2','ICAM1','increases_total_protein_abundance','protein_abundance','increase','GM-CSF induced ICAM1 protein during the six-to-24-hour eosinophil time course.','Results and Figure2B; open01.json source lines 209-218; cell culture Methods lines159-164','CSF2 at 10 ng/mL increases total ICAM1 protein in these human blood eosinophils over 6-24 h.',duration='6–24 h',time_point='detected by 6 h; maximal at 24 h',**gm)
a(2,1,1,'CSF2','CSF2RA','decreases_total_protein_abundance','protein_abundance','decrease','GM-CSF reduced the receptor alpha-chain protein detectable in total eosinophil lysates from three through 24 hours.','Results and Figure2B; open01.json source lines210-212','CSF2 at 10 ng/mL reduces total CSF2RA protein in these eosinophils over 3-24 h.',duration='3–24 h',time_point='3–24 h',**gm)
a(3,1,1,'ICAM1 antisense oligonucleotide','eosinophil viability','decreases_GMCSF_supported_viability','cellular_phenotype','decrease','ICAM1 suppression reduced viable eosinophils in GM-CSF-treated cultures compared with cytokine and sense-control cultures.','Figure7A and Results in search01.json; viability and inhibition Methods in open01.json lines162-164,179-182','ICAM1 antisense treatment reduces eosinophil viability at 48 h in the presence of CSF2.',subject_type='experimental_intervention',object_type='cellular_phenotype',subject_layer='T',object_layer='F',evidence_tier='perturbational',tissue='peripheral blood',cell_type='purified eosinophil',disease='healthy; nonallergic',stimulation='CSF2 with ICAM1 antisense versus sense control',dose='CSF2 10 ng/mL; antisense 50 nM',duration='48 h',time_point='48 h',assay='annexin V/7-AAD flow cytometry',causal_directness='Antisense perturbation; no direct receptor knockout.',uncertainty='Donor/replicate basis for Figure7 not recovered.',limitations='Later results available only as excerpt; antisense specificity and transfection effects require full review. Does not prove ICAM1 is the CSF2-binding receptor.')
il5=dict(tissue='peripheral blood',cell_type='purified eosinophil',duration='72 h',time_point='72 h',assay='trypan-blue exclusion',uncertainty='Full methods and disease/donor demographics not recovered.',limitations='Survival readout does not establish proliferation or degranulation. Figure5 captions are saved primary-source excerpts; full-page retrieval returned CAPTCHA.',causal_directness='Recombinant cytokine perturbation in human target cells.')
a(4,2,2,'IL5','eosinophil viability','increases','cellular_phenotype','increase','Wild-type IL5 supported human eosinophil survival over 72 hours compared with cytokine-free culture.','Figure5A caption in search01.json','Wild-type IL5 increases the percentage of viable eosinophils at 72 h in this culture system.',object_type='cellular_phenotype',object_layer='F',stimulation='wild-type IL5 concentration response',dose='concentration series; exact full range unavailable',**il5)
assertions[-1]['quantitative_result']={'value':66,'unit':'percent viable cells at maximal wild-type IL5 response','comparator':'2.7% viable cells without cytokine','uncertainty':'SEM 5.6 percentage points for stimulated and 1.7 for unstimulated','donor_sample_basis':'six independent experiments with different blood donors','locator':'Figure5A caption in search01.json'}
a(5,2,2,'IL5(E12K)','eosinophil viability','increases','cellular_phenotype','increase','The recombinant IL5 E12K mutant retained eosinophil survival-promoting activity in the 72-hour assay.','Figure5A-B caption and accompanying Results in search01.json','IL5(E12K) can promote eosinophil survival under these assay conditions.',object_type='cellular_phenotype',object_layer='F',stimulation='IL5 E12K concentration series',dose='series; Figure5B uses 50 nM',**il5)
a(6,2,2,'anti-IL5 antibody TRFK-5','eosinophil viability','reduces_IL5_supported_survival','cellular_phenotype','decrease','TRFK-5 neutralization blocked the survival activity of wild-type IL5 and IL5(E12K) in eosinophil cultures.','Figure5B and control-experiment Results in search01.json','TRFK-5 reduces the eosinophil survival supported by wild-type IL5 or IL5(E12K).',subject_type='antibody',object_type='cellular_phenotype',object_layer='F',evidence_tier='perturbational',stimulation='IL5 or IL5(E12K) plus TRFK-5',dose='IL5 1 pM or IL5(E12K) 50 nM; TRFK-5 250 µg/mL',**il5)
il2=dict(tissue='peripheral blood',cell_type='primary CD4+ T cell',duration='15 min',time_point='15 min',assay='STAT5 tyrosine-phosphorylation readout with CD25/Foxp3 gating; platform details unavailable',stimulation='IL2',uncertainty='Dose, donor count and full assay method unavailable.',limitations='Primary-cell result kept separate from YT cell-line experiments. Phosphorylation is not a measured suppressive function or proliferation endpoint.')
a(7,3,3,'IL2','STAT5 tyrosine phosphorylation','increases','protein_activity','increase','IL2 induced STAT5 tyrosine phosphorylation in human CD4 T cells at 15 minutes.','Results: IL-2-induced pSTAT5 activation is dependent on CD25 levels; Figure1A excerpt in search01.json','IL2 activates the measured STAT5 phosphorylation response at 15 min in these primary human CD4 T cells.',object_type='protein_modification',causal_directness='Cytokine perturbation; no receptor perturbation extracted.',**il2)
a(8,3,3,'IL2RA protein-expression stratum','STAT5 tyrosine phosphorylation','is_associated_with_greater_IL2_response','protein_activity','association','CD4 T cells with greater CD25 expression showed stronger IL2-induced STAT5 phosphorylation.','Figure1A-B and accompanying Results excerpt in search01.json','Higher CD25 expression strata associate with a greater 15-min IL2-induced pSTAT5 response in this cell preparation.',subject_type='protein_expression_stratum',object_type='protein_modification',evidence_tier='observational',causal_directness='CD25-stratified association, not a human primary-cell CD25 blockade experiment.',**il2)
a(9,4,4,'IL2','cell-cycle progression','does_not_initiate_detectably_when_given_alone','cellular_phenotype','null','The authors report that IL2 alone induced a transient STAT5 signal but did not initiate cell-cycle progression in quiescent primary human T cells.','Primary-source result excerpt in search01.json, Time-Dependent Regulation article','IL2 alone initiates cell-cycle progression in quiescent primary human blood T cells under the tested conditions.',object_type='cellular_phenotype',object_layer='F',tissue='peripheral blood',cell_type='primary T lymphocyte',cell_state='quiescent',stimulation='IL2 alone',causal_directness='Cytokine-only context contrast.',uncertainty='Dose, timing, assay and precision not recovered; no inference of universal IL2 unresponsiveness.',limitations='Short result excerpt only. Retained as provisional qualitative context contrast; cannot update existence prior or define absent receptor signaling.')
il17=dict(tissue='temporomandibular joint synovium',cell_type='patient-derived synovial fibroblast',disease='temporomandibular disorder',assay='IL6 ELISA of conditioned medium',uncertainty='Replicate n values are not confirmed donor counts except the three Fig7 patient samples.',limitations='Cultured disease-derived fibroblasts; no extrapolation to all immune cells. Full methods unavailable; pharmacological inhibitors do not uniquely prove target specificity.')
a(10,5,5,'IL17A','IL6','increases_extracellular_protein','secreted_protein','increase','IL17A increased extracellular IL6 in cultures from three human temporomandibular-joint synovial fibroblast samples.','Figure7 caption in search01.json','IL17A at 10 ng/mL increases conditioned-medium IL6 after 24 h in these three TMD fibroblast samples.',object_type='extracellular_protein',stimulation='IL17A',dose='10 ng/mL',duration='24 h',time_point='24 h',causal_directness='Purified cytokine treatment with extracellular protein measurement.',**il17)
a(11,5,5,'(5z)-7-Oxozeaenol','IL6','reduces_IL17A_induced_extracellular_protein','secreted_protein','decrease','TAK1-inhibitor pretreatment reduced IL17A-induced IL6 release in the eight-hour fibroblast assay.','Results section3.6 and Figure8 in search01.json','(5z)-7-Oxozeaenol pretreatment reduces IL17A-induced extracellular IL6 in this fibroblast assay.',subject_type='small_molecule_inhibitor',object_type='extracellular_protein',evidence_tier='perturbational',stimulation='IL17A after inhibitor pretreatment',dose='IL17A 10 ng/mL; inhibitor 1 µM',duration='30-min inhibitor pretreatment plus 8-h IL17A exposure',time_point='8 h after IL17A',causal_directness='Pathway-inhibitor cotreatment; no receptor knockout or rescue.',**il17)
a(12,5,5,'IRAK1/4 inhibitor','IL6','has_no_detected_effect_on_IL17A_induced_release','secreted_protein','null','IRAK1/4-inhibitor pretreatment did not detectably alter IL17A-induced IL6 production in the reported assay.','Results section3.6 and Figure8 in search01.json','IRAK1/4-inhibitor pretreatment reduces IL17A-induced extracellular IL6 under this tested condition.',subject_type='small_molecule_inhibitor',object_type='extracellular_protein',evidence_tier='perturbational',stimulation='IL17A after inhibitor pretreatment',dose='IL17A 10 ng/mL; inhibitor 20 µM',duration='30-min pretreatment plus 8-h IL17A',time_point='8 h after IL17A',causal_directness='Pharmacological perturbation with qualitative nondetection.',**il17)
il1=dict(tissue='skin',cell_type='primary human keratinocyte',uncertainty='Donor count and detailed baseline characteristics unavailable.',limitations='Only explicitly human in-vitro arm retained. No transport of mouse IL1R1-knockout evidence to the human experiment.')
a(13,6,6,'primary keratinocyte','IL1A','releases_extracellular_protein_after_imiquimod','secreted_protein','increase','Imiquimod-treated primary human keratinocytes had increased IL1A protein in conditioned medium.','Figure2 heading/caption and Results in search02.json','Imiquimod treatment increases extracellular IL1A recovered from these primary human keratinocyte cultures.',subject_type='cell',subject_layer='C',object_type='extracellular_protein',evidence_tier='P1',stimulation='imiquimod',assay='conditioned-medium IL1A ELISA',causal_directness='Direct extracellular protein measurement after a non-cytokine perturbation.',**il1)
assertions[-1]['limitations']+=' Release from damaged cells versus regulated secretion is unresolved; LDH was measured in the study but its result was not extracted. Figure3 dose/time is not imputed to Figure2.'
a(14,6,6,'anti-IL1A antibody','CXCL8','has_no_detected_effect_on_imiquimod_induced_release','secreted_protein','null','Neutralizing IL1A did not reduce the imiquimod-induced chemokine response reported for primary human keratinocytes, including CXCL8.','Results: Imiquimod induced chemokine expression is independent of IL1A signaling; Figure3A in search02.json','IL1A neutralization reduces imiquimod-induced extracellular CXCL8 at 6 h in these primary human keratinocytes.',subject_type='antibody',object_type='extracellular_protein',evidence_tier='perturbational',stimulation='imiquimod with anti-human IL1A or isotype control',dose='imiquimod 50 µg/mL; antibody concentration unavailable',duration='30-min pretreatment; 6-h stimulation',time_point='6 h',assay='chemokine ELISA',causal_directness='Neutralizing-antibody contrast; lack of inhibition does not exclude another IL1 context.',**il1)
a(15,7,7,'IL1A','CXCL8','increases_extracellular_protein','secreted_protein','increase','Primary human keratinocytes increased CXCL8 release in response to recombinant IL1A at the higher tested concentrations.','Figure3B and accompanying Results in search02.json','Recombinant IL1A at concentrations above 0.1 ng/mL increases extracellular CXCL8 in the reported primary human keratinocyte assay.',object_type='extracellular_protein',tissue='skin',cell_type='primary human keratinocyte',stimulation='recombinant IL1A',dose='response reported above 0.1 ng/mL; full concentration series unavailable',assay='cell-culture supernatant CXCL8 ELISA',causal_directness='Purified cytokine perturbation.',uncertainty='Duration, donor count and effect estimate unavailable.',limitations='Primary-source result excerpt only. Fibroblast versus keratinocyte potency comparison not quantified here; receptor blockade not assigned to this keratinocyte arm.')

# Full-method continuation: Chrome displayed all eight primary articles without
# an access challenge. The saved passages below are selected source text, not
# reconstructed summaries or full-article downloads.
metadata={
2:(1997,'10.1084/jem.186.1.121','9207003',['Murray McKinnon','Kevin Page','Iain J Uings','Martyn Banks','Dilniya Fattah','Amanda EI Proudfoot','Pierre Graber','Christian Arod','Richard Fish','Timothy NC Wells','Roberto Solari'],'PMC2198963'),
3:(2019,'10.4049/jimmunol.1801570','31085588',['Ying Ding','Aixin Yu','George C Tsokos','Thomas R Malek'],'PMC6581624'),
4:(2016,'10.1371/journal.pone.0167215','27936140',['Alla N Shatrova','Elena V Mityushova','Irina O Vassilieva','Nikolay D Aksenov','Valery V Zenin','Nikolay N Nikolsky','Irina I Marakhova'],'PMC5172478'),
5:(2015,'10.1155/2015/436067','26839464',['Toshio Hattori','Naomi Ogura','Miwa Akutsu','Mutsumi Kawashima','Suguru Watanabe','Ko Ito','Toshirou Kondoh'],'PMC4709758'),
6:(2013,'10.1038/jid.2012.512','23407395',['Mireia Uribe-Herranz','Li-Hua Lian','Kirsten M Hooper','Katelynn A Milora','Liselotte E Jensen'],'PMC3656131'),
7:(2022,'10.3389/fimmu.2022.984045','36268013',['Sevda Cordier-Dirikoc','Nathalie Pedretti','Julien Garnier','Sandrine Clarhaut-Charreau','Bernhard Ryffel','Franck Morel','François-Xavier Bernard','Valérie Hamon de Almeida','Jean-Claude Lecron','Jean-François Jégou'],'PMC9576869'),
8:(2009,'10.1111/j.1365-2567.2008.02903.x','19278422',['Catherine A Thornton','Judith A Holloway','Janis K Shute','John W Holloway','Norma D Diaper','John O Warner'],'PMC2673366')}
for n,(year,doi,pmid,authors,pmc) in metadata.items():
    sources[n-1].update(year=year,doi=doi,pmid=pmid,authors=authors,access_level='full_article_inspected_via_Chrome_selected_passages_archived',snapshot_path=str(B/'snapshots'/f'{pmc}_selected.txt'),version=pmc+' article displayed in PMC on 2026-09-13',notes='Relevant full-article Methods, Results and figure captions inspected through Chrome. Selected source passages archived; supplements and raw participant data not reviewed. Human primary-cell assertions are distinct from any cell-line or animal experiments.')
sources[0]['notes']='Methods and Results through Figure2 saved in open01.json; later Figure7 and ICAM1 perturbation Methods independently inspected in Chrome and saved in PMC4465562_survival.txt.'
sources[0]['additional_snapshot_paths']=[str(B/'snapshots'/'PMC4465562_survival.txt')]
sources[2]['species']=['Homo sapiens','Mus musculus']
cohorts[1].update(participants='healthy blood donors with mildly elevated eosinophil count',disease='healthy',notes='CD16 negative selection, >95% purity. Recombinant E. coli expression is the cytokine reagent host; COS transfected cells and TF1 cell-line binding assays are not extracted as primary-human results. Survival and adhesion experiments share study but unique-donor overlap unresolved.')
cohorts[2].update(participants='healthy adult donors aged 20–45 years; Continental Blood Bank, Miami',donor_count='five different healthy adult donors in Figure1',sample_count='typically 100000 PBMC flow events per sample; events are not participants',cell_type='CD4+ cells gated within unfractionated PBMCs',notes='Figure1 uses unfractionated PBMCs rested 1 h before IL2. Do not conflate with purified/expanded lentivirus-treated Tregs, YT cells or mouse arms.')
cohorts[3].update(participants='healthy adult venous-blood donors',sample_count='Table1 five independent experiments with different donors; Figure3 four',donor_count='Table1 five; Figure3 four; overall overlap unavailable',cell_type='peripheral blood lymphocytes, >85% CD3+',notes='Histopaque separation and plastic-adherence monocyte depletion; overnight rest in RPMI plus5% human serum. Mixed lymphocyte preparation, not purified Treg. Table1 and prose disagree on IL2-only cycling fraction and dose labels; quantitative effect not harmonized.')
cohorts[4].update(participants='TMJ1 female age23; TMJ2 female age26; TMJ3 male age59',disease='internal derangement or osteoarthritis of temporomandibular joint; per-donor assignment unavailable',notes='Primary outgrowth cultures at passages6–8. Three unique patients; six ELISA experiments are not six patients. Inhibitor Figure8 donor identity not specified. Microarray accession GSE74668 applies to TMJ1 transcript profiling, not an independently sampled cohort.',accession='GSE74668 (transcript arm only)')
cohorts[5].update(participants='commercial pooled human primary keratinocytes, Life Technologies',sample_count='at least three independent experiments; n=2 per time-point/treatment within an experiment unless stated',notes='Commercial pooled cells in defined keratinocyte serum-free medium, adapted >=24h. Pool donor number unavailable. Mouse newborn keratinocytes and in vivo mouse knockout excluded.')
cohorts[6].update(cell_type='normal human epidermal keratinocyte; normal human dermal fibroblast',intervention='recombinant IL1A concentration responses',notes='Human skin-derived primary cultures. Figure3-specific exposure24h retained despite generic Methods48h. Fibroblasts in broader site comparison span breast, abdomen, ear, foreskin and ages7months–51years; per-Figure3 donor assignment and unique count unavailable.')
cohorts[7].update(participants='amniotic-fluid donors at16–18weeks and elective Caesarean atterm; separate healthy adult blood donors provide target CD4 T cells',tissue='amniotic fluid; adult peripheral blood target cells',donor_count='20 mid-gestation fluid donors;16term fluid donors; chemotaxis n=6/group and neutralization n=5 fluid samples; adult target-cell unique donor count unavailable',sample_count='chemotaxis triplicate wells, five high-power fields/well; not donor counts',notes='No indication of fetal abnormality in included pregnancies. CD4+CD3+ target cells >95%purity. Fluid assays and target blood donors are not one participant population. Same-study neutralization and chemotaxis subsets are not counted as independent replication; exact fluid-ID overlap unavailable.')
for row in assertions:
    row.update(qc_status='reviewed_extraction',qualitative_confidence='moderate')
    row['scoring_annotation']['rationale']=('The tested contrast was inspected in primary-article methods/results. A qualitative null remains inconclusive for absence.' if row['direction']=='null' else 'Direct source inspection supports this narrow context-specific hypothesis.')+' Independent exact-pack-hash review is still required for prior eligibility.'
assertions[2].update(source_locator='PMC4465562_survival.txt: Methods ICAM1 inhibition; Figure5 target-expression validation; Results and Figure7A; culture/viability Methods also open01.json',duration='1-h antisense pretreatment;48-h CSF2 culture',limitations='Antisense with sense control and target-protein validation; no rescue, direct CSF2 receptor knockout or unique-donor uncertainty reported. ICAM1 is not asserted to bind CSF2 directly.')
assertions[2]['quantitative_result']={'value':42,'unit':'percent viable eosinophils','comparator':'78% with CSF2 alone;73% with CSF2 plus sense oligonucleotide','uncertainty':'Figure7 values; donor-level uncertainty not reported in selected passage','donor_sample_basis':U,'locator':'PMC4465562_survival.txt Results Figure7A'}
for row in assertions[3:6]:
    row.update(disease='healthy',source_locator='PMC2198963_selected.txt: Eosinophil Purification; Eosinophil Survival Assay; Results and Figure5A-B',uncertainty='Figure5A six independent donor experiments, means±SEM; Figure5B >=3 experiments, donor overlap unavailable.',limitations='Survival readout does not establish proliferation or degranulation. Mutant protein is distinct from wild type. Full concentration-axis range not transcribed; no binding inference from this survival experiment.')
assertions[3]['quantitative_result']['locator']='PMC2198963_selected.txt Figure5A'
for row in assertions[6:8]:
    row.update(age='20–45 years',disease='healthy',cell_type='CD4+ cells gated within unfractionated PBMCs',cell_state='1-h rest in RPMI complete medium before stimulation',assay='pSTAT5 phospho-flow cytometry with surface CD25 and intracellular Foxp3 gating; BD LSRFortessa or LSR II',dose='IL2 dose-response series; exact axis range not transcribed',source_locator='PMC6581624_selected.txt: pSTAT5 Analysis; Antibodies and Flow Cytometry; Results and Figure1',uncertainty='Five different adult donors; mean±SEM; detailed numerical dose-response points unavailable.',limitations='Subset-stratified PBMC assay, not purified CD4 culture. CD25 association is not a receptor knockdown. No T-cell suppression or proliferation inferred from pSTAT5.')
assertions[7]['subject']='IL2RA surface-protein expression stratum'
assertions[8].update(predicate='does_not_elicit_full_proliferative_response_in_quiescent_culture',evidence_summary='IL2 alone produced a low cell-cycle response in quiescent lymphocyte cultures compared with the full response to mitogenic PHA. It did not imply zero cycling cells.',tissue='peripheral blood',cell_type='lymphocyte preparation, >85% CD3+ cells',disease='healthy',duration='48 h',time_point='48 h',assay='propidium-iodide DNA-content flow cytometry; S+G2+M fraction',source_locator='PMC5172478_selected.txt: isolation and flow cytometry Methods; Table1; Results IL2 up-regulates CD25 in competent but not quiescent PBL',uncertainty='Table1 five donor experiments, mean±SD; prose4.3% conflicts with table2.3% for IL2-only cycling. Dose labels100 vs200 are not silently reconciled.',limitations='Qualitative failure to induce a full mitogenic response, not complete absence of cell-cycle entry. Source numeric inconsistencies preclude a harmonized quantitative effect or dose. Mixed lymphocytes, not purified Tregs.',qualitative_confidence='low')
assertions[8]['scoring_annotation'].update(tested_hypothesis='IL2 alone elicits the full proliferative response seen with mitogenic PHA in these quiescent human lymphocyte cultures by48h.',evidence_relation='inconclusive',null_adequacy='No prespecified full-response/equivalence bound; small cycling fractions are reported and the source numbers conflict. Cannot infer absent IL2-cell-cycle relationship.')
for row in assertions[9:12]:
    row.update(cell_state='primary outgrowth synovial fibroblasts, passages6–8;confluent cultures after24h in2%FBS',source_locator='PMC4709758_selected.txt: Methods2.1,2.6; Results3.5/Figure7 or3.6/Figure8 as specified by assay contrast',uncertainty='Three donor-derived cultures inFigure7; six independent ELISA experiments. Figure8 n=4 but donor identity unavailable.',limitations='Disease-derived cultured fibroblasts; target-specific pharmacological effects are not proven by these inhibitors. Primary Methods and result captions inspected.')
assertions[9].update(age='23,26,59 years',sex='two female,one male')
assertions[12].update(duration='IL1A detectable increase by3h;extended course includes24h',time_point='3h early detectable extracellular increase',cell_state='confluent pooled primary culture, >=24h defined-medium adaptation',source_locator='PMC3656131_selected.txt: Cell culture; Results IL1A release; Figure2a-b',uncertainty='>=3 independent experiments; n=2 per treatment/time unless otherwise stated. Commercial pool donor count unavailable.',limitations='Measured conditioned-medium IL1A. Early IL1A preceded the reported LDH increase, but no specific export mechanism is established; later cell damage is present. Exact Figure2 dose-axis values not transcribed.')
assertions[13].update(subject='anti-IL1A antibody MAB200',cell_state='confluent pooled primary culture, >=24h defined-medium adaptation',source_locator='PMC3656131_selected.txt: Culture treatments; Results IL1A neutralization; Figure3a',uncertainty='>=3 independent experiments; n=2 per treatment/time unless otherwise stated; no equivalence bound.',limitations='Antibody concentration delegated to an earlier methods citation, not recovered here. IL1A and polyIC inhibition provide same-study positive controls; ordinary nonsignificance still cannot establish absence. Mouse receptor KO excluded.')
assertions[14].update(duration='24h according toFigure3',time_point='24h',source_locator='PMC9576869_selected.txt: Cell cultures; Figure3B caption and Results',uncertainty='Per-Figure3 unique donor count and numerical uncertainty unavailable.',limitations='Human primary keratinocytes. Figure3 explicitly gives24h whereas generic Methods say48h; figure-specific24h retained. Receptor-blocking fibroblast and mouse arms are not assigned to this keratinocyte response.')

il16=dict(tissue='adult peripheral blood target cells;amniotic fluid stimulus',cell_type='purified adult CD4+CD3+ T cells',age='adult target cells; fluid16–18weeks gestation',duration='45-min antibody/sample preincubation;2-h migration',time_point='2h',assay='5µm-filter micro-Boyden chemotaxis;triplicate wells,5high-power fields;buffer background subtracted',qc_status='reviewed_extraction',qualitative_confidence='moderate',uncertainty='Five fluid donors;adult target blood donor number unavailable.',limitations='Mixture stimulus with partial IL16 dependence. No source-cell secretion, fetal-cell migration, in vivo trafficking, or CD4 receptor-blockade proof inferred.')
a(16,8,8,'anti-IL16 polyclonal antibody','CD4 T-cell chemotaxis','reduces_amniotic_fluid_induced_migration','cellular_phenotype','decrease','Anti-IL16 reduced the CD4 T-cell chemotaxis induced by mid-gestation amniotic fluid relative to the isotype control.','PMC2673366_selected.txt: Chemotaxis assay; Results and Figure1c','IL16 neutralization reduces adult CD4 T-cell migration induced by1:10 mid-gestation amniotic fluid under this assay.',subject_type='antibody',object_type='cellular_phenotype',object_layer='F',evidence_tier='perturbational',dose='antiIL16 10µg/mL;amniotic fluid1:10',stimulation='amniotic fluid with antiIL16 orgoatIgG',causal_directness='Ligand-neutralizing antibody with isotype and recombinant-ligand positive controls; partial mixture-response attribution.',**il16)
assertions[-1]['quantitative_result']={'value':42.09,'unit':'percent of fluid-alone chemotactic activity remaining','comparator':'isotype control99.67%','uncertainty':'SEM6.95 vs7.88;P=0.0006','donor_sample_basis':'five amniotic-fluid donors;target-cell unique donor count unavailable','locator':'PMC2673366_selected.txt Results Figure1c'}
a(17,8,8,'amniotic fluid (16–18weeks gestation)','CD4 T-cell chemotaxis','induces_greater_migration_than_term_fluid','cellular_phenotype','increase','Mid-gestation amniotic fluid induced greater adult CD4 T-cell migration than term fluid in the same assay.','PMC2673366_selected.txt: sample collection;Chemotaxis assay;Results Figure1b','Mid-gestation amniotic fluid diluted1:2 induces greater adult CD4 T-cell chemotaxis than term amniotic fluid diluted1:2.',subject_type='biofluid',subject_layer='C',object_type='cellular_phenotype',object_layer='F',evidence_tier='observational',dose='fluid1:2',stimulation='mid-gestation versus term fluid',causal_directness='Biofluid-mixture exposure; difference cannot be assigned solely to IL16.',**{**il16,'duration':'2h','uncertainty':'six fluid samples per group;adult target blood donor number unavailable.'})
assertions[-1]['quantitative_result']={'value':134.76,'unit':'migrated cells per high-power field','comparator':'term fluid21.79 cells/field','uncertainty':'SEM17.67 vs13.53;P=0.0006','donor_sample_basis':'six fluid samples per group','locator':'PMC2673366_selected.txt Results Figure1b'}
a(18,8,8,'amniotic fluid (16–18weeks gestation)','IL16','contains_higher_immunoreactive_protein_than_term_fluid','protein_abundance','increase','Mid-gestation fluid contained greater immunoreactive IL16 than fluid collected at term.','PMC2673366_selected.txt: sample collection;IL16 ELISA;Results Figure1a','Immunoreactive IL16 abundance is higher in16–18week amniotic fluid than term fluid in the sampled pregnancies.',subject_type='biofluid',subject_layer='C',object_type='extracellular_protein',evidence_tier='observational',tissue='amniotic fluid',cell_type='cell-free biofluid;source cells unresolved',age='16–18weeks gestation versus term>37weeks',assay='Biosource IL16 ELISA;1:2sample dilution;sensitivity23pg/mL',time_point='collection at16–18weeks or term',causal_directness='Cross-sectional protein abundance;no source-cell secretion measurement.',uncertainty='20mid-gestation and16term fluid donors;P<0.001;effect size not extracted.',limitations='Immunoreactivity does not establish mature active isoform abundance. Cell source and export pathway unresolved. This is not a source-cell secretion edge.',qc_status='reviewed_extraction',qualitative_confidence='moderate')
a(19,2,2,'IL5(E12K)','eosinophil adhesion to immobilized IgG','does_not_detectably_induce_adhesion','cellular_phenotype','null','The IL5 E12K mutant did not detectably induce eosinophil adhesion in the30-minute assay despite retained survival activity in a distinct72-hour assay.','PMC2198963_selected.txt: Eosinophil Activation Assay;Results and Figure4A','IL5(E12K) induces adhesion of these human eosinophils to immobilized IgG within30min.',object_type='cellular_phenotype',object_layer='F',tissue='peripheral blood',cell_type='purified eosinophil',disease='healthy',stimulation='IL5 E12K concentration response',dose='up to1µM',duration='30min',time_point='30min',assay='IgG-coated plate adhesion;wash,lysis,endogenous-peroxidase colorimetry',causal_directness='Mutant-cytokine perturbation;wild-typeIL5 positive control.',uncertainty='three independent experiments using different donors;mean±SEM;absence bound unavailable.',limitations='Assay-specific nondetection,not general IL5-receptor inactivity or an absence prior. Survival and adhesion have different doses/times/readouts.',qc_status='reviewed_extraction',qualitative_confidence='moderate',contradiction_group='XCI-CONTEXT-IL5-E12K')
assertions[4]['contradiction_group']='XCI-CONTEXT-IL5-E12K'
a(20,5,5,'IL17A','IL6','does_not_significantly_increase_release_at_low_dose','secreted_protein','null','At1ng/mL, IL17A did not significantly increase conditioned-medium IL6 relative to untreated fibroblasts in the reported24-hour dose experiment.','PMC4709758_selected.txt: Methods2.6;Results3.5 and Figure5','IL17A at1ng/mL increases extracellular IL6 at24h in these cultured human synovial fibroblasts.',object_type='extracellular_protein',tissue='temporomandibular joint synovium',cell_type='patient-derived synovial fibroblast',cell_state='passages6–8;confluent after24h2%FBS',disease='internal derangement or osteoarthritis ofTMJ',stimulation='IL17A',dose='1ng/mL',duration='24h',time_point='24h',assay='conditioned-medium IL6 ELISA',causal_directness='Cytokine dose-context contrast.',uncertainty='n=6independent ELISA experiments;donor identity perFigure5 unavailable;no equivalence bound.',limitations='Nonsignificance atlow dose does not negate IL17A-IL6 relationship;10ng/mL positive response retained separately.',qc_status='reviewed_extraction',qualitative_confidence='moderate',contradiction_group='XCI-CONTEXT-IL17A-DOSE')
assertions[9]['contradiction_group']='XCI-CONTEXT-IL17A-DOSE'
a(21,7,7,'IL1A','CXCL8','increases_fibroblast_extracellular_protein','secreted_protein','increase','Recombinant IL1A increased extracellular CXCL8 in primary human dermal fibroblast cultures over the low-dose concentration response.','PMC9576869_selected.txt: Cell cultures;Results and Figure3A','IL1A exposure increases conditioned-medium CXCL8 in these primary human dermal fibroblasts over24h.',object_type='extracellular_protein',tissue='skin dermis',cell_type='normal human dermal fibroblast',stimulation='recombinant IL1A',dose='increasing response over10^-5–10^-1ng/mL;plateau from10^-1ng/mL',duration='24h perFigure3',time_point='24h',assay='conditioned-medium CXCL8 ELISA',causal_directness='Purified cytokine perturbation with measured extracellular protein.',uncertainty='Per-Figure3 unique donor number and numerical uncertainty unavailable.',limitations='Figure3-specific24h retained despite general Methods48h. No inference of source-cell release from keratinocyte RNA, receptor abundance or mouse knockout.',qc_status='reviewed_extraction',qualitative_confidence='moderate',contradiction_group='XCI-CONTEXT-IL1A-CELL')
assertions[14]['contradiction_group']='XCI-CONTEXT-IL1A-CELL'
a(22,4,4,'IL2','cell-cycle progression','increases_after_weak_PHA_preconditioning','cellular_phenotype','increase','IL2 promoted cell-cycle entry in lymphocyte cultures preconditioned with a submitogenic PHA dose.','PMC5172478_selected.txt: isolation/flow Methods;Results following Figure3;Figure3C','IL2 promotes S+G2+M-phase entry in human lymphocytes after weakPHA preconditioning.',object_type='cellular_phenotype',object_layer='F',tissue='peripheral blood',cell_type='lymphocyte preparation,>85%CD3+',cell_state='preconditioned with weakPHA',disease='healthy',stimulation='PHApreconditioning followedbyIL2',dose='PHA0.7µg/mL;Figure3IL2condition200U/mL;Table1dose/timing labels inconsistent',duration='Figure3preconditioning24h thenIL2 next24h',time_point='48h overall',assay='propidium-iodide DNA-content flow cytometry;S+G2+M fraction',causal_directness='Sequential mitogen/cytokine perturbation;not IL2alone.',uncertainty='Figure3 four independent donor experiments;mean±SEM;harmonized numerical effect withheld.',limitations='PHA is a polyclonal mitogen,not antigen-specific TCR stimulation. Table1 has inconsistent timing/dose labels; record uses Figure3-specific context and remains low-confidence pending independent review.',qc_status='reviewed_extraction',qualitative_confidence='low',contradiction_group='XCI-CONTEXT-IL2-COMPETENCE')
assertions[8]['contradiction_group']='XCI-CONTEXT-IL2-COMPETENCE'

searches=[]
for n in [1,2]:
    obj=json.loads((B/'snapshots'/f'search{n:02}.json').read_text())
    searches.append(dict(search_id=f'XCI-Q{n:02}',lane='cytokine expansion',query=json.dumps(obj['queries'],ensure_ascii=False),database='web search, batched queries',searched_at=DATE,result_source_ids=['XCI-S01','XCI-S02','XCI-S03','XCI-S04','XCI-S05','XCI-S08'] if n==1 else ['XCI-S06','XCI-S07'],screening_notes='Actual batched query strings retained. Returned results are a bounded ranked sample; the tool did not attribute each merged result to one individual query. This ID identifies the complete batch.'))
searches.append(dict(search_id='XCI-Q03',lane='full-text retrieval',query='NCBI efetch db=pmc id=4465562,2198963,2673366,4709758,6581624,5172478,9576869,3656131 retmode=xml',database='NCBI Entrez helper',searched_at=DATE,result_source_ids=[],screening_notes='Exact request saved in pmc_request.json. Sandbox DNS failure; elevated network retry waited on approval and was aborted. No source XML downloaded. No further shell network calls attempted.'))
searches.append(dict(search_id='XCI-Q04',lane='primary-page retrieval',query='Open PMC4465562, PMC2198963, PMC5172478; then PMC2673366, PMC4709758, PMC9576869, PMC6581624',database='web open',searched_at=DATE,result_source_ids=['XCI-S01'],screening_notes='open01.json/open02.json retain actual outcomes. Only PMC4465562 returned article sections; other six returned CAPTCHA. No CAPTCHA bypass attempted.'))
searches.append(dict(search_id='XCI-Q05',lane='exact-title follow-up',query=json.dumps(json.loads((B/'snapshots'/'search03.json').read_text())['queries'],ensure_ascii=False),database='web search,batched queries',searched_at=DATE,result_source_ids=['XCI-S02','XCI-S03','XCI-S05','XCI-S08'],screening_notes='Actual four exact-title queries and ranked outcomes saved in search03.json. Relevant primary IL16 results recovered; irrelevant signed-link token redacted. No exhaustive-search claim.'))
searches.append(dict(search_id='XCI-Q06',lane='alternate-repository retrieval',query='Open EuropePMC articles PMC2198963,PMC2673366,PMC4709758,PMC6581624',database='web open EuropePMC',searched_at=DATE,result_source_ids=[],screening_notes='All four returned URL-not-safe non-retryable tool failures; actual outcomes in open03.json. No retrieved article content claimed.'))
searches.append(dict(search_id='XCI-Q07',lane='full-method closure',query='Chrome opens known PMC pages:2198963,2673366,6581624,5172478,4709758,3656131,9576869,4465562',database='Chrome browser visible article DOM',searched_at=DATE,result_source_ids=[s['source_id'] for s in sources],screening_notes='All eight article pages displayed full content without CAPTCHA. Relevant primary Methods,Results and captions read; selected verbatim passages saved under PMC-prefixed snapshot files, with article locators. No browser full-export/download claimed. Navigation,account details and external link metadata excluded.'))
gaps=[{'gap_id':'XCI-G01','topic':'IL16 source and receptor','detail':'Adult CD4 chemotaxis and partial antiIL16 inhibition are now extracted. Fetal source-cell secretion, cytokine active-isoform identity,CD4 receptor dependence,and in vivo trafficking remain unmeasured in the retained experiment.'},{'gap_id':'XCI-G02','topic':'Access closure','detail':'All eight sources now have relevant full-article Methods and Results inspected through Chrome. No needs_full_text flags remain solely due to initial web failures. Selected passages,not complete downloaded articles,are archived. Independent exact-pack-hash review remains pending.'},{'gap_id':'XCI-G03','topic':'Mechanistic limits','detail':'No complete paths constructed. No human receptor knockout inferred from mouse arms. Ligand neutralization and signaling inhibitors are not direct binding evidence. Antisense and pharmacological specificity remain limited.'},{'gap_id':'XCI-G04','topic':'Cohort independence','detail':'Unique donors,ancestry,and assay-arm overlap remain unavailable when not reported. Commercial keratinocyte pools and technical/experimental replicates are not treated as independent people. Fluid-donor and target-cell-donor counts are distinct.'},{'gap_id':'XCI-G05','topic':'Source inconsistencies','detail':'XCI-S04 Table1 and text disagree on IL2-only cycling values and dose/timing labels. XCI-A09/A22 are low-confidence qualitative context records. XCI-S07 generic Methods48h conflicts with Figure3-specific24h;Figure3 duration retained explicitly.'},{'gap_id':'XCI-G06','topic':'Bounded coverage','detail':'All six assigned cytokines have primary human responses represented. Coverage is a targeted supplement rather than a systematic or exhaustive review. Broad source-secretion and receptor-perturbation gaps remain; no counts were inflated by transporting unmeasured biology.'}]
pack=dict(sources=sources,cohorts=cohorts,assertions=assertions,searches=searches,gaps=gaps,synthesis='This targeted expansion covers CSF2-induced eosinophil proteins and ICAM1-dependent survival;IL5 survival and a mutant adhesion contrast;IL2 STAT5 activation and quiescent/competent-cell contexts;IL17A-induced fibroblast IL6 with dose/inhibitor contrasts;IL1A-associated keratinocyte and fibroblast responses;and partial IL16-dependent adult CD4 chemotaxis induced by amniotic fluid. Relevant full methods are inspected for all sources. Null observations remain inconclusive for absence. No complete path or calibrated numerical prior is constructed.')
(B/'pack.json').write_text(json.dumps(pack,indent=2,ensure_ascii=False)+'\n')

# Every returned search candidate is logged, not only the selected papers.
screen=[]
included={s['url'].rstrip('/'):s for s in sources}
for q in [1,2,3]:
    payload=json.loads((B/'snapshots'/f'search{q:02}.json').read_text())['response']
    for block in payload.split('--------------------------------------------------------------------------------'):
        first=block.strip().splitlines()[0] if block.strip() else ''
        m=re.match(r'(.+) \((https?://[^\s]+)\)$',first)
        if not m:continue
        title,url=m.groups(); normalized=url.split('?')[0].rstrip('/')
        s=included.get(normalized)
        if s is None:
            s=next((z for z in sources if z['pmid']!=U and f'pubmed.ncbi.nlm.nih.gov/{z["pmid"]}' in normalized),None)
        if s is None:
            s=next((z for z in sources if title.casefold().strip()==z['title'].casefold().strip()),None)
        if s:
            decision='include'
            reason='Relevant primary human result selected;full Methods and Results subsequently inspected in Chrome. Duplicate repository or PubMed records map to the same source.'
        else:
            decision='exclude'
            if any(x in title.lower() for x in ['review','survival and apoptosis in health','interleukin 1-alpha','siglec8']):reason='Review/general reference; not used as a primary perturbation assertion.'
            elif any(x in title.lower() for x in ['endothelin','dapsone','two-step adhesion','shear stress','neutralization of il-8']):reason='Different perturbation or unresolved IL1 species; outside this bounded extraction.'
            else:reason='Potentially relevant primary or secondary candidate not selected after stronger accessible targeted results; full source not inspected in this bounded pass.'
        screen.append(dict(candidate_id=f'XCI-C{len(screen)+1:03}',query_id=f'XCI-Q{(5 if q==3 else q):02}',title=title,url=normalized,doi=s['doi'] if s else U,pmid=s['pmid'] if s else U,decision=decision,reason=reason,source_id=s['source_id'] if s else U))
(B/'screening.json').write_text(json.dumps({'scope':'All candidates returned in three saved search batches that expose a title/URL header; no exhaustive-search claim. No reference-list citation chaining performed. URL query metadata omitted. Primary full-method closure documented as XCI-Q07.','candidates':screen},indent=2,ensure_ascii=False)+'\n')
for row in assertions:
    assert all(k in row for k in fields)
    assert all(v is not None and v!='' for v in row.values())
assert len({x['assertion_id'] for x in assertions})==len(assertions)
assert all(Path(s['snapshot_path']).exists() for s in sources)
assert all(a['source_id'] in {s['source_id'] for s in sources} and a['cohort_id'] in {c['cohort_id'] for c in cohorts} for a in assertions)
assert all(a['scoring_annotation']['evidence_relation']=='inconclusive' for a in assertions if a['direction']=='null')
