#!/usr/bin/env python3
"""Apply separately recovered primary methods after the reviewed stable stage."""
import hashlib,json,re,runpy
from pathlib import Path
from urllib.parse import urlsplit,urlunsplit
OUT=Path(__file__).resolve().parent
v=runpy.run_path(str(OUT/'upgrade_pack.py'))
p=v['p'];u=v['u'];ROOT=u['ROOT'];NA=v['NA'];cohort=v['cohort'];assertion=v['assertion'];snap=v['snap'];write=v['write']
END='2026-09-13 18:46:00 UTC'
ft='research/fulltext_followup/XCH_S008_Loetscher1996_selected_primary.json'
s8=next(s for s in p['sources'] if s['source_id']=='XCH_S008')
s8.update(authors='Marcel Loetscher; Basil Gerber; Pius Loetscher; Simon A Jones; Luca Piali; Ian Clark-Lewis; Marco Baggiolini; Bernhard Moser',pmid='9064356',url='https://pmc.ncbi.nlm.nih.gov/articles/PMC2192763/',snapshot_path=ft,access_level='full_text_primary_pdf_selected_passages',retrieved_at='2026-09-13T18:34:36Z',version='Published article1996;184:963–969; primary PDF with historical OCR artifacts',ingestion_status='extracted',notes='Primary PDF recovered and inspected by independent cytokine lane, then curator inspected exact saved Methods/Results. Figure4 donor-buffy-coat PBL are separate from mouse300-19 calcium and humanJurkat transfectant migration. Figure3 measures RNA; failed radioligand binding with60–80% nonspecific signal supplies no affinity estimate.')
s10=dict(source_id='XCH_S010',title='A Novel Highly Potent Therapeutic Antibody Neutralizes Multiple Human Chemokines and Mimics Viral Immune Modulation',authors='Michelle L Scalley-Kim; Bruce W Hess; Ryan L Kelly; Anne-Rachel F Krostag; Kurt H Lustig; John S Marken; Pamela J Ovendale; Aaron R Posey; Pamela J Smolak; Janelle D L Taylor; C L Wood; David L Bienvenue; Peter Probst; Ruth A Salmon; Daniel S Allison; Teresa M Foy; Carol J Raport',year=2012,url='https://pmc.ncbi.nlm.nih.gov/articles/PMC3422223/',doi='10.1371/journal.pone.0043332',pmid='22912856',source_type='primary_study',version='Published2012 Aug17;7(8):e43332',retrieved_at='2026-09-13 18:31:00 UTC',access_level='full_text_chrome_selected_passages',snapshot_path=snap('ScalleyKim2012_chrome.txt'),species='Homo sapiens',ingestion_status='extracted',notes='Direct mixed-human-PBMC supernatant measurements only. Ba/F3 receptor-transfectant migration, three-ligand human phosphorylation and mouse engraftment are separate experiments not assigned to individual primary-human ligand responses. Exact Rules Based Medicine assay platform is unspecified.')
p['sources'].append(s10)
c13=cohort(13,'XCH_S010','Healthy human blood volunteers; source-supernatant donor number unavailable','peripheral blood-derived PBMC culture supernatant','peripheral blood mononuclear cell mixture','LPS and IFNG stimulated with IL2 present','healthy volunteers','48h LPS1 μg/mL + recombinant human IFNG1000 U/mL + IL2 50 U/mL',notes='Mixed PBMC source; no specific producing subset assigned. Six donors in phosphoflow experiments are not a secretion donor count. Pooling, sex, age, ancestry and overlap with other studies unavailable.')
for i,chem,value in [(23,'CCL3',71),(24,'CCL4',398)]:
    a=assertion(i,chem,c13,'XCH_S010',chem,'extracellular_protein_detected_in_supernatant',f'{chem} protein was quantified in conditioned medium from stimulated healthy-human PBMC.', 'ScalleyKim2012 Materials and Methods Human Blood Samples s2b AX190–192; Chemotaxis AX269–276; ScalleyKim2012_chrome.txt.',tier='P1',direction='association',measurement='secreted_protein',reviewed=True,subject='human peripheral blood mononuclear cell mixture',subject_type='cell',subject_layer='C',cell_state='Mixed PBMC cultured48 h with LPS, IFNG and IL2',stimulation='LPS plus recombinant human IFNG in the presence of IL2',dose='PBMC10 million/mL; LPS1 μg/mL, IFNG1000 U/mL, IL2 50 U/mL',duration='48 h culture',time_point='48 h conditioned-medium collection',assay='Extracellular chemokine protein quantified by Rules Based Medicine; exact platform unspecified',effect_size=value,effect_unit='ng/mL supernatant concentration',uncertainty='No uncertainty or calibrated detection limit reported',causal_directness='Direct protein measurement in source-cell supernatant; no unstimulated comparator establishes induction and no producing PBMC subset identified.',limitations='Single reported conditioned-medium concentration, with donor number, pooling and precision unavailable. No unstimulated control concentration, secretion rate, cell-viability correction or specific producing-cell identity. Six phosphorylation donors and Ba/F3 chemotaxis replicates do not define this source experiment.',quantitative_result={'value':value,'unit':'ng/mL','comparator':'No unstimulated concentration reported','uncertainty':'unavailable','donor_sample_basis':'Source PBMC donor number and pooling unavailable','locator':'Methods Chemotaxis AX276'})
    a['scoring_annotation'].update(tested_hypothesis=f'Human PBMC release extracellular {chem} protein under the recorded48 h LPS/IFNG/IL2 culture condition',rationale='Direct supernatant protein measurement supports extracellular presence only; it does not estimate induction or a single-ligand target effect.')
c14=cohort(14,'XCH_S008','Human donor blood buffy-coat PBL; Swiss Central Laboratory Blood Transfusion Service SRK','peripheral blood-derived lymphocytes','peripheral blood lymphocyte','Fresh or cultured10 d with IL2','unavailable','CXCL10 migration dose-response; fresh versus10 d IL2 culture',samples='Triplicate technical wells; unique donors and experiments unavailable',notes='Figure4 PBL assay family. Fresh and cultured conditions share a study group, with exact donor matching unavailable. Culture RPMI1640 with5% human serum and400 U/mL IL2; these are not purified single T-cell subsets. Other receptor-transfectant assays are excluded.')
for i,fresh in [(25,False),(26,True)]:
    state='Freshly isolated donor-buffy-coat PBL' if fresh else 'Donor-buffy-coat PBL cultured10 d with400 U/mL IL2'
    a=assertion(i,'CXCL10',c14,'XCH_S008','human peripheral blood lymphocyte chemotaxis','induces_chemotaxis','No CXCL10 migration response was observed in freshly isolated PBL in this assay.' if fresh else 'CXCL10 induced chemotaxis of human PBL after10 d culture with IL2.','Loetscher1996 Methods Chemotaxis printedp964 lines97–106; Figure4 and Results printedp967 lines314–317,348–353; XCH_S008_Loetscher1996_selected_primary.json.',direction='null' if fresh else 'increase',reviewed=True,cell_state=state,stimulation='CXCL10/IP10 concentration series',dose='CXCL10 migration concentration series; graph values not digitized; IL2 400 U/mL for cultured arm only',duration='60 min migration; no pre-culture' if fresh else '10 d IL2 culture followed by60 min migration',time_point='60 min migration endpoint',assay='48-well NeuroProbe chambers;3 μm membrane;100,000 PBL/upper well;60 min37°C;5 fields counted;triplicate technical wells; no-chemoattractant control',treatment_status='Ex vivo fresh preparation' if fresh else '10 d ex vivo IL2 culture; donor medication unavailable',contradiction_group='XCH_CXCL10_PBL_PREPARATION',causal_directness='Direct ligand perturbation and migration endpoint; primary-PBL receptor blockade not performed in this experiment.',limitations='No unique donor count, donor matching, subset-resolved response, numerical effect estimate or precision extracted. Fresh-preparation nonresponse is not equivalence or a universal resting-cell property. Figure3 receptor RNA and receptor-transfectant experiments cannot establish surface abundance or receptor dependence in these PBL.')
    a['scoring_annotation']['tested_hypothesis']='CXCL10 increases human PBL chemotaxis in the recorded cell-preparation context'

# Record all actual follow-up appearances; earlier provisional decisions remain history.
for qi,fn in [(16,'followup_search11.json'),(17,'followup_search12.json'),(18,'followup_search13.json')]:
    d=json.loads((OUT/'snapshots'/fn).read_text());qid=f'XCH_Q{qi:03}'
    p['searches'].append(dict(search_id=qid,lane='chemokine_expansion',query=json.dumps(d['queries']),database='public web primary-source search',searched_at=d['retrieved_at']['current_time'],result_source_ids=[],screening_notes='Actual ranked candidate appearances; not exhaustive. Follow-up direct retrieval rows distinguish successful full methods from provisional candidates.',snapshot_path=snap(fn)))
    for title,url in re.findall(r'^(.+?) \((https?://[^\n]+)\)$',d['result'],re.M):
        z=urlsplit(url);url=urlunsplit((z.scheme,z.netloc,z.path,'',''));s=s10 if 'PMC3422223' in url else None
        decision='include' if s else 'await_full_text' if any(x in url for x in ['PMC2191042','7684437','50415','PMC7669268']) else 'exclude'
        reason='Primary PBMC source assay recovered separately; no primary-human recipient claim from transfectants.' if s else 'Primary migration candidate; complete Methods not yet inspected.' if decision=='await_full_text' else 'Peripheral, background or unmatched candidate; no evidence imported.'
        u['screening'].append(dict(candidate_id=f'XCH_CAN{len(u["screening"])+1:03}',query_id=qid,title=title,url=url,doi=s['doi'] if s else NA,pmid=s['pmid'] if s else NA,decision=decision,reason=reason))
        if s:p['searches'][-1]['result_source_ids'].append(s['source_id'])
    p['searches'][-1]['result_source_ids']=sorted(set(p['searches'][-1]['result_source_ids']))
for qi,s in [(19,s10),(20,s8)]:
    qid=f'XCH_Q{qi:03}'
    p['searches'].append(dict(search_id=qid,lane='chemokine_expansion',query='Direct retrieval and full-method inspection of primary candidate: '+s['url'],database='PMC through Chrome' if qi==19 else 'Primary published PDF mirror; independent follow-up query log in snapshot',searched_at=s['retrieved_at'],result_source_ids=[s['source_id']],screening_notes='Successful primary Methods/Results retrieval; same study, not independent replication. Loetscher underlying actual query log retained in exact source snapshot.',snapshot_path=s['snapshot_path']))
    u['screening'].append(dict(candidate_id=f'XCH_CAN{len(u["screening"])+1:03}',query_id=qid,title=s['title'],url=s['url'],doi=s['doi'],pmid=s['pmid'],decision='include',reason='Relevant full primary Methods/Results inspected with human-primary and transfected-host contexts separated.'))
for g in p['gaps']:
    if g['status']=='partial_source_secretion_coverage':g['description']='Human macrophage CCL22 and mixed-PBMC CCL3/CCL4 extracellular protein now directly measured. CCL3/4 producing subsets and induction relative to unstimulated culture remain unresolved; other assigned ligands lack extracted secretion assays.'
    if g['status']=='preparation_context_gap':g['description']='Historical Taub1993 activation and Taub1995 purification assertions remain provisional because complete methods are unrecovered. New independent ScalleyKim2012 human-PBMC CCL3/4 protein measurements close reviewed ligand coverage, but do not replace those migration or preparation propositions.'
    if g['status']=='bounded_access':g['description']='Most selected methods recovered through Chrome or primary PDF. Historical Taub1993/1995 methods remain unrecovered. Schall1993 PDF rendered in Chrome but article text was not inspected; native-app CUA call with30-second timeout stalled and was interrupted after485 seconds. No assertion was upgraded from a failed or uninspected retrieval.'
    if g['status']=='remaining_bridge_gap':g['description']+=' Loetscher1996 primary PBL migration and fresh-preparation contrast now have full methods. No primary-cell receptor blockade or numerical affinity is inferred from its transfectants or failed binding assay.'
p['gaps'].append(dict(entity='CCL3; CCL4',status='alternate_migration_candidate_uninspected',description='Schall1993 PMID7684437 and eLife2020 PMC7669268 remain screened alternatives. Schall primary PDF is accessible in Chrome, but no complete method extraction was made; no assay assertion imported.'))
p['synthesis']='Twenty-six narrow assertions cover all eight assigned chemokines;20 have inspected full Methods/Results, while6 historical Taub migration/preparation assertions retain needs_full_text. Direct CCL3/CCL4 extracellular protein in stimulated mixed human PBMC and CXCL10 cultured-versus-fresh human PBL chemotaxis are now added. Secretion does not establish induction or target signaling; receptor-transfectant hosts, primary cells and technical replicates remain distinct. No complete pathway, calibrated probability or human adjudication is claimed.'
write('pack.json',p);write('screening.json',u['screening'])
r=json.loads((OUT/'run.json').read_text());r.update(timestamp_end=END,retrieval_queries=[q['query'] for q in p['searches']],retrieval_dates=[q['searched_at'] for q in p['searches']],source_versions={s['source_id']:s['version'] for s in p['sources']},output_hash=hashlib.sha256((OUT/'pack.json').read_bytes()).hexdigest(),followup='Reproduce with finalize_pack.py; includes upgrade_pack.py plus saved ScalleyKim/Loetscher primary-method additions. All old provisional records and original reviews remain preserved.',critic_run_ids=['XCH-REVIEW-20260913-01','XCH-RECHECK-20260913-01'])
r['source_hashes']={s['snapshot_path']:hashlib.sha256((ROOT/s['snapshot_path']).read_bytes()).hexdigest() for s in p['sources']}
r['source_hashes'].update({str(f.relative_to(ROOT)):hashlib.sha256(f.read_bytes()).hexdigest() for f in (OUT/'snapshots').iterdir() if f.is_file()})
write('run.json',r)
assert len(p['assertions'])==26
assert sum(a['qc_status']=='reviewed_extraction' for a in p['assertions'])==20
assert all(c['query_id'] in {q['search_id'] for q in p['searches']} for c in u['screening'])
print(json.dumps({'sources':len(p['sources']),'cohorts':len(p['cohorts']),'assertions':len(p['assertions']),'reviewed':20,'screening_candidates':len(u['screening']),'hash':r['output_hash']}))
