import json
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parent
B='research/mechanisms_antigen/'
p=json.loads((R/'pack.json').read_text()); aa={x['assertion_id']:x for x in p['assertions']};ss={x['source_id']:x for x in p['sources']};cc={x['cohort_id']:x for x in p['cohorts']}
U='unavailable'
bridges=[]
def ctx(a):
    c=cc[a['cohort_id']]
    return dict(species=a['species'],source_cell_taxon=a['source_cell_taxon'],recipient_cell_taxon=a['recipient_cell_taxon'],biological_preparation=c['cell_type'],cell_identity_state=a['cell_type']+'; '+a['cell_state'],tissue=a['tissue'],stimulation=a['stimulation'],dose=a['dose'],time=a['duration'],cohort_linkage=a['cohort_id'])
def add(n,mech,left,right,typ,relation,status,summary,mapping,temporal,link,limitations,blocked_checks=None):
    a,b=aa[f'MP_A{left:03}'],aa[f'MP_A{right:03}'];nonserial=typ in ['shared_intervention','context_contrast']
    checknames=['entity_continuity','context_compatibility','temporal_compatibility','measurement_link','experimental_linkage','mediation_test']
    default='not_applicable_nonserial' if nonserial else 'supported'
    explanations={'entity_continuity':mapping,'context_compatibility':limitations if status=='blocked_missing_evidence' else 'Compatible only at the explicitly stated within-preparation or contrast scope; no transport assumed.','temporal_compatibility':temporal,'measurement_link':summary,'experimental_linkage':link,'mediation_test':'No serial mediation asserted.' if nonserial else 'Relevant intermediate perturbation/rescue and measured endpoint support only the narrow stated dependency.'}
    checks={key:dict(status=default,explanation=explanations[key]) for key in checknames}
    for k,v in (blocked_checks or {}).items():checks[k]['status']=v
    paths=list(dict.fromkeys(a['supporting_snapshot_paths']+b['supporting_snapshot_paths']))
    bridges.append(dict(bridge_id=f'MP_B{n:03}',mechanism_id=mech,from_assertion_id=a['assertion_id'],to_assertion_id=b['assertion_id'],bridge_type=typ,bridge_relation=relation,source_ids=list(dict.fromkeys([a['source_id'],b['source_id']])),source_locators=[a['source_locator'],b['source_locator']],supporting_snapshot_paths=paths,evidence_summary=summary,entity_mapping=mapping,context_comparison=dict(from_context=ctx(a),to_context=ctx(b),comparison=limitations),temporal_basis=temporal,measurement_basis=dict(from_measurement=a['measurement'],from_assay=a['assay'],to_measurement=b['measurement'],to_assay=b['assay'],interpretation=summary),experimental_linkage=link,limitations=limitations,status=status,checks=checks,attestation_role='extractor_only_pending_independent_review'))

add(1,'MP_M001',1,3,'mediation_test','supports','candidate_pending_review','Restoring functional B2M in 1074mel supports B2M-dependent susceptibility to HLA-compatible human CTL lysis.','Intermediate is human B2M protein restored by its coding vector; Fig3 validates protein and Fig5 tests lysis. This is not a quantified surface-HLA mediation claim.','Documented scheduling: vector infection precedes CTL coculture; no matched time-course quantification of B2M protein and killing.','Same 1074mel preparation/protocol and B2M-versus-control vector; immunoblot and lysis are distinct assays. Exact aliquot linkage unavailable.','Human melanoma target; human allogeneic expanded CD8 recipient. Single compatible tumor line; viral-vector rescue could affect additional variables. No claim of peptide identity, direct binding or exclusive HLA-surface mediation.')
add(2,'MP_M001',2,3,'shared_intervention','supports','candidate_pending_review','B2M rescue changes surface HLA and CTL lysis as a branched response.','W6/32-positive class-I abundance is distinct from a defined peptide-HLA complex and from human CTL killing.','Vector precedes both measurements; ordering between measured surface abundance and lysis is not demonstrated.','1074mel is the shared subset of the surface panel and human CTL experiment; matched aliquots unavailable.','HLA-intermediate necessity was not independently perturbed in this experiment. Do not relabel this profile as surface HLA causing killing.')
add(3,'MP_M001',3,4,'context_contrast','opposes','candidate_pending_review','HLA-mismatched 1259mel remains near background despite B2M restoration, limiting a universal rescue-to-killing claim.','Same B2M intervention and human antimelanoma effector restriction; different tumor HLA backgrounds.','Matched Fig5 assay schedule; not a serial transition.','Same Fig5 experiment, different target lines; no autologous comparison.','Negative graph control is qualitative; target antigens and other line-specific differences are not fully matched.')
add(4,'MP_M001',3,5,'context_contrast','inconclusive','candidate_pending_review','Mouse vaccinia recognition provides a different antigen-processing context, not independent human-recipient replication.','Human HLA-A2.1/human CTL differs from mouse H-2Kd/mouse CTL despite common B2M rescue.','Both use vector-before-coculture schedules; not temporal pathway evidence.','Overlapping human tumor lines but separate effector preparations and MHC restriction.','Recipient taxon, MHC molecule and antigen differ. H82 non-rescue limits sufficiency of B2M across targets.')
add(5,'MP_M002',6,7,'context_contrast','supports','candidate_pending_review','TAP1-specific, not TAP2, complementation supports the TND-3 surface-HLA defect being attributable to TAP1.','Different transporter subunits are experimentally contrasted, not treated as identical proteins.','Overnight vector infection before flow measurement.','Same TND-3 EBV-B-cell system and figure; no primary B-cell preparation.','Surface rescue only; no downstream antigen-specific T-cell endpoint in this complementation experiment.')
add(6,'MP_M003',8,9,'serial_transition','inconclusive','blocked_missing_evidence','The variant-to-splicing observation cannot yet form a measured transcript-to-TAP2-protein-to-HLA pathway.','Observed aberrant TAP2 cDNA is not the same molecular state as introduced wild-type TAP2; mutant protein abundance/function was not directly measured.','Patient genotype/cDNA observation and complementation are separate experiments; protein ordering is unmeasured.','Same HA-L line, different assays and intervention states.','Whole-gene rescue does not establish a measured translation bridge or isolate the causal nucleotide.',{'entity_continuity':'not_demonstrated','context_compatibility':'supported','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'supported','mediation_test':'not_demonstrated'})
add(7,'MP_M003',9,11,'context_contrast','opposes','candidate_pending_review','Residual autologous CTL lysis occurs in uncomplemented HA-L, so low surface class I does not imply absent antigen recognition.','Surface-HLA restoration and selected EBV-directed lysis are distinct endpoints and intervention states.','No before/after complementation CTL test.','Same patient-2 EBV-B line; CTL is autologous but measured without rescue.','One patient and expanded CTL specificity; antigen identity tested separately using nonhuman COS targets. No general antiviral-protection claim.')
add(8,'MP_M004',13,14,'shared_intervention','supports','candidate_pending_review','LPS lowers CIITA RNA and protein; the observations remain separate molecular layers.','CIITA type-I/type-III RNA and 121/124/132-kDa proteins are not one-to-one abundance proxies.','RNA time course precedes terminal protein assay on documented schedule; relative translation/turnover unmeasured.','Same human monocyte-derived DC protocol; cross-assay donor identity unavailable.','No precise isoform translation bridge or antigen-specific human CD4 endpoint.')
add(9,'MP_M004',15,16,'shared_intervention','opposes','candidate_pending_review','Maturing human DCs show reduced DRA RNA at 24 h alongside increased surface HLA-DR.','HLA-DRA RNA is distinct from assembled HLA-DR surface protein.','Both include 24-h LPS treatment; early 3-h RNA increase also retained.','Same culture protocol; different flow/RNA experiments, donor overlap unavailable.','Contradicts using RNA direction as a surface-protein proxy. No measured T-cell function follows from surface staining.')
add(10,'MP_M005',18,19,'shared_intervention','supports','candidate_pending_review','ERAP1 knockout lowers HLA-C-enriched surface staining and mouse reporter stimulation as parallel outcomes.','DT-9-reactive surface protein is distinct from antigen-specific peptide occupancy or mouse NFAT reporter function.','KO precedes both assays; no matched surface-peptide time course.','Shared WM793/WM278 clone systems and reporter protocol; aliquot pairing unavailable.','Surface abundance is not proven to mediate reporter loss; DT-9 specificity and mouse-recipient limits retained.')
add(11,'MP_M005',19,20,'mediation_test','supports','candidate_pending_review','ERAP1 reconstitution after knockout supports an ERAP1-dependent reporter-stimulation mechanism within WM793.','Human ERAP1 is removed then restored as Hap2/Hap10; human TCR specificity and mouse recipient host remain the same.','Documented schedule: reconstitution 24 h before reporter addition, then 24 h coculture.','WM793 subset of KO experiment; two independently isolated KO clones with both reconstitution constructs. Same TCR lineage, not independent patient specificities.','Narrow ERAP1-dependence only. Does not prove exclusive HLA-abundance mediation, exact presented peptide length, physiological allotype dosage or primary human-CD8 function.')
add(12,'MP_M005',21,22,'serial_transition','inconclusive','blocked_missing_evidence','Biochemical trimming supports plausibility but cannot be equated to direct delivery of the measured digest products into the reporter experiment.','HPLC pools unresolved 9mer/8mer products; cellular assay expresses precursors with uncertain N-terminal methionine processing.','Cell-free reaction and separate cellular transfection/coculture schedules; no product-transfer test.','Separate cell-free reaction versus engineered HEK293T plus mouse reporter.','No same-species/state peptide transfer, absolute peptide-HLA quantification or cell-context equivalence.',{'entity_continuity':'not_demonstrated','context_compatibility':'not_demonstrated','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'not_demonstrated','mediation_test':'not_applicable_nonserial'})
add(13,'MP_M006',23,24,'context_contrast','opposes','candidate_pending_review','B2M knockout lowers TCR1 activation but preserves TCR22 activation, limiting class-I-generalized claims.','Different patient-derived TCR specificities; same human Jurkat host design and matched-TMG APC framework.','Same 20–24 h coculture framework.','MEL9 B-cell/TCR experiment, supplemental Fig4i with two biological replicates; distinct antigen/TCR pairs.','Immortalized human cells, engineered murine TCR constant domains, no primary effector function or surface-class-I mediation claim.')
add(14,'MP_M006',24,25,'context_contrast','supports','candidate_pending_review','TCR22 remains active under B2M knockout but is inhibited by HLA-II blockade, supporting class-II restriction.','Same TCR22 and cognate-TMG response; different class-I versus class-II interventions.','Same assay schedule; not a serial transition.','Within supplemental Fig4i framework; exact aliquot mapping not provided.','Restricting class supported; no precise HLA-II allele/ligand quantity or clinical response inferred.')
add(15,'MP_M007',26,27,'mediation_test','supports','candidate_pending_review','Depletion and autologous add-back support B-cell contribution to bulk spontaneous PBMC proliferation.','Intermediate is the autologous B-cell population itself; the same bulk DNA-incorporation endpoint is measured under removal and restoration.','B-cell fraction manipulations precede five-day culture; day4 thymidine pulse precedes harvest.','Fig3B paired individual-donor comparisons in seven psoriasis samples; technical triplicate wells.','This is a B-cell-dependence mechanism for bulk PBMC proliferation. It does not establish antigen identity, B-cell-specific HLA mechanism or CD8-specific response.')
add(16,'MP_M007',27,28,'mediation_test','inconclusive','blocked_missing_evidence','Bulk class-I blockade is insufficient to assign the B-cell add-back effect specifically to B-cell HLA-I.','W6/32 targets HLA-I on multiple cell types, not specifically the re-added B-cell intermediate.','Five-day thymidine protocol and day4 BrdU protocol differ.','Exact donor overlap and paired aliquots between Fig3B and 3D unavailable.','B-cell-specific HLA perturbation and matching donor readouts needed.',{'entity_continuity':'not_demonstrated','context_compatibility':'not_demonstrated','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'not_demonstrated','mediation_test':'not_demonstrated'})
add(17,'MP_M007',26,29,'serial_transition','inconclusive','blocked_missing_evidence','B-depletion-associated bulk proliferation loss cannot be assigned directly to the separately measured CD8 CFSE response.','Bulk thymidine incorporation and CD8-specific division are different endpoint species/populations.','Both use five-day culture but no within-sample ordered transition.','Seven-plus-seven versus 17-plus-9 cohorts; donor overlap unavailable.','No CD8-resolved readout under the same B-cell manipulation; no antigen specificity.',{'entity_continuity':'not_demonstrated','context_compatibility':'not_demonstrated','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'not_demonstrated','mediation_test':'not_applicable_nonserial'})
add(18,'MP_M008',30,29,'serial_transition','inconclusive','blocked_missing_evidence','Antigen-specific mouse reporter stimulation by tonsillar B cells cannot be joined to the primary-human blood CD8 proliferation observation.','Mouse NFAT reporter bearing a selected human TCR is not the endogenous human CD8 repertoire.','24-h reporter versus five-day PBMC assay; no transfer or sequential recruitment experiment.','Tonsils from three patients versus blood cohort 17 plus 9; overlap unavailable; TCR lineage reused.','Species, tissue, cell state, time and specificity mismatch block transport.',{'entity_continuity':'not_demonstrated','context_compatibility':'contradictory','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'not_demonstrated','mediation_test':'not_applicable_nonserial'})
add(19,'MP_M008',21,31,'context_contrast','opposes','candidate_pending_review','ADAMTSL5 biochemical/target-cell evidence cannot imply its presentation by the four B-cell lines where the peptide was not detected.','Same named autoantigen, distinct biochemical substrate versus ligand-recovery readouts.','Separate studies and experiments; no temporal connection.','Reused psoriatic TCR lineage across research program but different target preparations; no independent peptide-specific human cohort replication.','Nondetection has sensitivity limits. Cell-line identifiers/FDR-file inconsistencies unresolved; no absence claim.')

out=dict(schema_version='0.3.0',role='extractor_connection_proposals_pending_review',bridges=bridges,summary=dict(total=len(bridges),candidate_pending_review=sum(x['status']=='candidate_pending_review' for x in bridges),blocked_missing_evidence=sum(x['status']=='blocked_missing_evidence' for x in bridges),note='No complete serial pathway asserted. Nonserial profiles are not mediation. Checks are extractor attestations only.'))
(R/'bridges.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')

candidates=[]
def cand(n,q,title,url,decision,reason,source=None,doi=U,pmid=U,unique=None):
    if source:
        s=ss[source];title=s['title'];url=s['url'];doi=s['doi'];pmid=s['pmid']
    candidates.append(dict(candidate_id=f'MP_SC{n:03}',appearance_id=f'MP_AP{n:03}',unique_paper_id=unique or source or f'MP_UP{n:03}',query_id=q,title=title,url=url,doi=doi,pmid=pmid,decision=decision,reason=reason,source_id=source or U,query_attribution='For multiquery batches, exact member-query rank attribution unavailable; batch and actual queries preserved in pack.json.'))
cand(1,'MP_Q001','', '', 'include','B2M protein/surface rescue and human HLA-compatible CTL lysis; full Methods/Results plus Fig5 image inspected.',source='MP_S001')
cand(2,'MP_Q002','', '', 'include','Human TAP2 splice defect, surface complementation and residual autologous EBV CTL response; context-dependent contrary evidence.',source='MP_S003')
cand(3,'MP_Q003','ERAP1 Allotypes 2 and 10 Differentially Regulate the Immunopeptidome of Melanocytes','https://pubmed.ncbi.nlm.nih.gov/41130749/','await_full_text','Recent immunopeptidome anchor surfaced; abstract/search only in this run. No assertion extracted.',pmid='41130749')
cand(4,'MP_Q001','Natural killer cell lines kill autologous beta2-microglobulin-deficient melanoma cells: implications for cancer immunotherapy','https://pubmed.ncbi.nlm.nih.gov/9371813/','exclude','NK-effector complement beyond this bounded antigen-specific T-cell lane; likely shared melanoma lines, not independent replication by title alone.',doi='10.1073/pnas.94.24.13140',pmid='9371813')
cand(5,'MP_Q001','beta2-Microglobulin mutations, HLA class I antigen loss, and tumor progression in melanoma','https://pmc.ncbi.nlm.nih.gov/articles/PMC508863/','await_full_text','PMC web access challenged; not pursued after stronger gene-restoration full text recovered. No assertion extracted.')
cand(6,'MP_Q005','', '', 'include','KO, allotype rescue, biochemical trimming and reporter specificity; mouse recipient preserved.',source='MP_S005')
cand(7,'MP_Q005','Melanocyte antigen triggers autoimmunity in human psoriasis','https://pmc.ncbi.nlm.nih.gov/articles/PMC4689169/','await_full_text','Original TCR/autoantigen discovery appeared in citation chain. Search excerpts only; treated as provenance/reuse lead, not independent extracted evidence.')
cand(8,'MP_Q004','', '', 'include','Primary-human-monocyte-derived DC RNA/protein/surface contrast; no inferred CD4 functional endpoint.',source='MP_S004')
cand(9,'MP_Q011','', '', 'include','Recent primary B-cell and PBMC perturbations plus distinct ligand/reporter experiments; seven-plus-seven versus 17-plus-9 cohorts separated.',source='MP_S007')
cand(10,'MP_Q008','', '', 'include','Human B-cell/Jurkat host antigen-specific perturbation controls; supplemental Fig4i visually checked.',source='MP_S006')
cand(11,'MP_Q010','', '', 'include','Citation-chained TAP1-specific rescue; transformed human B cells distinguished from separate fibroblast source.',source='MP_S002')
cand(12,'MP_Q005','Current knowledge on autoantigens and autoantibodies in psoriasis','https://onlinelibrary.wiley.com/doi/full/10.1111/sji.12945','exclude','Review/discovery only; not primary biological evidence.',doi='10.1111/sji.12945',pmid='32697368')
cand(13,'MP_Q012','Critical role of the tumor suppressor TSC1 for dendritic cell to activate CD4 T cells by promoting MHC class II expression via IRF4 and CIITA','https://pmc.ncbi.nlm.nih.gov/articles/PMC3702379/','exclude','Distinct predominantly mouse perturbation lane; no human source/recipient mechanism inferred from search excerpt.')
cand(14,'MP_Q021','Review Reports - B Cells Can Trigger the T-Cell-Mediated Autoimmune Response Against Melanocytes in Psoriasis','https://www.mdpi.com/2073-4409/14/24/2002/review_report','exclude','Publisher review reports surfaced in correction search; not biological primary evidence and not an independent review initiated by this run.')
cand(15,'MP_Q012','Extensive remodeling of DC function by rapid maturation-induced transcriptional silencing','https://pmc.ncbi.nlm.nih.gov/articles/PMC4150779/','await_full_text','Citation/forward-search lead for CIITA chromatin mechanism. No assertion extracted.')
cand(16,'MP_Q014','', '', 'include','Repeated appearance of already selected primary paper; same DOI and cohort, not additional evidence.',source='MP_S001')
cand(17,'MP_Q013','', '', 'include','Repeated appearance of same selected paper; deduplicated by DOI/PMID.',source='MP_S003')
cand(18,'MP_Q012','', '', 'include','Repeated appearance of same selected paper; deduplicated by DOI/PMID.',source='MP_S004')
screen=dict(scope='Bounded ranked-search mechanism pilot, not exhaustive systematic retrieval',screened_at='2026-09-13',candidates=candidates,counts=dict(candidate_appearances=len(candidates),unique_papers=len(set(x['unique_paper_id'] for x in candidates)),selected_unique_primary_papers=len(ss),note='Counts cover the explicitly registered candidates, not every result returned by ranked search. Included repeat appearances do not add independent studies.'),citation_chains=[dict(from_source='search result for Asymptomatic deficiency/TAP/Villard (review citation)',to_source='MP_S002',action='opened primary JCI article; extracted Methods/Results'),dict(from_source='MP_S002 references',to_title='Human peptide transporter deficiency. Importance of HLA-B in the presentation of TAP-independent EBV antigens (1997)',action='future full-text lead; not extracted'),dict(from_source='MP_S004 references',to_title='Inflammatory stimuli induce accumulation of MHC class II complexes on dendritic cells (Cella1997)',action='future full-text functional bridge lead; not extracted'),dict(from_source='MP_S005; MP_S007',to_title='Melanocyte antigen triggers autoimmunity in human psoriasis (2015)',action='same original TCR specificity reused; no independent TCR discovery count')],correction_retraction_checks=[dict(source_id=s['source_id'],checked_at='2026-09-13',query_id=f'MP_Q{15+i:03}',methods='DOI plus correction/erratum/retraction ranked search; downloaded article header/notices/version area; text token scan',outcome='No relevant notice identified in inspected material; bounded check, absence not certified.',snapshot_paths=[B+'snapshots/'+('MP_correction_search1.json' if i<4 else 'MP_correction_search2.json'),s['snapshot_path']]) for i,s in enumerate(p['sources'])],cohort_reuse_checks=[dict(group='MP_REUSE001',source_ids=['MP_S002','MP_S003'],finding='ST-EMO is the same previously described TAP2-deficient EBV-B control in both studies; no independent replication count.',status='known_reuse'),dict(group='MP_REUSE002',source_ids=['MP_S005','MP_S007'],finding='Same Vα3S1/Vβ13S1 TCR lineage and shared target lines such as WM278; no independent patient receptor replication.',status='known_reuse'),dict(group='MP_REUSE003',source_ids=['MP_S007'],finding='Tonsil samples previously described in cited study[23]; seven-plus-seven and17-plus9 blood-cohort overlap unresolved.',status='partly_resolved'),dict(group='MP_REUSE004',source_ids=list(ss),finding='Exact DOI/PMID/title-term scan of existing research pack.json files found no selected-paper match; this is not a whole-project donor-registry adjudication.',status='unresolved')],failed_access_paths=['PMC browser challenges in web open','EuropePMC403/unsafe web fetch','initial sandbox DNS failure; approved direct primary download succeeded'],remaining_full_text_candidates=[x['candidate_id'] for x in candidates if x['decision']=='await_full_text'])
(R/'screening.json').write_text(json.dumps(screen,ensure_ascii=False,indent=2)+'\n')
run=json.loads((R/'run.json').read_text());run['timestamp_end']=datetime.now(timezone.utc).isoformat();run['output_files']=['pack.json','screening.json','bridges.json','notes.md','run.json'];run['supplement_checks']='Kuilman supplementary Fig4i and6l rendered with bundled Poppler; Fig4i used for extraction. Restifo Fig5 image visually inspected.';(R/'run.json').write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(out['summary']))
