import json
from pathlib import Path
from datetime import datetime,timezone
D=Path('research/mechanisms_activation');p=json.loads((D/'pack.json').read_text());A={x['assertion_id']:x for x in p['assertions']};now=datetime.now(timezone.utc).isoformat()
A['MA-A02']['measurement']='chromatin_accessibility'
A['MA-A02']['limitations']='Dominant-negative sequestration affects JUN partners broadly; not single-FOS specificity. chromatin_accessibility is an explicit extension to the old measurement enum. No gene-specific enhancer deletion or functional rescue.'
# A12 uses pooled-screen discovery as the immediately grounded experiment.
A['MA-A12'].update(cohort_id='MA-CO04',dose='10 ng/mL IL12 with600 IU/mL IL2',duration='48 h after editing then72 h cytokine; final4.5 h PMA/ionomycin/brefeldin',time_point='After72 h cytokine',assay='Pooled CRISPR indel enrichment in IFNG-high/low fractions; supporting arrayed multi-gRNA comparison',uncertainty='Pooled4 donors; separate arrayed2-donor follow-up',limitations='Pooled edited-allele enrichment is the narrow direct readout; arrayed validation uses additional donors. Intracellular cytokine is not secretion. No TBX21 rescue or direct-binding assay.')
def context(x):return {k:x.get(k,'unavailable') for k in ['species','cell_type','cell_state','tissue','stimulation','dose','duration','time_point','cohort_id']}
B=[]
def bridge(i,m,l,r,typ,rel,summary,mapping,time,measurement,linkage,limits,status='candidate_pending_review',checks=None):
 left=A[f'MA-A{l:02}'];right=A[f'MA-A{r:02}'];non=typ in ['shared_intervention','context_contrast']
 b=dict(bridge_id=f'MA-B{i:02}',mechanism_id=f'MA-M{m:02}',from_assertion_id=left['assertion_id'],to_assertion_id=right['assertion_id'],bridge_type=typ,bridge_relation=rel,source_ids=list(dict.fromkeys([left['source_id'],right['source_id']])),source_locators=[left['source_locator'],right['source_locator']],supporting_snapshot_paths=list(dict.fromkeys(left['supporting_snapshot_paths']+right['supporting_snapshot_paths'])),evidence_summary=summary,entity_mapping=mapping,context_comparison={'left':context(left),'right':context(right),'biological_preparation_left':left['cell_type'],'biological_preparation_right':right['cell_type'],'cohort_linkage':linkage,'transportability':'No equivalence beyond the explicitly compared preparations; overlapping donor identity is unavailable unless stated.'},temporal_basis=time,measurement_basis=measurement,experimental_linkage=linkage,limitations=limits,status=status,checks=checks or {'entity_continuity':'not_applicable_nonserial' if non else 'supported','context_compatibility':'supported','temporal_compatibility':'supported','measurement_link':'not_applicable_nonserial' if non else 'supported','experimental_linkage':'supported','mediation_test':'not_applicable_nonserial' if non else 'supported'},check_role='Extractor attestations; independent and human review pending')
 B.append(b)
bridge(1,1,1,2,'mediation_test','supports','CD28 withdrawal reduces nuclear AP-1; perturbing AP-1 with A-FOS reduces activation-induced chromatin opening. This supports an AP-1 requirement within CD3/CD28 activation, without identifying a natural indirect-effect fraction.','Intermediate is the AP-1 FOS/JUN protein family; A-FOS perturbs JUN-partner DNA-binding capacity. Nuclear abundance and complex activity are distinct measured/perturbed aspects, not identical observations.','CD28 contrast begins at activation; A-FOS precedes activation by2h; chromatin sampled5h later. Scheduling documented; no time-resolved AP-1→ATAC lag measured.','Nuclear immunoblot plus relevant protein intermediate perturbation and ATAC endpoint; not RNA→protein inference.','Same primary naive-cell preparation/protocol and paper; total3 donors; exact overlap across experiments unavailable.','No rescue of CD28 omission by AP-1, broad dominant-negative effects, and other CD28 signaling branches remain possible.')
bridge(2,1,2,3,'shared_intervention','supports','AP-1 inhibition produces chromatin and RNA branches. Co-occurrence does not prove that a measured accessibility change caused a particular RNA change.','Shared A-FOS treatment; G-layer accessibility and T-layer RNA remain separate endpoints.','Both sampled after5h activation following2h electroporation recovery; no measured serial order.','ATAC-seq and RNA-seq are distinct endpoint assays under the same perturbation.','Same source/protocol,3 donors total; exact matched aliquot and donor overlap unavailable.','Cannot infer secretion, protein abundance, or functional anergy from the RNA/chromatin profile.')
bridge(3,1,1,5,'context_contrast','opposes','Under CD28 omission nuclear AP-1 falls strongly while most NFAT1 binding remains detectable. This opposes treating NFAT1 presence as sufficient for chromatin opening in this context.','AP-1 nuclear protein and NFAT1 DNA occupancy are distinct TF measurements; no serial mapping.','Documented activation contrasts; exact NFAT/nuclear sampling-time identity unavailable.','Nuclear Western blot versus ChIP-seq; comparison does not test NFAT knockout.','Same naive-cell source protocol; figure-specific donor overlap unavailable.','IL2 locus is an exception to retained NFAT binding; no universal NFAT dispensability claim.',checks={'entity_continuity':'not_applicable_nonserial','context_compatibility':'supported','temporal_compatibility':'not_demonstrated','measurement_link':'not_applicable_nonserial','experimental_linkage':'supported','mediation_test':'not_applicable_nonserial'})
bridge(4,2,6,7,'shared_intervention','supports','STAT5B depletion reduces both FOXP3 RNA and protein, a transcriptional/protein response profile.','Same gene perturbation; FOXP3 RNA and FOXP3 protein remain different molecular layers.','RNA24/72h and protein72h; documented sampling supports response profile, not translation kinetics.','qPCR and flow; no pulse-labeling/translation or isoform-specific bridge.','Healthy primary CD4 protocol shared; differing sample counts and donor/aliquot overlap unavailable.','No rescue and no measured suppression in the knockdown preparation.')
bridge(5,2,6,8,'context_contrast','supports','STAT5B and STAT5A depletion produce differing FOXP3 RNA responses in the tested preparation.','Paralogs are distinct genes, not interchangeable STAT5 observations.','Matched24/72h schedule.','Same qPCR endpoint with paralog-specific siRNA conditions.','Same healthy-cell protocol; exact pairing unavailable.','Partial knockdown and small groups; STAT5A null is not equivalence or proof of global dispensability.')
bridge(6,2,7,9,'serial_transition','inconclusive','A proposed STAT5B→FOXP3→suppression connection is blocked: knockdown protein data and patient correlation do not demonstrate FOXP3 mediation of function.','Left is FOXP3 protein after siRNA; right is cross-person FOXP3-positive fraction correlated with function. Neither identical molecular state nor experimental causal transfer is shown.','72h siRNA endpoint versus disease-cohort ex vivo assay; serial time order unavailable.','Flow abundance/frequency differ; downstream is thymidine incorporation; no FOXP3 rescue/depletion in the STAT5B-deficient functional experiment.','Different healthy and patient cohorts; earlier patient-publication overlap unresolved.','Genotype, disease and alternative STAT5 targets confound transport.',status='blocked_missing_evidence',checks={'entity_continuity':'not_demonstrated','context_compatibility':'not_demonstrated','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'not_demonstrated','mediation_test':'not_demonstrated'})
bridge(7,3,13,12,'mediation_test','supports','IL12-associated intracellular IFNG induction is sensitive to TBX21 perturbation in expanded primary human Tregs. This is conditional TBX21 dependence, not a demonstrated IL12→TBX21 induction edge.','Intermediate TBX21/T-bet is directly targeted by CRISPR. Downstream IFNG is intracellular protein accumulation in both assays; no secretion is inferred.','Editing precedes72h IL12 exposure and terminal intracellular cytokine assay. Experimental scheduling documented, no measured TBX21 induction trajectory.','IL12 perturbation/flow plus targeted TBX21 indel enrichment in IFNG-low fraction with separate arrayed validation.','Same pooled-screen preparation and donor cohort for primary discovery; arrayed2-donor follow-up is separate. No single-cell lineage matching assumed.','Pooled-screen enrichment, incomplete editing, no TBX21 rescue, and cytokine-restimulation context limit the claim to a required regulator of the assayed response.')
bridge(8,4,10,11,'shared_intervention','supports','FOXP3 knockout changes RNA programs and intracellular cytokine proteins across the study, preserved as a branched regulatory profile.','FOXP3 perturbation is shared; IL2/IFNG protein and a multi-gene RNA program are not treated as matched species or direct translation.','RNA and flow terminal activation differ; no ordered transition established.','Arrayed flow and scRNA-seq read distinct layers; external ChIP enrichment not a direct gene-specific binding result here.','Arrayed donor pair and scRNA donor pair overlap unavailable; scRNA preactivation48h versus prolonged expansion in arrayed screen.','Preparation mismatch and2-donor size preclude a serial RNA→protein/function claim.',checks={'entity_continuity':'not_applicable_nonserial','context_compatibility':'not_demonstrated','temporal_compatibility':'not_demonstrated','measurement_link':'not_applicable_nonserial','experimental_linkage':'supported','mediation_test':'not_applicable_nonserial'})
bridge(9,5,14,15,'shared_intervention','supports','IL2RA disruption reduces acute pSTAT5 responsiveness and later measured suppressive function; these are separate branches of the receptor perturbation.','Shared IL2RA knockout; pSTAT5 and suppression remain distinct endpoints.','15min IL2 pulse versus4-day responder coculture. Scheduling is documented but is not serial tracking of the same cells.','Phospho-flow and responder CFSE dilution.','Same expanded/edited/sorted protocol; pSTAT5n=3 and suppressionn=3–6; actual donor overlap unavailable.','IL2 consumption, cell persistence and other CD25-related effects may contribute; pSTAT5 is not established mediator of suppression.')
bridge(10,5,14,15,'mediation_test','inconclusive','The stronger hypothesis that the suppression defect is mediated by deficient STAT5 phosphorylation remains untested in these experiments.','Proposed STAT5 phosphoprotein intermediate was measured but not separately perturbed or rescued in the suppression assay.','Different15min and4-day endpoint schedules; no serial same-cell trace.','No active-STAT5 rescue or matched STAT5 perturbation with functional endpoint.','Same receptor-knockout source; assays may use different donors.','Receptor perturbation alone cannot distinguish STAT5 mediation from IL2 deprivation or survival effects.',status='blocked_missing_evidence',checks={'entity_continuity':'supported','context_compatibility':'supported','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'supported','mediation_test':'not_demonstrated'})
bridge(11,5,15,16,'shared_intervention','opposes','Suppression is impaired while FOXP3 abundance shows no detectable change, opposing use of FOXP3 protein alone as the functional endpoint.','Different F and P endpoints under shared IL2RA perturbation.','Post-edit protein assay and4-day functional coculture not the same timepoint.','Direct functional assay plus FOXP3 protein flow; null without equivalence bounds.','Same source/protocol; group counts and donor overlap differ or unavailable.','Neither unchanged FOXP3 nor its expression alone establishes preserved Treg function.')
bridge(12,6,17,18,'shared_intervention','supports','IL2 increases FOXP3 RNA at6h and protein at18h in sorted CD25bright cells.','Same FOXP3 locus but RNA and protein remain separate molecular species; no direct translation experiment.','6hRNA precedes18hprotein by assay schedule, not longitudinal same-cell tracking.','qPCR versus Western blot; both measured.','Same source preparation; RNA/protein donor matching unavailable.','Does not prove that measured RNA caused measured protein or that either caused suppression.')
bridge(13,6,17,19,'context_contrast','supports','IL2 response differs between freshly sorted CD25bright and CD25-negative human CD4 cells at6h.','Same FOXP3 RNA endpoint across cell-state strata.','Same6h exposure schedule.','qPCR direct comparison; no receptor blockade.','Same sorting protocol and paper; subset pairing explicit for proteinFig1B only, RNA pairing unavailable.','CD25 strata contain other state differences; cannot assign all difference to CD25 or transport to activated cells.')
bridge(14,7,22,23,'mediation_test','supports','The anti-CD3-associated FOXP3 protein response depends partly on endogenous IL2 activity in the PBMC culture, supported by neutralization and IL2 competition.','IL2 is the perturbed intermediate; FOXP3 intracellular protein is the common downstream endpoint. Upstream source-cell IL2 secretion is not identified.','Anti-CD3 and blockade startt=0; FOXP3 measured24h. Schedule supports intervention ordering, not a measured secretion→STAT5→FOXP3 trajectory.','Direct FOXP3 flow under CD3 activation, IL2 antibody blockade and exogenous IL2 competition.','Same PBMC protocol; Fig1 and Fig3 exact donor overlap unavailable. Four blocking experiments; no purified-cell transfer.','Neither antibody fully inhibitory alone; mixed-cell indirect effects possible. No STAT5 assay or stable Treg-function claim.')
bridge(15,7,23,24,'mediation_test','supports','Neutralization/CD25 blockade and IL2 competition strengthen the narrow IL2/CD25 dependence of FOXP3 induction; high combined blockade resists10nM IL2 rescue.','Same IL2 protein/receptor interaction perturbed by antibodies and competitive supplementation; no claim of downstream STAT5 mediation.','Blockade and ligand added atactivation; FOXP3 assay24h.','Intracellular FOXP3 with dose-dependent antibody/ligand conditions.','Same source PBMC assay; exact donor pairing across panels unavailable,4 experiments reported.','Competitive rescue is concentration dependent. High combined blocker failure is retained; a complete negative-feedback loop is not established.')
bridge(16,7,22,25,'context_contrast','opposes','FOXP3 induction in activated PBMCs does not by itself establish suppression of neighboring FOXP3-negative-cell IL2 responses.','FOXP3 protein frequency versus intracellular IL2 in a different gate; no translation or serial regulatory inference.','Initial24h activation followed by6h restimulation in separate experiment.','Both intracellular flow, not purified Treg suppression or secretion assays.','Same source PBMC culture; baseline and restimulation donors overlap unavailable.','Does not oppose all Treg suppressive activity; culture ratios, timing and activated non-Treg FOXP3 expression matter.')
bridge(17,8,21,20,'mediation_test','inconclusive','RBPJ/HDAC3 repression and RBPJ-dependent suppression are promising follow-up hypotheses, blocked until complete primary wet-lab Methods and Results are inspected.','FOXP3 expression and suppressive function remain distinct; even HDAC3-dependent FOXP3 repression would not demonstrate FOXP3 mediation of suppression.','Full intervention and endpoint timing unavailable.','Public figure captions and analytical supplement only; main wet-lab Methods/Results inaccessible.','Same paper; Fig4n=4,Fig3jn=3; donor overlap unavailable.','Source correction adds competing-interest disclosure. No claims from mouse-host GvHD transported into human in vivo.',status='blocked_missing_evidence',checks={'entity_continuity':'not_demonstrated','context_compatibility':'not_demonstrated','temporal_compatibility':'not_demonstrated','measurement_link':'not_demonstrated','experimental_linkage':'not_demonstrated','mediation_test':'not_demonstrated'})
(D/'bridges.json').write_text(json.dumps(B,indent=2,ensure_ascii=False)+'\n')
p['gaps']=[{'gap_id':'MA-G01','description':'Direct chromatin→specific RNA→secreted protein/function chain after AP-1 mediation remains absent; no serial pathway is materialized.'},{'gap_id':'MA-G02','description':'STAT5 phosphorylation→FOXP3→Treg suppression requires matched intermediate perturbation/rescue with human functional endpoints.'},{'gap_id':'MA-G03','description':'Recent2025 RBPJ/HDAC3 study: public figures and analytical supplement accessible; main wet-lab Methods/Results inaccessible on attempted primary/public routes. Retain needs_full_text.'},{'gap_id':'MA-G04','description':'Full TCR-proximal LCK/ZAP70/LAT/calcium causal extraction, tissue-resident contexts, receptor dose titration and matched donor kinetics remain to be screened.'},{'gap_id':'MA-G05','description':'Ancestry, age/sex, genotype, exact cross-figure donor linkage and measurement calibration often unavailable. Do not assume transport or replicate independence.'},{'gap_id':'MA-G06','description':'Independent scientific review and human adjudication intentionally pending user trigger; no numerical priors or release approval.'}]
(D/'pack.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
