from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
D=Path('research/mechanisms_activation');p=json.loads((D/'pack.json').read_text());date=datetime.now(timezone.utc).date().isoformat();now=datetime.now(timezone.utc).isoformat();U='unavailable'
batches=[
('MA-Q01',['human T cells CD28 AP-1 chromatin anergy'],'PubMed Entrez script',[],'Failed twice: requests dependency absent in system and bundled Python; no Entrez result set.'),
('MA-Q02',['human primary T cells CD28 AP-1 chromatin accessibility anergy CRISPR IL2 2019 2020','human T cells STAT5 FOXP3 knockdown IL-2 regulatory suppression primary study','human T cells NFAT knockdown IL-2 secretion proliferation primary cells'],'Public web ranked search',[1,2,4,5],'Broad human mechanistic discovery. Returned results aggregated across three query strings; appearances attributed to batch, not individual rank.'),
('MA-Q03',['"AP-1 activity induced by co-stimulation" full text','"Differentiating the roles of STAT5B and STAT5A" full text','"human" "AP-1" "A-FOS" "IL-2" chromatin 2019','"Functional CRISPR dissection of gene networks controlling human regulatory T cell identity"'],'Public web ranked search',[1,2,3,6],'Full-text discovery and primary citation chain; 2025 and other recent regulatory sources surfaced.'),
('MA-Q04',['"Genome-wide CRISPR screen in human T cells reveals regulators of FOXP3" PMC','"Fast and Efficient Genome Editing of Human" PMID','"AP-1 activity induced by co-stimulation" correction retraction','"Functional CRISPR dissection" correction retraction'],'Public web ranked search',[1,3,4,6],'Metadata, access, and correction screening; exact individual originating query unavailable in aggregated tool result.'),
('MA-Q05',['"Genome-wide CRISPR screen in human T cells reveals regulators of FOXP3" pubmed','"Fast and Efficient Genome Editing of Human FOXP3" pubmed','"AP-1 activity induced by co-stimulation" correction retraction','"Functional CRISPR dissection of gene networks" correction retraction'],'Public web ranked search',[1,3,4,6],'Resolved PubMed identifiers; no matching correction found for AP1/2020 Treg paper in bounded results.'),
('MA-Q06',['"s41586-025-08795-5" "Methods" "Human"','"s41586-025-08795-5" "HDAC3" "inhibitor"','"s41586-025-08795-5" "suppression" "CellTrace"','"s41586-025-08795-5" correction retraction'],'Public web ranked search',[6],'Located author correction10.1038/s41586-025-09356-6; competing-interest addition, no biological-results correction stated. Full wet-lab Methods not retrieved.'),
('MA-Q07',['"Differentiating the roles of STAT5B and STAT5A" correction retraction','"Fast and Efficient Genome Editing" correction retraction','"IL-2 regulates FOXP3 expression" correction retraction'],'Public web ranked search',[2,4,5,7],'Correction check plus additional contrary/feedback evidence discovery. No matching correction for selected older papers surfaced.'),
('MA-Q08',['"Negative Feedback Regulation of T Cells via Interleukin-2 and FOXP3 Reciprocity" correction retraction','"Fast and Efficient Genome Editing of Human FOXP3+ Regulatory T Cells" correction retraction'],'Public web ranked search',[4,7],'No matching correction surfaced;2009 conference abstract detected and excluded from independent evidence.'),
('MA-Q09',['"10.1084/jem.20182009" correction retraction','"10.1016/j.clim.2013.04.014" correction retraction','"10.1038/s41590-020-0784-4" correction retraction','"10.3389/fimmu.2021.655122" correction retraction'],'Public web ranked search',[1,2,3,4],'No matching correction/retraction notice in returned bounded set. Public source-site article notices also inspected; not exhaustive registry clearance.')]
p['searches']=[dict(search_id=i,lane='human_T_cell_activation_regulatory_mechanisms',query=qs[0],additional_queries=qs[1:],database=db,searched_at=date,result_source_ids=[f'MA-S{s:02}' for s in ss],screening_notes=notes,query_attribution='Tool returned a combined result set for the separately submitted query strings in this batch.') for i,qs,db,ss,notes in batches]
for a in p['assertions']:
 if a['direction']=='null':a['null_adequacy']='No equivalence margin or power to establish absence; preserve no-detected-effect finding only.'
p['assertions'][4]['measurement']='TF_occupancy'
(D/'pack.json').write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
S={x['source_id']:x for x in p['sources']};records=[]
def candidate(cid,q,title,url,decision,reason,doi=U,pmid=U,source=U,chain=U):
 records.append(dict(candidate_id=cid,query_id=q,title=title,url=url,doi=doi,pmid=pmid,decision=decision,reason=reason,source_id=source,unique_paper_id=doi if doi!=U else url,screened_at=date,citation_chain=chain,query_id_attribution='Batched search occurrence; exact originating subquery/rank unavailable.',correction_retraction_check='Selected source: see pack sources; other candidate: not individually cleared.'))
for i,q in [(1,'MA-Q02'),(2,'MA-Q02'),(3,'MA-Q03'),(4,'MA-Q02'),(5,'MA-Q02'),(6,'MA-Q03'),(7,'MA-Q07')]:
 s=S[f'MA-S{i:02}'];candidate(f'MA-C{i:02}',q,s['title'],s['url'],'await_full_text' if i==6 else 'include','Full primary wet-lab Methods/Results inaccessible; public captions and analytical supplement retained, with2 needs_full_text assertions.' if i==6 else 'Primary human Methods and Results inspected; narrow molecular/function extraction with context and limitations.',s['doi'],s['pmid'],s['source_id'],'S04 reference57 also points to S03; not independent evidence.' if i==3 else U)
extras=[
('MA-C08','MA-Q02','Signal transducer and activator of transcription5 (STAT5) paralog dose governs T cell effector and regulatory functions','https://pmc.ncbi.nlm.nih.gov/articles/PMC4856466/','exclude','Mouse mutant Treg experiments in surfaced primary Results; do not substitute for human STAT5 causality.','10.7554/eLife.08384'),
('MA-C09','MA-Q02','Genomic profiling of T-cell activation suggests increased sensitivity of memory T cells to CD28 costimulation','https://www.nature.com/articles/s41435-020-00118-0','await_full_text','Potential naive/memory transportability contrast; no full Methods/Results inspection in this bounded lane.','10.1038/s41435-020-00118-0'),
('MA-C10','MA-Q02','Requirement for Transcription Factor NFAT in Interleukin-2 Expression','https://pmc.ncbi.nlm.nih.gov/articles/PMC84022/','await_full_text','Jurkat and primary-cell experiments mixed in snippet; primary-cell species/preparation unresolved. No human assertion extracted.',U),
('MA-C11','MA-Q02','STAT5-signaling cytokines regulate the expression of FOXP3 in CD4+CD25+ regulatory T cells and CD4+CD25− effector T cells','https://pubmed.ncbi.nlm.nih.gov/18270368/','await_full_text','Potential primary-human FOXP3-without-suppression contrast; abstract only.','unavailable'),
('MA-C12','MA-Q02','Nonredundant roles for Stat5a/b in directly regulating Foxp3','https://pubmed.ncbi.nlm.nih.gov/17227828/','exclude','Surfaced experiments are murine thymocytes/splenocytes; outside human mechanism extraction.',U),
('MA-C13','MA-Q02','The Jak Inhibitor CP-690,550 Preserves the Function of CD4+CD25brightFoxP3+ Regulatory T Cells and Inhibits Effector T Cells','https://onlinelibrary.wiley.com/doi/full/10.1111/j.1600-6143.2010.03200.x','await_full_text','Potential contrary kinase-inhibitor/function relation; no full Methods/Results inspected.','10.1111/j.1600-6143.2010.03200.x'),
('MA-C14','MA-Q02','Antigen receptor-mediated depletion of FOXP3 in induced regulatory T-lymphocytes via PTPN2 and FOXO1','https://pmc.ncbi.nlm.nih.gov/articles/PMC4633965/','await_full_text','Strong context-dependent mechanism candidate; model/species and full Methods not resolved during this lane.','10.1038/ncomms9576'),
('MA-C15','MA-Q02','Upregulation of Foxp3 Expression in Mouse and Human Treg Is IL-2/STAT5 Dependent','https://nyaspubs.onlinelibrary.wiley.com/doi/10.1196/annals.1375.031','await_full_text','Mouse/human mixture and brief report; not extracted without full study assessment.','10.1196/annals.1375.031'),
('MA-C16','MA-Q02','Low-dose IL-2 expands CD4+ regulatory T cells with a suppressive function in vitro via the STAT5-dependent pathway','https://www.tandfonline.com/doi/pdf/10.1080/0886022X.2018.1456462','await_full_text','Potential human CKD STAT5 perturbation/function mechanism; not inspected beyond discovery excerpt.','10.1080/0886022X.2018.1456462'),
('MA-C17','MA-Q02','An essential role for the IL-2 receptor in Treg cell function','https://www.uab.edu/medicine/rheumatology/images/AS_-_Chinen_et_al_2016.pdf','exclude','Mouse conditional genetics in surfaced experiments; not primary human evidence.',U),
('MA-C18','MA-Q02','Chromatin conformation dynamics during CD4+ T cell activation','https://assets-eu.researchsquare.com/files/rs-2855977/v1_covered_4d3bbc7a-5e96-4618-b489-77da2802521e.pdf','await_full_text','Preprint/version identity and primary-cell IL2 deletion experiment require full inspection.',U),
('MA-C19','MA-Q03','Identification of STAT5A and STAT5B Target Genes in Human T Cells','https://pmc.ncbi.nlm.nih.gov/articles/PMC3907443/','await_full_text','Potential direct-occupancy extension; author/cohort overlap with S02 requires resolution.','10.1371/journal.pone.0086790'),
('MA-C20','MA-Q03','Systematic discovery and perturbation of regulatory genes in human T cells reveals the architecture of immune networks','https://pmc.ncbi.nlm.nih.gov/articles/PMC10035359/','await_full_text','Broad primary-human gene network resource; exact narrower mediation mechanism not extracted.',U),
('MA-C21','MA-Q05','RASA2 ablation in T cells boosts antigen sensitivity and long-term function','https://www.nature.com/articles/s41586-022-05126-w','await_full_text','Useful receptor-proximal genetic/function candidate discovered late; retained for next screen without abstract-derived edges.','10.1038/s41586-022-05126-w'),
('MA-C22','MA-Q07','IL-2 and IL-15 Each Mediate De Novo Induction of FOXP3 Expression in Human Tumor Antigen-specific CD8 T Cells','https://pmc.ncbi.nlm.nih.gov/articles/PMC2174606/','await_full_text','Potential CD8 functional context contrast; no full-text extraction.',U),
('MA-C23','MA-Q08','NEGATIVE FEEDBACK REGULATION OF T CELLS: INTERLEUKIN2 AND FOXP3 RECIPROCITY (89.8)','https://academic.oup.com/jimmunol/article-abstract/182/Supplement_1/89.8/8013984','exclude','Conference abstract by same authors/topic as S07; no independent cohort evidence; not counted as replication.','10.4049/jimmunol.182.Supp.89.8'),
('MA-C24','MA-Q06','Author Correction: Genome-wide CRISPR screen in human T cells reveals regulators of FOXP3','https://www.nature.com/articles/s41586-025-09356-6','exclude','Integrity metadata linked to S06; adds competing-interest disclosure, not an independent mechanistic study.','10.1038/s41586-025-09356-6'),
('MA-C25','MA-Q03','STAT5B Deficiency: Impacts on Human Growth and Immunity','https://pmc.ncbi.nlm.nih.gov/articles/PMC4846566/','exclude','Review; discovery only, not an independent experiment.',U),
('MA-C26','MA-Q03','STAT5A and STAT5B—Twins with Different Personalities in Hematopoiesis and Leukemia','https://pmc.ncbi.nlm.nih.gov/articles/PMC6895831/','exclude','Review; no primary assertion extracted.',U),
('MA-C27','MA-Q08','The molecular mechanisms of regulatory T cell immunosuppression','https://pmc.ncbi.nlm.nih.gov/articles/PMC3522108/','exclude','Review/interpretive discussion, not primary evidence of a serial human feedback loop.',U),
('MA-C28','MA-Q08','IL-2 signaling strength dictates T cell biology and therapeutic outcomes in autoimmunity and cancer','https://pmc.ncbi.nlm.nih.gov/articles/PMC11126276/','exclude','Review; no assertion extracted.',U)]
for row in extras:candidate(*row)
# Preserve repeated primary appearances without multiplying unique papers.
for j,(i,q) in enumerate([(1,'MA-Q03'),(2,'MA-Q03'),(3,'MA-Q04'),(4,'MA-Q04'),(6,'MA-Q04'),(1,'MA-Q05'),(3,'MA-Q05'),(4,'MA-Q05'),(6,'MA-Q05'),(6,'MA-Q06'),(2,'MA-Q07'),(5,'MA-Q07'),(7,'MA-Q08'),(4,'MA-Q08'),(1,'MA-Q09'),(2,'MA-Q09'),(3,'MA-Q09'),(4,'MA-Q09')],29):
 s=S[f'MA-S{i:02}'];candidate(f'MA-C{j:02}',q,s['title'],s['url'],'await_full_text' if i==6 else 'include','Duplicate appearance of same primary paper; does not add independent evidence.',s['doi'],s['pmid'],s['source_id'])
write=lambda n,o:(D/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
write('screening.json',{'screening_scope':'Bounded ranked-search mechanistic screen; not an exhaustive systematic review. Scientific candidates triaged are recorded; unrelated commercial/news/person-index results are not treated as candidate studies.','queries':[{ 'query_id':x[0],'query_strings':x[1]} for x in batches],'candidate_appearances':records,'summary':{'candidate_appearance_count':len(records),'unique_candidate_paper_count':len({r['unique_paper_id'] for r in records}),'selected_primary_papers':7,'full_primary_methods_results_extracted':6,'selected_awaiting_main_full_text':1,'new_assertions':len(p['assertions']),'cohort_deduplication':'All inter-study donor independence remains unresolved unless a source explicitly describes distinct donor groups. Seven unique selected papers are not assumed seven fully independent donor cohorts.'}})
write('run.json',{'run_id':'MA-RUN-20260913','agent_role':'Evidence extractor: human T-cell activation/regulatory mechanisms; not independent reviewer','timestamp_start':'2026-09-13T19:19:09Z','timestamp_end':now,'timezone':'UTC (runtime clock); user America/New_York','LLM_provider':'OpenAI','LLM_model':'unavailable','model_family_instructions':'GPT-6','model_snapshot_if_available':U,'reasoning_mode':U,'protocol_version':'0.3.0 extraction phase','agent_prompt_version':'EXTRACTION_CONTRACT_0.3 plus original EXTRACTION_CONTRACT; user all-cytokines scope steering','instruction_bundle_hash':U,'instruction_versions':['research/EXTRACTION_CONTRACT_0.3.md','research/EXTRACTION_CONTRACT.md','README.md','Parent assignment: MA prefix and mechanisms_activation-only writes'],'skills_used':['ncbi-entrez-skill (script unavailable requests dependency; public-web fallback)','pdf:pdf (read-only analytical supplement text extraction)'],'source_versions':[{'source_id':s['source_id'],'version':s['version']} for s in p['sources']],'retrieval_queries':p['searches'],'retrieval_dates':[date],'source_hashes':'Computed in source_manifest.json as file-integrity hashes only; not a reviewed release','code_commit':U,'environment_hash':U,'output_hash':U,'critic_run_ids':[],'human_edits':[],'independent_review':'pending_user_trigger','human_review':'pending','numerical_priors_constructed':False,'production_release_frozen':False,'write_scope':'research/mechanisms_activation only','failed_attempts':[{'route':'Entrez skill/system Python and bundled Python','result':'requests dependency unavailable; no results; no package installed'},{'route':'Unprivileged curl PMC','result':'DNS unavailable; approved read-only retrieval succeeded'},{'route':'web.open PMC7037242 and PMC4169138','result':'recaptcha placeholder; approved curl subsequently retrieved real full HTML'},{'route':'web.open Nature2025 article','result':'unsafe redirect/internal fetch failure; curl retrieved subscription-limited primary HTML'},{'route':'Harvard primary PDF URL','result':'404 HTML; saved with .failed.html extension'},{'route':'Kyoto repository PDF URL','result':'HTML response not PDF; saved with .failed.html extension'},{'route':'Nature2025 main PDF URL','result':'HTML response not PDF; saved with .failed.html extension'},{'route':'Nature public figure3/4 pages and supplementary analysis Methods PDF','result':'Retrieved; no complete wet-lab Methods; two assertions remain needs_full_text'}],'structural_check_role':'Extraction completeness/reference validation only; not biological scientific review.'})
# Compact source index preserves true accessed locators, not invented excerpts.
manifest=[]
for f in sorted((D/'snapshots').iterdir()):
 if f.is_file():manifest.append({'path':str(f),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'access_class':'failed_retrieval_html' if '.failed.' in f.name else 'primary_partial_2025' if f.name.startswith('MA_S06') else 'source_tool_response' if 'web' in f.name else 'primary_full_html_or_text' if '_full' in f.name else 'metadata_or_supplement'})
write('source_manifest.json',manifest)
