import json, re, html
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parent
U = 'unavailable'
now = lambda: datetime.now(timezone.utc).isoformat()
def stamp(p):
    return datetime.fromtimestamp(p.stat().st_mtime, timezone.utc).isoformat()

source_specs = [
 ('G01',2014,'PMC4064786','Innate Immune Activity Conditions the Effect of Regulatory Variants upon Monocyte Gene Expression','10.1126/science.1246949','24604202','Benjamin P Fairfax et al.'),
 ('G02',2017,'PMC5675716','Discovery of stimulation-responsive immune enhancers with CRISPR activation','10.1038/nature23875','28854172','Dimitre R Simeonov et al.'),
 ('G03',2017,'PMC5456452','Human epistatic interaction controls IL7R splicing and increases Multiple Sclerosis risk','10.1016/j.cell.2017.03.007','28340352','Gaddiel Galarza-Muñoz et al.'),
 ('G04',2018,'PMC6289654','Impact of genetic polymorphisms on human immune cell gene expression','10.1016/j.cell.2018.10.022','30449622','Benjamin J Schmiedel et al.'),
 ('G05',2016,'PMC5119954','Genetic Drivers of Epigenetic and Transcriptional Variation in Human Immune Cells','10.1016/j.cell.2016.10.026','27863251','Lu Chen et al.'),
 ('G06',2022,None,'Single-cell eQTL mapping identifies cell type-specific genetic control of autoimmune disease','10.1126/science.abf3041','35389779','Seyhan Yazar et al.'),
 ('G07',2022,'PMC9197762','Immune disease risk variants regulate gene expression dynamics during CD4+ T cell activation','10.1038/s41588-022-01066-3','unavailable','Blagoje Soskic et al.'),
 ('G08',2007,None,'Interleukin 7 receptor alpha chain (IL7R) shows allelic and functional association with multiple sclerosis','10.1038/ng2103','17660817','Simon G Gregory et al.'),
 ('G09',2014,'PMC4124741','Common Genetic Variants Modulate Pathogen-Sensing Responses in Human Dendritic Cells','10.1126/science.1246980','24604203','Mark N Lee et al.'),
 ('G10',2019,'PMC6783569','Context-specific regulation of surface and soluble IL7R expression by an autoimmune risk allele','10.1038/s41467-019-12393-1','31594933','Hussein Al-Mossawi et al.')
]
sources=[]
for id,year,pmc,title,doi,pmid,authors in source_specs:
    p=ROOT/'snapshots'/f'{id}_fulltext.html' if pmc else ROOT/'snapshots'/f'{id}_open.txt'
    if pmc:
        raw=p.read_text()
        authors=[html.unescape(a) for a in re.findall(r'<meta name="citation_author" content="([^"]+)"',raw)] or authors
        m=re.search(r'<meta name="citation_pmid" content="([^"]+)"',raw)
        if m: pmid=m.group(1)
    note='Primary publication snapshot; supplementary captions embedded in main page reviewed where used. Standalone supplementary files and raw individual-level data not downloaded.'
    if id=='G02': note+=' Human and mouse experiments have separate cohorts. Author correction DOI 10.1038/s41586-018-0227-7 (2018) is retained as metadata/indexed excerpt in G02correction_retrieval.txt, search_01.json and Gsearch7_retrieval.txt. Correction full text not obtained; no EDEL steady-state Treg percentage assertion is extracted.'
    if id=='G06': note='OneK1K anchor evaluated at abstract level: 982 donors, 1,267,758 PBMCs, 14 cell types. No molecule-specific assertion extracted from aggregate coverage. Publisher full-text request returned 403. MR language in abstract is not accepted as experimental variant causality.'
    if id=='G08': note='Abstract-only historical association anchor. Functional assay methods and cohort-level membership not verified here; only disease association is extracted.'
    sources.append(dict(source_id=id,title=title,authors=authors,year=year,url=f'https://pmc.ncbi.nlm.nih.gov/articles/{pmc}/' if pmc else f'https://pubmed.ncbi.nlm.nih.gov/{pmid}/',doi=doi,pmid=pmid,source_type='primary_study',version=f'{year} primary publication; exact publisher revision unavailable',retrieved_at=stamp(p),access_level='full_text' if pmc else 'abstract_and_metadata',snapshot_path=str(p.relative_to(ROOT.parent.parent)),species=['Homo sapiens','Mus musculus'] if id=='G02' else 'Homo sapiens',notes=note))

cohorts=[]
def cohort(id,study,**kw):
    d={k:U for k in ['cohort_id','dataset_id','accession','study_id','participants','ancestry','species','tissue','cell_type','disease','intervention','sample_count','donor_count','parent_cohort','related_publications','independence_status','notes']}
    d.update(cohort_id=id,dataset_id=id.replace('GCO','GDS'),study_id=study,species='Homo sapiens',tissue='peripheral blood',disease='healthy',independence_status='unresolved',related_publications=[study]);d.update(kw);cohorts.append(d)
cohort('GCO01','G01',accession='EGAS00000000109 (genotypes); expression ArrayExpress accession unavailable in inspected main text',participants=432,donor_count=432,ancestry='European',cell_type='CD14+ monocyte',intervention='LPS 20 ng/mL, 2 or 24 h; IFNG 20 ng/mL, 24 h; unstimulated',sample_count='414 unstimulated; 367 IFNG; 322 24-h LPS; 261 2-h LPS; 228 donors shared across all four states',related_publications=['G01','G10'],notes='Fairfax Oxford monocyte cohort. Al-Mossawi soluble IL7R arm explicitly reuses 161 samples. Contexts and assays within this cohort are not independent donor replications; exact donor identifiers not inspected.')
cohort('GCO02','G02',participants=178,donor_count=178,ancestry='European American/Caucasian analysis restriction (author labels)',cell_type='CD4+ T cell',intervention='anti-CD3/CD28 stimulation',notes='Reanalysis of ImmVar T-cell expression data, not a newly recruited 178-person cohort. Potential donor overlap with ImmVar/PhenoGenetic Lee G09 unresolved.')
cohort('GCO03','G02',participants='Jurkat cell line',tissue='cell culture',cell_type='Jurkat T cell line',disease=U,intervention='CaRE4 allele reporter; anti-CD3/CD28; 20 h',sample_count='at least two independent experiments reported',notes='Engineered reporter system, not independent human donors or native allele replacement.')
cohort('GCO04','G02',species='Mus musculus',participants='C57BL/6 enhancer-edited mice and wild-type littermates',tissue='spleen and peripheral lymph nodes',cell_type='naive CD4+ CD62L+ CD44- T cell',disease='no induced disease',intervention='human rs61839660-equivalent SNP knock-in; anti-CD3/CD28 stimulation',sample_count='Figure 3d SNP n=6, wild-type n=10; 12DEL n=5 not pooled into SNP comparison',notes='Separate from NOD-background EDEL experiments and human ImmVar. Allele effect on mouse surface IL2RA is context-specific. No human disease phenotype proof.')
cohort('GCO05','G03',participants='HeLa cell line',tissue='cell culture',cell_type='HeLa',disease=U,intervention='allele-specific IL7R splicing and DDX39B 5-prime UTR reporters; DDX39B siRNA where indicated',sample_count='biological triplicates; knockdown experiments repeated three times',notes='Reporter experiments share laboratory system. GSE94730 belongs to RNA-seq experiments in this paper, not asserted to identify these reporter wells.')
cohort('GCO06','G03',participants=6,donor_count=6,cell_type='primary CD4+ T cell',intervention='anti-CD3/CD28 activation; DDX39B sh3/sh5 knockdown; IL2 culture then withdrawal before collection',sample_count=6,notes='Healthy donors stratified as IL7R rs6897932 CC or CT; no TT donor comparison. Individual donor samples are repeated across shRNA conditions.')
cohort('GCO07','G03',participants=52,donor_count=52,tissue='lymphoblastoid cell culture',cell_type='lymphoblastoid cell line',disease=U,ancestry='Yoruba/Esan in Nigeria (YRI/ESN), 25; Iberian in Spain (IBS), 27',intervention='genotype-stratified RNA/protein measurement',notes='Figure 3 experimental LCL panel, distinct per authors from earlier Wu 2013 YRI/CEU proteomics dataset. Within-panel genotype counts: African CC12/AC11/AA2; Iberian CC12/AC12/AA3. Do not merge with historical CEU null result as one population.')
cohort('GCO08','G03',participants=86,donor_count=86,cell_type='PBMC',disease='relapsing-remitting multiple sclerosis and healthy controls',intervention='genotype-stratified DDX39B RNA measurement',notes='Figure 3B counts CC32/AC31/AA23. Case/control split and ancestry not recovered. Not the six-cohort MS association meta-analysis.')
cohort('GCO09','G04',accession='phs001703.v1.p1',participants=91,donor_count=91,sample_count='106 leukapheresis collections including 15 longitudinal repeat collections',cell_type='13 purified immune cell types plus activated naive CD4/CD8 T cells',intervention='ex vivo profiling; T-cell activation in separate conditions',notes='DICE phase 1, San Diego Blood Bank. 54 male/37 female; median age 27 (18–61). Self-reported race/ethnicity in Table S1A, not fully extracted; ancestry unavailable rather than assumed European. Same donors across 15 cell conditions.')
cohort('GCO10','G04',participants=13,donor_count=13,cell_type='naive CD4+ T cell',intervention='pre-coated anti-CD3 10 micrograms/mL; soluble anti-CD28 1 microgram/mL; IL7 5 ng/mL; surface 4-1BB flow cytometry',notes='Figure 3K genotype-selected follow-up. Exact overlap with the 91-person DICE discovery cohort not verified; conservatively share study evidence group, not independent replication.')
cohort('GCO11','G05',accession='EGAS00001001456',participants='200 recruited; up to 197 analyzed',donor_count=197,cell_type='classical CD14+ CD16- monocytes; CD66b+ CD16+ neutrophils; phenotypically naive CD4+ CD45RA+ T cells',intervention='baseline purified-cell multiomic profiling',notes='BLUEPRINT human variation panel: 169/200 recruited donors extended to naive T cells; 54% female, mean age 55. UK blood-donor population. Genetic PCA European-ancestry criterion shown in Figure S2; exact retained ancestry breakdown not verified, so ancestry unavailable. Other BLUEPRINT publications are potential reuse, not new donors.')
cohort('GCO12','G06',participants=982,donor_count=982,sample_count='1,267,758 PBMCs (cells, not independent donors)',cell_type='14 PBMC immune cell types',intervention='single-cell RNA-seq; no stimulation stated in abstract',notes='OneK1K original cohort. GSE196830 identified in later primary-source data availability, but not independently checked against original deposition here. Ancestry/age/sex unavailable from inspected original abstract. Later OneK1K reuse is not independent evidence.')
cohort('GCO13','G07',accession=['EGAD00001008197','EGAD00010002291'],participants=119,donor_count=119,sample_count='655,349 cells',ancestry='British ancestry (author wording)',cell_type='naive and memory CD4+ T cells',intervention='anti-CD3/CD28 Dynabeads 1:2 bead:cell ratio; 16 h, 40 h, 5 d; negative controls cultured 16 h without beads',notes='67 male/52 female, mean age 47, SD15.61. Author-reported sex percentages (53.7%/56.3%) are inconsistent with counts and are not propagated. Donors modeled as repeated measures; subclusters are not independent cohorts. Cell culture time of resting comparator is not zero elapsed time.')
cohort('GCO14','G08',participants='four family-based or case-control datasets; sizes unavailable',cell_type=U,disease='multiple sclerosis and comparison participants',intervention='genetic association',notes='Authors describe four independent datasets within paper; individual cohort identities and overlap with later MS studies unresolved. Do not infer four independent weights from this abstract.')
cohort('GCO15','G09',accession='GSE57542',participants=534,donor_count=534,sample_count='1598 transcriptional profiles; preliminary microarray panel 30 donors',ancestry='295 Caucasians, 122 African-Americans, 117 East Asians (original study labels)',cell_type='monocyte-derived dendritic cell',intervention='LPS, influenza infection, IFNB stimulation, or resting',notes='PhenoGenetic/ImmVar-associated study. Disease-locus example Figure 6A uses 184 Caucasians (author wording). Cell differentiation is ex vivo; no direct extrapolation to tissue-resident DC. Discovery-panel overlap with 534 and overlap with GCO02 unresolved.')
cohort('GCO16','G10',participants=161,donor_count=161,sample_count=161,ancestry='European (inherited only from explicitly reused GCO01 cohort)',cell_type='CD14+ monocyte',intervention='LPS 20 ng/mL for 24 h; supernatant ELISA',parent_cohort='GCO01',related_publications=['G01','G10'],notes='Figure 3a and Results explicitly identify randomly selected samples from previous eQTL study. Known reuse; exact donor matching not available. Must share biological independence group with GCO01.')
cohort('GCO17','G10',participants=62,donor_count=62,sample_count=62,cell_type='CD14+ monocytes gated in PBMC',intervention='TNF 10 ng/mL, 24 h',notes='Figure 2e genotyped TNF arm; larger paper also has isolated-monocyte n84 and other PBMC panels. Do not sum panels as independent donors; overlap among panels and with original Fairfax cohort unresolved.')

assertions=[]
fields=['assertion_id','subject','subject_type','predicate','object','object_type','subject_layer','object_layer','measurement','evidence_tier','direction','source_id','cohort_id','source_locator','evidence_summary','species','ancestry','age','sex','tissue','disease','disease_severity','treatment_status','cell_type','cell_state','developmental_state','stimulation','dose','duration','assay','genomic_background','time_point','effect_size','effect_unit','uncertainty','causal_directness','limitations','contradiction_group','candidate_path','qc_status','qualitative_confidence']
C={c['cohort_id']:c for c in cohorts}
def add(id,src,co,subject,predicate,obj,summary,locator,**kw):
 d={k:U for k in fields};c=C[co]
 d.update(assertion_id=id,source_id=src,cohort_id=co,subject=subject,subject_type='variant',predicate=predicate,object=obj,object_type='gene',subject_layer='G',object_layer='T',measurement='RNA_abundance',evidence_tier='G2',direction='association',source_locator=locator,evidence_summary=summary,species=c['species'],ancestry=c['ancestry'],tissue=c['tissue'],disease=c['disease'],cell_type=c['cell_type'],uncertainty='Effect estimate and confidence interval unavailable unless explicitly supplied; cohort/state-specific evidence.',causal_directness='Genotype association with molecular trait; linked variants and residual confounding remain possible.',limitations='No automatic transport across cell type, stimulation, ancestry, tissue or molecular layer.',qc_status='reviewed_extraction',qualitative_confidence='moderate')
 d.update(kw);assertions.append(d)

add('G-A001','G01','GCO01','rs1179625','has_context_dependent_eQTL','HIP1','The peak rs1179625 association with HIP1 RNA has opposite directions in unstimulated monocytes and after 24-hour LPS.','Figure 1C; Results: Identifying Context-Specific Local Genetic Regulatory Variants',direction='mixed',stimulation='unstimulated versus LPS',dose='LPS 20 ng/mL',duration='24 h for LPS',assay='Illumina HumanHT-12 v4 expression microarray; HumanOmniExpress genotyping',contradiction_group='G-CX-HIP1-context')
add('G-A002','G01','GCO01','rs7700004 T allele','is_associated_with_increased_RNA','STAP1','After IFNG treatment, T-allele carriers show greater STAP1 induction than C-allele carriers.','Figure 1B',direction='increase',stimulation='IFNG',dose='20 ng/mL',duration='24 h',time_point='24 h',assay='expression microarray and genotype association')
add('G-A003','G01','GCO01','rs7131225','has_no_detected_eQTL_after_IFNG','GDPD5','The GDPD5 eQTL detected in untreated monocytes was no longer detected after IFNG-induced expression.','Figure 1B',direction='null',stimulation='IFNG',dose='20 ng/mL',duration='24 h',assay='expression microarray and genotype association',limitations='Failure to detect is not equivalence or proof of zero effect; power and induction-dependent variance may differ.',contradiction_group='G-CX-GDPD5-stimulation')
add('G-A004','G01','GCO01','cis genetic variation at TNF','has_late_LPS_eQTL','TNF','A TNF RNA eQTL is detected after 24-hour LPS but not during the 2-hour induction phase.','Figure 1D; Results: Identifying Context-Specific Local Genetic Regulatory Variants',subject_type='variant_set',stimulation='LPS',dose='20 ng/mL',duration='2 h versus 24 h',assay='expression microarray and cis-eQTL mapping',limitations='Lead variant not extracted; this locus-level assertion must not become a named causal-variant edge. RNA does not measure TNF secretion.',contradiction_group='G-CX-TNF-LPS-time')
add('G-A005','G02','GCO03','rs61839660 alternate allele in CaRE4','reduces_stimulation_dependent_reporter_activity','CaRE4 luciferase reporter','Introducing rs61839660 into CaRE4 reduces the stimulation-dependent reporter signal relative to reference sequence in Jurkat cells.','Figure 2c,d; Methods: Luciferase assays',object_type='reporter',object_layer='P',measurement='protein_activity',evidence_tier='G4',direction='decrease',stimulation='anti-CD3/CD28',duration='20 h stimulated assay',assay='heterologous enhancer luciferase reporter',causal_directness='Direct allele manipulation establishes an effect in the reporter assay; G4 is restricted to that assay.',limitations='Reporter enzymatic signal is a regulatory readout, not measured endogenous IL2RA RNA or cytokine responsiveness. No native human allele replacement.')
add('G-A006','G02','GCO02','rs61839660 minor allele','is_associated_with_reduced_RNA','IL2RA','The minor allele associates with reduced IL2RA transcript after CD3/CD28 stimulation, including analysis conditioned on rs2476491.','Figure 2e and Extended Data Figure 6',direction='decrease',stimulation='anti-CD3/CD28',assay='ImmVar transcript reQTL reanalysis',limitations='Association remains G2 despite supporting reporter/mouse experiments elsewhere; ImmVar donor reuse unresolved.')
add('G-A007','G02','GCO04','rs61839660-equivalent SNP knock-in','reduces_early_surface_abundance','Il2ra','Naive T cells from SNP knock-in mice have reduced surface IL2RA 24 hours after CD3/CD28 activation.','Figure 3c,d',object_type='surface_protein',object_layer='P',measurement='protein_abundance',evidence_tier='G4',direction='decrease',stimulation='plate-bound anti-CD3/CD28',duration='24 h',time_point='day 1',genomic_background='C57BL/6; homozygous SNP knock-in versus wild-type littermates',assay='CRISPR knock-in followed by flow cytometry',effect_size='approximately 50% of wild-type surface expression',effect_unit='relative surface IL2RA',uncertainty='Reported P <= 0.0001; Figure 3d SNP n=6 and wild-type n=10; no confidence interval extracted.',causal_directness='Direct allele editing in mice; effect applies to measured mouse surface abundance.',limitations='Separate from human evidence and from NOD EDEL deletion experiments. Not complete loss of receptor, signaling assay or proof of human autoimmunity.',contradiction_group='G-CX-IL2RA-time-species')
add('G-A008','G03','GCO05','rs6897932 C allele','increases_exon6_skipping_relative_to_T','IL7R exon 6','Under DDX39B depletion, the IL7R-C minigene shows more exon 6 skipping than the IL7R-T minigene.','Figure 5; Methods: DDX39B RNAi-mediated knockdown and rescue',object_type='splice_event',measurement='splicing',evidence_tier='G4',direction='increase',stimulation='DDX39B siRNA depletion',duration='siRNA on days 1/3; reporter day 5; RNA day 7',assay='allele-specific minigene reporter; RT-PCR',genomic_background='HeLa; reporter C versus T at rs6897932',causal_directness='Direct reporter allele manipulation with trans-factor depletion; assay-specific causal effect.',limitations='HeLa reporter context does not establish the same effect size in unstimulated primary immune cells.',contradiction_group='G-CX-DDX39B-IL7R-context')
add('G-A009','G03','GCO05','rs2523506 A allele','reduces_5UTR_reporter_translation_readout','DDX39B 5-prime UTR luciferase reporter','A-allele DDX39B 5-prime UTR reporters have lower luciferase activity per RNA than C-allele reporters.','Figure 4A,B; Results: rs2523506 controls translation efficiency',object_type='reporter',object_layer='P',measurement='protein_activity',evidence_tier='G4',direction='decrease',assay='dual luciferase activity divided by reporter RNA quantified by RT-qPCR',effect_size='approximately 20–30% reduction',effect_unit='normalized reporter activity per RNA',causal_directness='Direct UTR allele manipulation tests a translation readout in HeLa cells.',limitations='Not a direct endogenous DDX39B protein measurement or native allele edit. Does not imply an eQTL for RNA abundance.')
add('G-A010','G03','GCO08','rs2523506','has_no_detected_RNA_association','DDX39B','DDX39B RNA levels do not differ detectably by rs2523506 genotype in the PBMC panel.','Figure 3B left',evidence_tier='G1',direction='null',assay='RT-qPCR, genotype-stratified PBMC samples',uncertainty='86 donors; genotype groups CC32, AC31, AA23; no equivalence interval reported.',limitations='Candidate association null, not genome-wide eQTL mapping. Case/control composition and treatment context unresolved. RNA null cannot negate the separate protein/readout evidence.',contradiction_group='G-CX-DDX39B-layer')
add('G-A011','G03','GCO06','DDX39B','depletion_increases_exon6_skipping','IL7R exon 6','Two DDX39B shRNAs increase IL7R exon 6 skipping in activated primary CD4 T cells from six donors.','Figure 6; Results: DDX39B regulates IL7R exon 6 inclusion in primary CD4+ T cells',subject_type='gene',subject_layer='T',object_type='splice_event',measurement='splicing',evidence_tier='perturbational',direction='increase',stimulation='anti-CD3/CD28 activation followed by DDX39B shRNA',dose='activation anti-CD3 50 ng/mL and anti-CD28 100 ng/mL; culture IL2 100 ng/mL',duration='48 h preactivation; 72 h transduction; 96 h selection; 24 h without IL2/puromycin before collection',genomic_background='donors rs6897932 CC or CT',assay='lentiviral shRNA; RT-PCR; DDX39B western blot',causal_directness='Trans-factor depletion in primary cells; does not directly edit rs2523506.',limitations='Six donors; differential knockdown efficiency; genotype groups small. No TT group. Gene depletion is not a causal variant experiment.',contradiction_group='G-CX-DDX39B-IL7R-context')
add('G-A012','G03','GCO06','DDX39B','depletion_changes_supernatant_IL7R','IL7R soluble protein','Supernatant IL7R increases in all six donors with sh3, but only two donors with sh5 despite splicing changes.','Results accompanying Figure 6; Figure S10',subject_type='gene',subject_layer='T',object_type='soluble_protein',object_layer='P',measurement='secreted_protein',evidence_tier='perturbational',direction='association',stimulation='DDX39B shRNA in previously CD3/CD28-activated T cells',duration='24-h collection without IL2 and puromycin after knockdown/selection',assay='supernatant ELISA',causal_directness='Primary-cell depletion; inconsistent reagent-specific protein output.',limitations='Authors state ELISA antibody can detect all IL7R isoforms; unexplained sh5 discordance. Do not infer uniform secretion change from exon skipping.',contradiction_group='G-CX-DDX39B-protein-shRNA')
add('G-A013','G04','GCO09','rs2511162 A/A genotype','is_associated_with_lower_RNA','GAB2','The A/A genotype associates with lower GAB2 RNA in B cells.','Figure 3G and Results: Expression QTLs are highly cell-specific',direction='decrease',cell_type='B cell',cell_state='ex vivo',assay='purified-cell RNA-seq; cis-eQTL mapping',contradiction_group='G-CX-GAB2-cell-type')
add('G-A014','G04','GCO09','rs2511162 A/A genotype','is_associated_with_higher_RNA','GAB2','The same A/A genotype associates with higher GAB2 RNA in T cells.','Figure 3G and Results: Expression QTLs are highly cell-specific',direction='increase',cell_type='T cell',cell_state='ex vivo',assay='purified-cell RNA-seq; cis-eQTL mapping',limitations='Do not turn opposing cell-type associations into a uniform regulatory prior. Exact T-cell subset coefficients not extracted.',contradiction_group='G-CX-GAB2-cell-type')
add('G-A015','G04','GCO10','rs9657975 T/T genotype','is_associated_with_more_surface_positive_cells','TNFRSF9','After activation, T/T donors have a greater fraction of surface 4-1BB-positive CD4 T cells than C/C donors.','Figure 3K; Figure S2F',object_type='surface_protein',object_layer='P',measurement='protein_abundance',evidence_tier='G1',direction='increase',stimulation='pre-coated anti-CD3; soluble anti-CD28; IL7 co-stimulation',dose='anti-CD3 10 micrograms/mL; anti-CD28 1 microgram/mL; IL7 5 ng/mL',assay='flow cytometry in 13 genotype-selected subjects',causal_directness='Candidate genotype–protein association follow-up, not direct allele manipulation.',limitations='Other activation markers CD69/CD25/HLA-DR did not share the effect. Protein validation does not establish signaling, clinical response or causal variant localization.')
add('G-A016','G05','GCO11','rs1800693-associated MS signal','colocalizes_with_splicing_QTL','TNFRSF1A','The multiple-sclerosis signal at rs1800693 colocalizes with TNFRSF1A alternative splicing in monocytes and neutrophils.','Results: Molecular QTLs Colocalize with Disease-Predisposing Variants; Figure 7 and Table S5',object_type='splice_event',measurement='splicing',evidence_tier='G3',cell_type='monocyte and neutrophil',cell_state='baseline purified cells',assay='RNA-seq sQTL mapping and disease-QTL colocalization',causal_directness='Statistical support for a shared locus mechanism; no allele perturbation in this assertion.',limitations='Colocalization is model-dependent; exact event coordinates, allele direction and posterior not extracted. Does not prove secretion of a soluble TNFRSF1A isoform.')
add('G-A017','G05','GCO11','rs3807306','is_associated_with_isoform_switch','IRF5','rs3807306 associates with a switch between two major IRF5 isoforms with different 5-prime UTRs in neutrophils.','Figure 4E (ISO sQTL examples)',object_type='splice_event',measurement='splicing',cell_type='neutrophil',cell_state='baseline purified cells',assay='RNA-seq isoform sQTL mapping',limitations='Isoform association without direct allele perturbation. No transcription-factor protein activity inferred.')
add('G-A018','G07','GCO13','cis genetic variation at VAMP8','has_TCM_specific_eQTL','VAMP8','A VAMP8 eQTL is detected in central-memory CD4 T-cell subpopulations, while absent in the inspected DICE T-cell comparison.','Results: eQTL mapping in CD4+ T cell populations; Figure 2g',subject_type='variant_set',cell_type='central-memory CD4+ T cell',stimulation='CD3/CD28 activation study',dose='1:2 Dynabead:cell ratio',duration='study spans resting control, 16 h, 40 h and 5 d; exact VAMP8 subcluster time unavailable',assay='single-cell RNA-seq aggregated per donor/cluster; tensorQTL',uncertainty='Reported TCM-specific adjusted P=5e-4; lead SNP and effect size not extracted.',limitations='Molecule-specific QTL target supported, but lead variant unavailable. DICE nondetection may reflect power/annotation differences and is not proof of biological absence. No materialized variant path.')
add('G-A019','G07','GCO13','cis genetic variation at AIMP1','has_TCM_specific_eQTL','AIMP1','An AIMP1 eQTL is detected in central-memory CD4 T-cell subpopulations and was not detected in the inspected DICE T-cell comparison.','Results: eQTL mapping in CD4+ T cell populations',subject_type='variant_set',cell_type='central-memory CD4+ T cell',stimulation='CD3/CD28 activation study',dose='1:2 Dynabead:cell ratio',duration='study spans resting control, 16 h, 40 h and 5 d; exact AIMP1 subcluster time unavailable',assay='single-cell RNA-seq aggregated per donor/cluster; tensorQTL',uncertainty='Reported TCM-specific adjusted P=1.04e-4; lead SNP and effect size not extracted.',limitations='Lead variant unavailable; no variant-specific prior or signaling-function inference. DICE comparison differs in cell definitions and power.')
add('G-A020','G08','GCO14','rs6897932','is_associated_with_disease_susceptibility','multiple sclerosis','IL7R polymorphism rs6897932 is associated with multiple sclerosis across four datasets in the original report.','PubMed abstract, association and variant sentences',object_type='disease',object_layer='F',measurement='association',evidence_tier='G1',assay='family-based and case-control association',uncertainty='Overall P=2.9e-7; effect size and confidence interval unavailable in abstract.',causal_directness='Disease association; does not itself establish molecular or disease causality.',limitations='Abstract-only extraction. Cohort membership, sample sizes and allele effects require full-text verification; four publications/datasets are not automatically four independent prior increments.',qc_status='needs_full_text',qualitative_confidence='low')
add('G-A021','G09','GCO15','rs4963128','has_IFNB_specific_eQTL','IRF7','rs4963128 associates with IRF7 expression after IFNB stimulation but is not detected as an association at baseline.','Figure 6A and Results: Linking reQTLs to human disease',ancestry='Caucasian (author label; Figure 6A n=184)',stimulation='IFNB versus resting',assay='NanoString 415-gene panel; genotype association',uncertainty='Stimulated P=1.10e-16; effect size unavailable.',limitations='SLE-associated SNP is not proven causal by this eQTL; baseline nondetection is not an equivalence test.',contradiction_group='G-CX-IRF7-stimulation')
add('G-A022','G09','GCO15','rs12805435','has_influenza_specific_trans_eQTL','IFNA13','rs12805435 associates in trans with IFNA13 expression and induction after influenza infection; the trans effect is stimulus-specific.','Figure 5B; Results on trans associations; Tables S8–S10',stimulation='influenza infection',duration='10 h infection time used in study response design',assay='NanoString expression/differential-expression QTL mapping',causal_directness='Trans molecular association; separate IRF7 overexpression is supportive but does not edit this variant.',limitations='Restricted 415-gene signature and trans-testing strategy; IFNA13 RNA is not secreted IFN-alpha protein or antiviral phenotype.')
add('G-A023','G10','GCO17','rs6897932 C risk allele','is_associated_with_lower_surface_abundance','IL7R','After TNF stimulation, the disease-risk allele associates with lower mean monocyte surface IL7R.','Figure 2e; Results: rs6897932 regulates monocyte cell surface IL7R levels',object_type='surface_protein',object_layer='P',measurement='protein_abundance',direction='decrease',stimulation='TNF',dose='10 ng/mL',duration='24 h',time_point='24 h',assay='surface flow cytometry; genotype association',uncertainty='P=0.0007, ANOVA; n=62; numeric effect unavailable.',limitations='PBMC-gated monocytes, not purified-cell intrinsic effect proof. TNF context differs from the LPS soluble-protein arm. No direct measurement of receptor signaling.',contradiction_group='G-CX-IL7R-layer-context')
add('G-A024','G10','GCO16','rs6897932 C allele','is_associated_with_more_supernatant_protein','IL7R soluble protein','CC donors have higher soluble IL7R in monocyte supernatants than TT donors after 24-hour LPS.','Figure 3a; Results: sIL7R is regulated by rs6897932',object_type='soluble_protein',object_layer='P',measurement='secreted_protein',direction='increase',stimulation='LPS',dose='20 ng/mL',duration='24 h',time_point='24 h',assay='supernatant sandwich ELISA; CD127 polyclonal antibodies, Fc-chimera standard',uncertainty='Allelic P=4.7e-15; n=161. Published absolute concentration units need source-data verification and are not used as an effect-size prior.',limitations='Known donor reuse from G01. ELISA does not independently identify splice origin versus all extracellular isoforms or prove IL7 availability/activity.',contradiction_group='G-CX-IL7R-layer-context')
add('G-A025','G10','GCO16','rs2523506 by rs6897932 genotype interaction','has_no_detected_effect_on_supernatant_protein','IL7R soluble protein','The reported DDX39B–IL7R genetic interaction is not detected for soluble IL7R in LPS-stimulated monocytes.','Results after Figure 3; Supplementary Figure 6',subject_type='variant_interaction',object_type='soluble_protein',object_layer='P',measurement='secreted_protein',evidence_tier='G1',direction='null',stimulation='LPS',dose='20 ng/mL',duration='24 h',assay='supernatant ELISA with candidate genotype interaction analysis',causal_directness='Candidate interaction test, not a direct perturbation of either allele.',limitations='Minor-allele frequency limits power. Monocyte LPS context differs from HeLa reporter and activated CD4 T-cell experiments; this null does not refute their context-specific effects.',contradiction_group='G-CX-DDX39B-IL7R-context')

query_batches=[
 ('search_01.json', ['Fairfax 2014 innate immune activity conditions effect regulatory variants monocytes eQTL Science','Simeonov 2017 IL2RA stimulation responsive enhancer rs61839660 Nature','Gregory 2007 IL7R rs6897932 alternative splicing multiple sclerosis'], [['G01'],['G02'],['G03','G08']]),
 ('search_02.json',['Schmiedel 2018 Impact genetic polymorphisms human immune cell gene expression DICE PMC 91','Chen 2016 genetic drivers epigenetic transcriptional variation human immune cells BLUEPRINT PMC','Yazar 2022 single cell eQTL mapping identifies cell type specific genetic control autoimmune disease OneK1K PMC','Soskic 2022 immune disease risk variants regulate gene expression dynamics T cell activation Nature Genetics'],[['G04'],['G05'],['G06'],['G07']]),
 ('Gsearch3_retrieval.txt',['"Discovery of stimulation-responsive" PMC','"Human epistatic interaction controls IL7R splicing" "rs2523506"','"Common genetic variants modulate pathogen-sensing responses" Lee 2014 PMC','"Immune disease risk variants" "rs" "Soskic"'],[['G02'],['G03','G10'],['G09'],[]]),
 ('Gsearch4_retrieval.txt',['site.pmc.ncbi.nlm.nih.gov/articles/PMC5675716/ "rs61839660" "luciferase"','site.pmc.ncbi.nlm.nih.gov/articles/PMC6783569/ "monocytes" "rs6897932"','site.pmc.ncbi.nlm.nih.gov/articles/PMC5119954/ "IL6R"','site.nature.com/articles/s41588-022-01066-3 "rs"'],[['G02'],['G10'],[],[]]),
 ('Gsearch7_retrieval.txt',['"Immune disease risk variants regulate gene expression dynamics" "PMC"','"OneK1K" "European" "GSE196830"','"Author Correction" "0227-7" "percentages"'],[['G07'],['G06'],['G02']])
]
searches=[]
for fn,qs,ids in query_batches:
 for q,result_ids in zip(qs,ids):
  searches.append(dict(search_id=f'G-S{len(searches)+1:03d}',lane='genomic',query=q,database='web search (targeted primary-publication discovery)',searched_at=stamp(ROOT/'snapshots'/fn),result_source_ids=result_ids,screening_notes=f'Bounded purposive pilot; snapshot {fn}. Timestamp is saved tool-response time, not an inferred publication date. '+('No extractable result selected for this exact query.' if not result_ids else 'Primary sources selected for study/variant relevance; unrelated and review results not used as mechanistic evidence.')))
gaps=[
 dict(gap_id='G-GAP01',description='This is a purposive 10-publication pilot, not exhaustive systematic search. No independent database-wide screening, full inclusion/exclusion ledger, full citation chaining, or search saturation is claimed.'),
 dict(gap_id='G-GAP02',description='OneK1K is abstract-level and contributes cohort/source context only. Obtain full methods, ancestry and variant-level summary statistics before any molecule-specific assertions or causal-MR interpretation.'),
 dict(gap_id='G-GAP03',description='The 2018 IL2RA author correction is confirmed; indexed excerpt indicates altered EDEL Treg percentages after genotype correction/paired analysis. Correction full text is not obtained. Original EDEL steady-state phenotype statement is not imported.'),
 dict(gap_id='G-GAP04',description='Cohort independence remains unresolved for ImmVar/PhenoGenetic reuse, DICE protein follow-up, BLUEPRINT secondary analyses and MS association cohorts. Explicit G10→G01 subset reuse must be enforced in weighting.'),
 dict(gap_id='G-GAP05',description='DICE ancestry distribution, individual BLUEPRINT ancestry filtering, and complete dose/time metadata in ImmVar/Lee still need supplementary extraction. Soskic reported sex percentages conflict with counts; retain counts without erroneous percentages.'),
 dict(gap_id='G-GAP06',description='Lead variants and event coordinates missing for VAMP8, AIMP1, TNF and TNFRSF1A event descriptions. These are target/event-level evidence records, not fully identified variant-specific prior inputs.'),
 dict(gap_id='G-GAP07',description='HLA/KIR, structural variation, somatic variants, ancestry-diverse immune QTL atlases, pQTL colocalization, cytokine-QTL dose-response and tissue-resident immune regulation are not systematically covered.'),
 dict(gap_id='G-GAP08',description='Recent indexed candidates require next-round screening: Genome-scale mapping of variant, enhancer and gene function in primary human CD4+ T cells (PMC13060838); Cell-type-specific eQTLs underlie the genetic architecture of complex traits (10.1038/s41586-026-10577-6); single-cell splicing study (10.1038/s41588-024-02019-8). No results are asserted without primary extraction; later OneK1K reuse must not count as independent replication.'),
 dict(gap_id='G-GAP09',description='Published absolute soluble IL7R concentrations in G10 may require unit verification against source data and assay calibration. They are intentionally not numeric magnitude priors; qualitative direction and reported association P are retained.'),
 dict(gap_id='G-GAP10',description='No source-to-target cytokine pathway is proven by these genomic assertions. Reporter, transformed-line, primary-cell, resting/stimulated, timepoint, RNA/protein and species contexts must pass compatibility checks before assembly.')
]
pack=dict(sources=sources,cohorts=cohorts,assertions=assertions,searches=searches,gaps=gaps,synthesis='Genomic evidence is state- and modality-dependent. Stimulated eQTLs, direction reversals, splicing effects and separately measured surface or supernatant proteins support context-specific priors. Direct allele reporter effects and mouse edits are retained at their actual assay/species level; human molecular QTLs remain statistical evidence. Nulls and reagent discordance remain visible. Ten primary sources form a bounded pilot; OneK1K provides an evaluated atlas anchor without invented molecule-level edges. No disease-causal complete path or calibrated probability is claimed.')
(ROOT/'pack.json').write_text(json.dumps(pack,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'sources':len(sources),'cohorts':len(cohorts),'assertions':len(assertions),'searches':len(searches),'gaps':len(gaps)},indent=2))
