import json, re
from pathlib import Path
from datetime import datetime, timezone
D=Path('research/mechanisms_activation'); U='unavailable'; now=datetime.now(timezone.utc).isoformat()
def write(name,obj): (D/name).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
def snap(s):return f'research/mechanisms_activation/snapshots/MA_S{s:02}_full.txt'
urls={1:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7037242/',2:'https://pmc.ncbi.nlm.nih.gov/articles/PMC4169138/',3:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7577958/',4:'https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2021.655122/full',5:'https://pmc.ncbi.nlm.nih.gov/articles/PMC1895505/',6:'https://www.nature.com/articles/s41586-025-08795-5',7:'https://pmc.ncbi.nlm.nih.gov/articles/PMC2265256/'}
sources=[]
for i in range(1,8):
 m=json.load((D/f'snapshots/MA_S{i:02}_full_metadata.json').open())
 def val(k):return m.get('citation_'+k,[U])[0]
 sources.append(dict(source_id=f'MA-S{i:02}',title=val('title'),authors=m.get('citation_author',U),year=int(re.search(r'\d{4}',val('publication_date')).group()),url=urls[i],doi=val('doi'),pmid=('34408743' if i==4 else '40140585' if i==6 else val('pmid')),source_type='primary_study',version='Primary article as retrieved 2026-09-13; '+('abstract, extended-data captions and public Figures 3/4 plus supplementary analytical Methods; main Methods/Results inaccessible' if i==6 else 'PMC/publisher full HTML; selected Methods/Results inspected'),retrieved_at=now,access_level='partial_primary_article_and_analysis_supplement' if i==6 else 'full_text_primary_methods_results_inspected',snapshot_path=snap(i),species=['Homo sapiens','Mus musculus'] if i in [3,6] else 'Homo sapiens',notes=('Human-cell in vitro records only; xenogeneic mouse-host functional experiments not transported to human in vivo.' if i in [3,6] else 'Primary human-cell records; nonprimary cell lines and clinical follow-up omitted from extracted assertions.'),corrections_retractions_checked={'checked_at':now,'method':'DOI/title-specific ranked public-web search plus article page notice inspection; not a complete Crossmark or Retraction Watch audit','result':'Author Correction 10.1038/s41586-025-09356-6 adds a competing-interest disclosure; no biological result correction stated. Saved primary notice.' if i==6 else 'No matching correction/retraction notice found in bounded checks; absence not guaranteed','notice_url':'https://www.nature.com/articles/s41586-025-09356-6' if i==6 else U},related_original_source_ids=[]))
# correct Nature citation metadata may be absent on subscription HTML
sources[5].update(title='Genome-wide CRISPR screen in human T cells reveals regulators of FOXP3',doi='10.1038/s41586-025-08795-5',year=2025)
cohorts=[]
def co(i,s,cell,intervention,donors,notes,accession=U,disease='healthy',age=U):
 x=dict(cohort_id=f'MA-CO{i:02}',dataset_id=f'MA-D{s:02}',accession=accession,study_id=f'MA-S{s:02}',participants='Primary human blood donors',ancestry=U,species='Homo sapiens',tissue='peripheral blood',cell_type=cell,disease=disease,intervention=intervention,sample_count=U,donor_count=donors,parent_cohort=U,related_publications=[],independence_status='unresolved',notes=notes,age=age);cohorts.append(x);return x
co(1,1,'Negatively isolated CD4+CD45RO− naive T cells','anti-CD3 beads with CD28 or IgG; A-FOS versus GFP electroporation','Figures 5 and 6: total 3 donors across 1–3 independent experiments','Deidentified blood filters, Hoxworth Blood Center. Same paper does not identify exact donor overlap across nuclear protein, RNA, ATAC and ChIP aliquots.','GSE116698')
co(2,2,'Purified human CD4+ cells; FOXP3 protein readout gated CD4+CD25+','STAT5A/B siRNA versus scrambled siRNA','Fig1 n=3; Fig2E control n=4, STAT5A n=2, STAT5B n=6','Healthy knockdown cohort separate from patient functional observations; RNA and protein aliquot/donor matching unavailable.')
co(3,2,'FACS-sorted CD4+CD25hiCD127low/− Tregs and CD4+CD25− responders','Natural STAT5B deficiency; suppression correlation','Fig3 four homozygous-deficient patients (#1,2,5,6), one heterozygote, one healthy control','Parent paper describes six deficient patients; #3/#4 are siblings. Earlier patient reports are cited and may overlap; do not count publications as replication. Fig3 correlation does not test FOXP3 mediation.',disease='STAT5B deficiency with heterogeneous clinical manifestations',age='Patient cohort 6–31 years; exact Fig3 age distribution unavailable')
co(4,3,'Sorted CD4+CD25hiCD127low Tregs (>97% purity), expanded','Pooled CRISPR RNP screen; cytokine treatments','4 donors','Pooled screen donors explicitly distinct from two additional arrayed-screen donors. Guide-level enrichments are not independent biological replicates.')
co(5,3,'Sorted CD4+CD25hiCD127low Tregs, expanded','Arrayed CRISPR with 3 gRNAs/TF; IL12 or no added IL12','2 additional donors','Explicitly additional to pooled-screen donors; overlap with scRNA-seq donor pair unavailable. Several phenotypes, including HIVEP2 after IL12, markedly differed by donor.')
co(6,3,'Sorted Tregs; activated 48 h before editing for scRNA-seq','Selected TF knockout and IL12 condition; PMA/ionomycin restimulation','2 donors; 54,424 single-cell transcriptomes across conditions','Donors pooled 1:1 and computationally demultiplexed; cells are not donors. Preparation differs from prolonged expansion for arrayed flow. Exact overlap with arrayed donors unavailable.')
co(7,4,'PI−CD4+CD25+CD127− sorted Tregs; expanded 7 days before editing','IL2RA CRISPR RNP; CD25-negative sorting','Fig4B n=11; pSTAT5 n=3; suppression n=3–6; FOXP3 mock n=3, CD25+ and KO n=6','Buffy coats from healthy donors. 4-day post-edit sorting; pSTAT5 and functional assay donor overlap unavailable. IL2RA editing efficiency/zygosity heterogeneous; sequencing KO score 70% in sorted cells.')
co(8,5,'FACS-sorted CD4+CD25bright or CD4+CD25− T cells (>95% purity)','IL2 with/without anti-CD3','unavailable','Healthy in vitro donors separate from 21 clinical IL2 recipients and 293 reporter cells. Within Figure1B, CD25-positive/negative cells explicitly same individual; RNA/protein donor matching unavailable.')
co(9,6,'Primary human CD4+ T cells polarized to iTregs','RBPJ and HDAC3 genetic perturbation','Fig4e n=4; Fig3j n=3; full cohort linkage unavailable','Main wet-lab Methods inaccessible. Figure captions and supplementary analytical Methods accessible. Mouse experiments kept outside human assertions.','PRJDB16517')
co(10,7,'Unfractionated PBMCs; CD4+ and CD8+ gates','Soluble anti-CD3; IL2/CD25 blocking antibodies and IL2 competition','Baseline n=19; Fig1D CD4 n=16/CD8 n=17; Figs3/4 n=4; restimulation n=5','Normal volunteers. Assay-specific counts are experiments unless specified as individuals; exact donor overlap across figures unavailable. Monocytes retained; not a purified Treg culture.')
C={x['cohort_id']:x for x in cohorts}; assertions=[]
def a(n,s,c,subject,sl,subject_type,predicate,obj,ol,objtype,measurement,direction,loc,summary,**kw):
 x={k:U for k in ['ancestry','age','sex','disease_severity','treatment_status','developmental_state','dose','duration','genomic_background','time_point','effect_size','effect_unit','uncertainty','contradiction_group','candidate_path']}
 cohort=C[f'MA-CO{c:02}'];x.update(assertion_id=f'MA-A{n:02}',subject=subject,subject_type=subject_type,predicate=predicate,object=obj,object_type=objtype,subject_layer=sl,object_layer=ol,measurement=measurement,evidence_tier='perturbational',direction=direction,source_id=f'MA-S{s:02}',cohort_id=cohort['cohort_id'],source_locator=loc,evidence_summary=summary,species='Homo sapiens',tissue='peripheral blood',disease=cohort['disease'],cell_type=cohort['cell_type'],cell_state=U,stimulation=cohort['intervention'],assay=U,causal_directness='Controlled perturbation within the stated preparation; no unmeasured intermediate or downstream endpoint implied.',limitations='Donor overlap across different figures is unavailable unless explicitly stated.',qc_status='needs_full_text' if s==6 else 'extracted_pending_review',qualitative_confidence='low' if s==6 else 'moderate',supporting_snapshot_paths=[snap(s)],related_original_assertion_ids=[],independence_note='No matching DOI found among inherited packs; assertions within this paper are not independent studies.');x.update(kw);x['tested_hypothesis']=x.pop('hypothesis',summary);x['evidence_relation']=x.pop('relation','inconclusive' if direction=='null' else 'supports');assertions.append(x)
A1CTX=dict(cell_state='naive; CD3 stimulation with or without CD28',dose='Bead coating: 24 ng anti-CD3 and 52 ng anti-CD28 or mouse IgG per 100 µL beads',duration='5 h primary chromatin comparison; FigS5A nuclear-blot sampling points not transcribed',time_point='5 h for ATAC; nuclear-blot time labels unavailable')
a(1,1,1,'CD28 costimulation omission','C','experimental_condition','reduces','nuclear FOS/JUNB protein','P','protein_localization','protein_abundance','decrease','Results Co-stimulation is required for open chromatin formation; FigS5A; Methods nuclear proteins/Western blot','Omitting CD28 during CD3 activation markedly reduced nuclear AP-1 abundance; nuclear NFAT1/2 was only slightly reduced.',assay='Nuclear protein fractionation; cFOS/JUNB immunoblot',limitations='Nuclear abundance is not direct DNA-binding activity. No CD28 rescue experiment; NFAT comparison is contextual.',**A1CTX)
a(2,1,1,'A-FOS dominant-negative protein','P','protein','reduces','AP-1-bound activation-induced chromatin accessibility','G','regulatory_chromatin_state','direct_transcriptional_regulation','decrease','Fig5D–G; Results AP-1 inhibition; Methods A-FOS preparation/electroporation/ATAC-seq','A-FOS reduced opening of AP-1-bound activation regions relative to GFP; constitutively open and naive-open regions were comparatively spared.',dose='25 µg A-FOS or GFP per 3.5 million naive cells',duration='2 h recovery then 5 h activation',time_point='5 h after CD3/CD28 stimulation',assay='ATAC-seq with supporting AP-1 ChIP-seq',cell_state='naive cells electroporated before activation',quantitative_result='395 regions accessible with GFP but not A-FOS; 73% bound by both FOS and JUNB',limitations='Dominant-negative sequestration affects JUN partners broadly; not single-FOS specificity. Chromatin accessibility has no dedicated original measurement enum; direct_transcriptional_regulation is used for perturbational regulatory chromatin, with exact assay retained. No gene-specific enhancer deletion or functional rescue.')
a(3,1,1,'A-FOS dominant-negative protein','P','protein','reduces','activation-inducible RNA program including IRF8, TBX21, IFNG and CSF2','T','transcriptional_program','RNA_abundance','decrease','Fig5H; Methods RNA-seq and A-FOS electroporation','A-FOS decreased an activation-inducible RNA program including IRF8, TBX21, IFNG and CSF2.',dose='25 µg A-FOS or GFP per 3.5 million cells',duration='2 h recovery then 5 h activation',time_point='5 h',assay='RNA-seq',cell_state='naive human CD4 cells activated with CD3/CD28',limitations='RNA is not secreted cytokine or cellular function. No molecule-specific translation assay; 8/18 downregulated activation-inducible genes also lost nearby chromatin opening, a correlation under shared intervention.')
a(4,1,1,'CD28 costimulation omission','C','experimental_condition','reduces','IL2 RNA','T','RNA','RNA_abundance','decrease','FigS5B,C; Fig6; Methods activation/RNA-seq','Without CD28, IL2 RNA and local activation-associated chromatin remodeling were reduced.',assay='RNA-seq; supporting ATAC/ChIP tracks',limitations='No IL2 secretion or recall-function assay inferred; the source anergy label is not itself a measured functional endpoint.',**A1CTX)
a(5,1,1,'CD28 costimulation omission','C','experimental_condition','preserves_at_many_sites','NFAT1 chromatin binding','P','protein_DNA_binding','protein_activity','mixed','FigS5D; Results Co-stimulation is required','NFAT1 binding remained detectable at most sites despite failed opening at many regions; IL2 was an exception.',assay='NFAT1 ChIP-seq with spike-in normalization',limitations='Binding persistence supports insufficiency of NFAT presence in this context, not universal NFAT dispensability. No NFAT perturbation.',**A1CTX)
KD=dict(cell_state='Unstimulated CD4 cells after siRNA transfection',dose='2 nmol siRNA cocktail per 2×10^5 cells/10 µL',stimulation='STAT5 siRNA; no further stimulation for RNA study',genomic_background='Experimentally depleted STAT5B or STAT5A; germline background unavailable')
a(6,2,2,'STAT5B siRNA depletion','G','experimental_gene_perturbation','decreases','FOXP3 RNA','T','RNA','RNA_abundance','decrease','Methods2.4; Results3.1; Fig2D','STAT5B knockdown decreased FOXP3 RNA at 24 and 72 h.',time_point='24 and 72 h',duration='24–72 h',assay='Quantitative RT-PCR',quantitative_result='Source reports 50% decrease at 24 h and 75% at 72 h',limitations='siRNA without rescue; no direct binding demonstrated in this experiment; endpoint donor matching to protein unavailable.',**KD)
a(7,2,2,'STAT5B siRNA depletion','G','experimental_gene_perturbation','decreases','FOXP3 intracellular protein','P','protein','protein_abundance','decrease','Methods2.4/flow; Results3.1; Fig2E','STAT5B depletion reduced FOXP3 protein fluorescence in gated CD4+CD25+ cells.',time_point='72 h',duration='72 h',assay='Intracellular flow cytometry',quantitative_result='43% lower FOXP3 MFI; P<0.005 reported',uncertainty='Control n=4, STAT5A n=2, STAT5B n=6',limitations='Different group sizes; no rescue and no experimental FOXP3-mediated suppression test.',**KD)
a(8,2,2,'STAT5A siRNA depletion','G','experimental_gene_perturbation','does_not_detectably_change','FOXP3 RNA','T','RNA','RNA_abundance','null','Methods2.4; Results3.1; Fig2D','STAT5A depletion did not detectably alter FOXP3 RNA in the tested unstimulated-cell conditions.',time_point='24 and 72 h',duration='24–72 h',assay='Quantitative RT-PCR',contradiction_group='MA-STAT5-PARALOG',limitations='Partial knockdown; absence of significance is not equivalence or proof of redundancy/dispensability.',**KD)
a(9,2,3,'FOXP3-positive Treg fraction across STAT5B genotypes','P','protein_expression_stratum','correlates_with','suppression of responder proliferation','F','cellular_function','cellular_phenotype','association','Methods2.2/2.7; Results3.2; Fig3','FOXP3-positive Treg fraction correlated with suppressive function across the small STAT5B genotype series.',evidence_tier='observational',cell_state='Patient-derived and control Tregs',assay='Flow cytometry and thymidine incorporation suppression assay',duration='Methods2.7 standard assay: 7 days; last16 h thymidine',time_point='After culture; per-sample temporal pairing unavailable',quantitative_result='Source r²=0.87',causal_directness='Cross-individual observational correlation; not FOXP3 mediation of STAT5B effects.',limitations='Genotype, illness, cell composition and other STAT5 targets confounded. Fig4 uses another 5-day protocol; not merged with Fig3. Patient overlap with earlier publications unresolved.')
TFCTX=dict(cell_state='Expanded human Tregs after CRISPR',dose='IL12 10 ng/mL with IL2 600 IU/mL; controls IL2 alone',duration='48 h after editing then 72 h cytokine; final 6 h PMA/ionomycin/brefeldin for arrayed flow',time_point='5 days after editing, plus final restimulation',assay='Intracellular flow cytometry; 3 gRNAs per TF; 2 donors',limitations='Intracellular accumulated cytokine, not secreted protein. Multi-gRNA consistency limits but does not remove off-target effects; no rescue.')
a(10,3,5,'FOXP3 CRISPR knockout','G','experimental_gene_perturbation','increases','intracellular IL2 and IFNG protein program','P','protein_program','protein_abundance','increase','Figs3a,b; Results Multidimensional analysis; Methods arrayed Cas9 RNP screen','FOXP3 knockout increased intracellular IL2 and IFNG, with further enhancement under IL12.',**TFCTX)
a(11,3,6,'FOXP3 CRISPR knockout','G','experimental_gene_perturbation','alters','IL12-context FOXP3-regulated RNA program','T','transcriptional_program','RNA_abundance','mixed','Figs5/6; Methods scRNA-seq and computational analysis','FOXP3 disruption changed an IL12-context RNA program distinct from several other TF modules.',dose='IL12 condition versus control as study protocol; exact scRNA culture dose/timing not repeated in scRNA Methods',duration='48 h activation before editing; final6 h PMA/ionomycin in IL2 300 IU/mL; intervening scRNA culture duration unavailable',time_point='After CRISPR/cytokine culture and 6 h restimulation',assay='10x scRNA-seq; genotype-based demultiplexing',cell_state='Tregs activated48 h before electroporation',quantitative_result='63 altered genes evaluated for enrichment against external FOXP3 ChIP targets; 24 overlapped',limitations='RNA program, not survival/function. External FOXP3-binding enrichment is not proof each altered transcript is directly regulated. Cells not donor replicates; two donors; sample-level linkage to flow unavailable.')
a(12,3,5,'TBX21 CRISPR knockout','G','experimental_gene_perturbation','reduces','IL12-induced intracellular IFNG protein','P','protein','protein_abundance','decrease','Fig1f pooled discovery; Fig2c arrayed validation; Fig4/Methods arrayed screen','TBX21 targeting reduced the IL12-induced intracellular IFNG response in human Tregs.',**TFCTX)
a(13,3,4,'IL12','P','protein','increases','intracellular IFNG protein','P','protein','protein_abundance','increase','Fig1b,f; Results Novel regulators; Methods pooled RNP screen','IL12 increased the intracellular IFNG-positive response in expanded human Tregs.',dose='10 ng/mL IL12 plus600 IU/mL IL2 versus IL2 alone',duration='72 h cytokine after48 h post-edit recovery; final4.5 h PMA/ionomycin/brefeldin',time_point='After72 h cytokine',cell_state='Expanded Tregs in pooled RNP experiment with controls',assay='Intracellular flow/FACS',limitations='No receptor or phosphorylation assay in this assertion. Pooled discovery and arrayed validation are distinct donor groups, not same-sample mediation.')
KOCTX=dict(cell_state='Expanded7 days; edited; living CD25− sorted4 days after editing',genomic_background='CRISPR IL2RA indels; sorted CD25-negative',stimulation='IL2RA CRISPR versus mock/CD25-positive controls',limitations='CD25 protein loss selected by sorting; incomplete/heterogeneous editing. pSTAT5 and suppression donor overlap unavailable. No STAT5 rescue or intermediate perturbation of suppression.')
a(14,4,7,'IL2RA CRISPR knockout','G','experimental_gene_perturbation','reduces','IL2-stimulated STAT5 phosphorylation','P','protein_modification','protein_activity','decrease','Fig4E; Methods Phosflow, nucleofection/sorting','IL2RA-deficient Tregs showed reduced STAT5 phosphorylation after IL2.',dose='IL2 100 U/mL',duration='2 h rest then15 min IL2',time_point='15 min after IL2',assay='Phospho-flow; pSTAT5 Pacific Blue reagent560311; STAT5 isoform/site not specified in prose',uncertainty='3 independent donors',**KOCTX)
a(15,4,7,'IL2RA CRISPR knockout','G','experimental_gene_perturbation','reduces','Treg suppression of CD4/CD8 responder proliferation','F','cellular_function','cellular_phenotype','decrease','Fig4F; Methods Suppression Assay','Edited CD25-negative Tregs suppressed allogeneic CD4 and CD8 responder proliferation less effectively.',dose='Treg:PBMC1:2; inspector beads:cell1:1',duration='4 days suppression coculture',time_point='4-day responder assay',assay='CFSE dilution in viable responder CD4/CD8 populations',uncertainty='3–6 independent donors',**KOCTX)
a(16,4,7,'IL2RA CRISPR knockout','G','experimental_gene_perturbation','does_not_detectably_change','FOXP3 intracellular protein','P','protein','protein_abundance','null','Fig4D; Results CD25-KO; Methods Flow Cytometry','FOXP3 protein expression did not differ detectably after CD25 sorting despite the functional/signaling deficits.',dose=U,duration='4 days after nucleofection and sorting',time_point='4 days post-edit',assay='Intracellular FOXP3 flow cytometry',contradiction_group='MA-FOXP3-NOT-FUNCTION',uncertainty='Mock n=3; CD25+ n=6; IL2RA-KO n=6',**KOCTX)
ILCTX=dict(cell_state='Freshly sorted healthy-donor CD25bright T cells',stimulation='Recombinant human IL2',dose='100 U/mL',limitations='CD25bright sorting enriches Tregs but does not itself establish function; no suppression assay for these aliquots. RNA/protein sample overlap unavailable.')
a(17,5,8,'IL2','P','protein','increases','FOXP3 RNA','T','RNA','RNA_abundance','increase','Fig1A,C; Methods IL2 induction and quantitative PCR','IL2 increased FOXP3 RNA in sorted CD4+CD25bright cells.',duration='6 h',time_point='6 h',assay='Quantitative RT-PCR normalized to TFRC',**ILCTX)
a(18,5,8,'IL2','P','protein','increases','FOXP3 protein','P','protein','protein_abundance','increase','Fig1B; Methods Western blot analysis','IL2 increased FOXP3 protein in sorted CD4+CD25bright cells.',duration='18 h',time_point='18 h',assay='FOXP3 Western blot clone236/E7; tubulin loading control',**ILCTX)
a(19,5,8,'IL2','P','protein','does_not_induce_detectable_increase','FOXP3 RNA in CD25-negative cells','T','RNA','RNA_abundance','null','Fig1A,C; Methods IL2 induction/quantitative PCR','The sorted CD4+CD25-negative preparation did not show the FOXP3 RNA response observed in CD25bright cells.',duration='6 h',time_point='6 h',assay='Quantitative RT-PCR',cell_state='Fresh CD4+CD25− sorted cells',stimulation='IL2',dose='100 U/mL',limitations='Short IL2-only exposure in a different cell state; not a universal inability to induce FOXP3. No equivalence bounds.',contradiction_group='MA-FOXP3-CELL-STATE')
a(20,6,9,'RBPJ CRISPR knockout','G','experimental_gene_perturbation','increases','iTreg suppression of responder proliferation','F','cellular_function','cellular_phenotype','increase','Public Fig3j caption; main wet-lab Methods unavailable','Primary Fig3j reports increased in vitro suppression after RBPJ ablation in human iTregs.',assay='Proliferating CD4/CD8 responder fraction per Fig3j; wet-lab Methods unavailable',uncertainty='3 donors per caption',limitations='Main wet-lab Methods inaccessible; no fully extracted function claim. Mouse GvHD data are not used.',supporting_snapshot_paths=[snap(6),'research/mechanisms_activation/snapshots/MA_S06_fig3_full.txt'])
a(21,6,9,'RBPJ overexpression with HDAC3 deletion','G','combined_gene_perturbation','tests_HDAC3_dependence_of','RBPJ-mediated FOXP3 protein repression','P','protein','protein_abundance','mixed','Public Fig4b,d,e; main wet-lab Methods unavailable','Fig4 describes RBPJ or interaction-mutant expression, HDAC3 deletion, co-immunoprecipitation and FOXP3 readouts as a proposed mediation experiment.',assay='FOXP3 flow; co-IP; main wet-lab Methods unavailable',uncertainty='Fig4e four donors',limitations='Direction/size of rescue not extracted from inaccessible main Results or uninspected figure image. Candidate hypothesis only; not support for completed mechanism.',relation='inconclusive',supporting_snapshot_paths=[snap(6),'research/mechanisms_activation/snapshots/MA_S06_fig4_full.txt','research/mechanisms_activation/snapshots/MA_S06_methods.txt'])
PBCTX=dict(cell_state='Normal-donor unfractionated PBMCs; CD4/CD8 flow gates',dose='Soluble anti-CD3 OKT3 1:800,000 dilution',stimulation='Anti-CD3 in PBMC cultures at3×10^6 cells/mL',time_point='24 h',duration='24 h',assay='FOXP3 intracellular/nuclear flow; FACSCalibur',limitations='Mixed PBMC preparation, not purified naive/Treg cells. No lineage-stable Treg identity, secretion-source attribution or suppressive function inferred.')
a(22,7,10,'CD3 triggering','C','receptor_perturbation','increases','FOXP3 intracellular protein-positive T cells','P','protein_expression_stratum','protein_abundance','increase','Fig1B,D; Methods PBMC isolation/activation and flow','Anti-CD3 increased FOXP3-positive fractions in CD4 and CD8 cells by24 h.',quantitative_result='Fig1D CD4 n=16 and CD8 n=17 paired baseline/24h comparison; qualitative direction retained',**PBCTX)
a(23,7,10,'IL2 neutralization during CD3 triggering','P','protein_blockade','reduces','FOXP3 intracellular protein induction','P','protein','protein_abundance','decrease','Fig3C,D; Fig4; Methods antibody/activation and flow','Anti-IL2 reduced CD3-induced FOXP3, and increasing exogenous IL2 competed with inhibition at lower antibody conditions.',**{**PBCTX,'dose':'AntiIL2 dose series; Fig3D1 µg/mL; IL2 competition0–10 nM','limitations':PBCTX['limitations']+' Incomplete inhibition; antibody concentration and available IL2 matter. No direct STAT5 intermediate measured.'})
a(24,7,10,'IL2 supplementation during CD25 blockade','P','protein','rescues_at_lower_blockade_dose','CD3-induced FOXP3 protein expression','P','protein','protein_abundance','increase','Fig3A,B; Fig4A,B; Methods antibody/activation and flow','Excess IL2 overcame CD25-blockade suppression of FOXP3 at lower antibody conditions, but did not overcome the high combined antiIL2/antiCD25 condition.',**{**PBCTX,'dose':'IL2 up to10 nM; Fig3B antiCD251 µg/mL; Fig4 combined antibodies1 versus10 µg/mL','limitations':PBCTX['limitations']+' Competitive rescue supports IL2/CD25 involvement; does not identify which PBMC cell supplied endogenous IL2 or establish the entire feedback loop.'})
a(25,7,10,'CD3/CD28 restimulation','C','receptor_perturbation','increases_despite_FOXP3_positive_neighbors','intracellular IL2 in FOXP3-negative CD4 cells','P','protein','protein_abundance','increase','Fig5C; TableS1 summarized in Results; Methods cytokine production','Restimulated mixed PBMC cultures retained an IL2 response in FOXP3-negative cells despite the presence of FOXP3-positive cells.',stimulation='24h antiCD3+IL2 followed by6h antiCD3/antiCD28 with brefeldin A',dose='Initial IL210 nM; antiCD2810 µg/mL',duration='24h preactivation plus6h restimulation',time_point='After6h restimulation',cell_state='Mixed activated PBMCs; CD4 gate',assay='Intracellular IL2/FOXP3 flow',quantitative_result='Across5 experiments IL2+ FOXP3− fraction rose from1.3±0.4% to12.6±2.2%; FOXP3+/negative ratio approximately1:5',limitations='No purified suppressor-responder titration or FOXP3 perturbation; cannot conclude Tregs lack suppressive function generally. Intracellular IL2 not secreted IL2.',contradiction_group='MA-FOXP3-NOT-FUNCTION')
# Every assertion remains extraction-only.
write('pack.json',dict(sources=sources,cohorts=cohorts,assertions=assertions,searches=[],gaps=[],synthesis='Bounded primary-human activation/regulatory mechanism screen. All cytokines are in scope, with receptor, transcription factor, chromatin, protein and functional mechanisms beyond ligand lists. Candidate mediation and shared-intervention branches remain distinct; no independent review or numerical priors.'))
