#!/usr/bin/env python3
"""Consolidate inspected full methods without modifying the historical corpus."""
import hashlib,json,re,runpy
from pathlib import Path
from urllib.parse import urlsplit,urlunsplit
OUT=Path(__file__).resolve().parent
u=runpy.run_path(str(OUT/'build_pack.py'))
p=u['pack'];NA=u['NA'];cohort=u['cohort'];assertion=u['assertion'];snap=u['snap'];write=u['write']
END='2026-09-13 18:24:00 UTC'
ss={s['source_id']:s for s in p['sources']};aa={a['assertion_id']:a for a in p['assertions']};cc={c['cohort_id']:c for c in p['cohorts']}
def upgrade(a,**kw):
    a.update(qc_status='reviewed_extraction',qualitative_confidence='moderate',**kw)
    a['scoring_annotation']['rationale']='Inspected primary methods and results support only this narrow assay/context proposition; independent review and human adjudication remain pending.'

ss['XCH_S001'].update(access_level='full_text_methods_results_excerpts',snapshot_path=snap('followup_fullmethods1.json'),retrieved_at='2026-09-13 17:44:23 UTC',notes='Full PDF Methods and the relevant Results/Figures 3–4 inspected; additional end of Figure 4 in followup_search6.json. PDF text extraction renders several microgram symbols as mg, so numeric antibody doses are not imported without visual verification. Human fresh-eosinophil results only; IL5-primed and mouse L1.2 experiments remain separate and unimported.')
ss['XCH_S001']['additional_snapshot_paths']=[snap('followup_search6.json')]
cc['XCH_CO001'].update(participants='Normal human eosinophil donors with moderately high eosinophil counts (approximately 3–6% of WBC)',disease='normal donors as described by study',intervention='Fresh isolated eosinophils exposed to human eotaxin or MCP4 with anti-CCR3 7B11',sample_count='Migration: at least four separate experiments; calcium: five experiments with different donors',donor_count='Five different donors represented in calcium experiments; total migration donors unavailable',notes='Figure 3–4 fresh-eosinophil experiment family. Exact cross-panel donor overlap unavailable; do not sum assays. IL5 priming (5 ng/mL, 5–7 d) belongs to a different Figure 5 experiment and is not pooled here.')
for i in (1,2,3,4):
    a=aa[f'XCH_A{i:03}'];chem=a['subject']
    common=dict(disease='normal donors as described by study',cell_state='Freshly isolated peripheral-blood eosinophils; CD16 microbead isolation, 99% purity',treatment_status='No IL5 priming in the extracted Figure 3–4 condition; donor medication unavailable',limitations='Antibody concentration unavailable in normalized data because PDF OCR corrupts microgram symbols. Donor overlap across readouts is unresolved. Dependence is restricted to these eosinophils and does not establish exclusive receptor use in other cells. The PDF calcium C5a-control prose appears inconsistent with the overall specificity interpretation; no independent calcium-control assertion is imported.')
    if i in (1,3):
        upgrade(a,**common,source_locator='Heath1997 Methods p179; Results pp180–181, Figure 3A (CCL11) or 3B (CCL13); saved followup_fullmethods1.json lines100–101,135–141,207–222,310–318.',dose='Optimal chemokine concentration, usually 12.5 nM according to Figure 3; exact ligand-specific concentration not separately reported',duration='1.5 h',time_point='1.5 h migration endpoint',assay='ECV304 transendothelial migration; 1 million eosinophils in top chamber; migrated-cell flow counts')
    else:
        upgrade(a,**common,source_locator='Heath1997 Methods p179 calcium paragraph; Results p180 and Figure 4 p182; followup_fullmethods1.json lines223–234,326–337 plus followup_search6.json lines338–345.',dose=f'10 nM {chem}; anti-CCR3 7B11 dose withheld for OCR ambiguity',duration='Antibody precedes chemokine by 40 s; C5a control added 100 s after chemokine',time_point='Acute calcium tracing after ligand addition',assay='Fura-2-loaded primary eosinophils; spectrofluorimeter calcium fluorescence')
    a['scoring_annotation']['tested_hypothesis']=f'CCR3 antibody blockade modifies {chem}-induced {a["object"]} in fresh human blood eosinophils'

ss['XCH_S003'].update(access_level='full_text_chrome_selected_passages',snapshot_path=snap('Godiska1997_chrome.txt'),retrieved_at='2026-09-13 17:54:22 UTC',notes='Full primary Methods, Results and figure legends inspected through Chrome after web-tool challenge. Selected exact visible passages saved with section/AX locators. Biological migration assays used chemically synthesized mature human MDC, distinct from CHO-expressed material used for biochemical comparisons. Western blots directly test extracellular macrophage protein.')
cc['XCH_CO004'].update(participants='Healthy human donor buffy-coat PBMC',disease='healthy donors',intervention='Chemically synthesized mature human MDC/CCL22',sample_count='Figure 7 representative experiments; dendritic-cell comparative response n=7; unit not resolved as donors',notes='Monocytes purified through Ficoll/Percoll and antiCD19/antiCD2 negative selection, then 6–8 d in 50 ng/mL GM-CSF and 20 ng/mL IL13. >80% CD1a+, >90% MHCII+. Some preparations further depleted of CD14; specific panel allocation unavailable. Donor overlap and ancestry unavailable.')
upgrade(aa['XCH_A008'],source_locator='Godiska1997 Methods Cell Culture sec5 AX204–210; Migration Assay sec6 AX221–223; Results Biological Activity sec13 AX339–349; Figure 7; Godiska1997_chrome.txt.',disease='healthy donors',cell_state='Monocyte-derived dendritic cells, culture days6–8; 50 ng/mL GM-CSF plus 20 ng/mL IL13',stimulation='Chemically synthesized mature human CCL22',dose='CCL22 dose response; significant migration from 0.1 ng/mL, maximum1 ng/mL',duration='1.5–2 h migration',time_point='1.5–2 h migration endpoint after6–8 d differentiation',assay='5 μm NeuroProbe microchamber; 27 μL lower stimulus,50 μL upper cells0.7–1.5 million/mL; five fields counted; technical triplicates',limitations='Migration is measured directly, but receptor not identified in this experiment. n=7 comparator result is not established as seven donors; panel overlap unknown. No source-to-recipient communication claim.',quantitative_result={'value':87,'unit':'percent of migration to100 ng/mL MCP3','comparator':'1 ng/mL CCL22 versus100 ng/mL MCP3','uncertainty':'±18%; error definition not explicit for this in-text aggregate; Figure7 individual examples use SE','donor_sample_basis':'n=7, experimental unit not established as unique donors','locator':'Results sec13 AX347'})

ss['XCH_S007'].update(authors='Jonathan M Viney; David P Andrew; Rhian M Phillips; Andrea Meiser; Pallavi Patel; Melissa Lennartz-Walker; David J Cousins; Nicholas P Barton; David A Hall; James E Pease',doi='10.4049/jimmunol.1300232',access_level='full_text_chrome_selected_passages',snapshot_path=snap('Viney2014_chrome.txt'),retrieved_at='2026-09-13 17:54:22 UTC',version='PMC author manuscript EMS56397, available2014-10-01; final-edited citation2014-02-21',notes='Full Experimental Procedures and relevant Results/Figures1,3 inspected. Separate human Hut78 line and primary cultured human Th2 assays. Murine L1.2 receptor-transfectant chemotaxis, binding and mutation experiments are not imported into human-primary assertions.')
for i in (10,11):
    upgrade(aa[f'XCH_A{i:03}'],source_locator='Viney2014 Experimental Procedures S3/S5/S7; Results S14, Figure1A; Viney2014_chrome.txt.',assay='5 μm ChemoTx;200,000 cells,0.1%BSA/RPMI; migrated cells assessed by counts or CellTiterGlo',duration='5 h at37°C,5%CO2',time_point='5 h migration endpoint',dose='Concentration response; complete numeric range not transcribed',limitations='Human Hut78 lymphoma line with endogenous CCR4; not primary Th2 cells. Figure1 n=3 refers to independent experiments, not independent donors. Receptor antibody experiments on transfectants elsewhere are not assigned to this assay.')
C9=cohort(9,'XCH_S007','Primary human Th2 lymphocytes; blood-derived cells','peripheral blood-derived culture','Th2 lymphocyte','Chronically activated cultured Th2 cells','healthy donor context for primary Th2 generation; calcium-specific donor metadata unavailable','Recombinant human CCL17 or CCL22',samples='Three independent calcium experiments, not equated to three unique donors',notes='Cell Culture describes healthy-volunteer naiveCD4 cells polarized4wk with ref28. Calcium Methods specifically invoke chronically activated Th2 preparation via ref30. Do not assume identical donors/preparation histories across flow and calcium panels; exact ref30 culture details remain unavailable.')
for i,chem,ec50 in [(18,'CCL17',1.6),(19,'CCL22',2.5)]:
    a=assertion(i,chem,C9,'XCH_S007','cultured human Th2 intracellular calcium mobilization','induces_intracellular_calcium_mobilization',f'{chem} elicited a calcium concentration response in chronically activated human Th2 cells.','Viney2014 Experimental Procedures Intracellular calcium flux S9; Results S15; Figure3E, Viney2014_chrome.txt.',reviewed=True,cell_state='Chronically activated primary human Th2 cells',stimulation=f'Recombinant human {chem}',dose='Concentration response; 50 nM first stimulus in separate desensitization panels',duration='Acute calcium trace; exact recording duration unavailable',time_point='Immediately following chemokine addition; numeric interval unavailable',assay='Fluo3 4 μM loading;300,000 cells/well;96-well FLIPR',causal_directness='Direct chemokine perturbation and proximal calcium response; no human-primary receptor-blockade result imported from transfectants.',limitations='n=3 experiments; unique donor count, sex and ancestry unavailable. Calcium-specific chronic Th2 culture follows ref30, whose exact schedule is not reproduced. EC50 is assay potency, not a binding affinity or a biological-truth prior.',quantitative_result={'value':ec50,'unit':'nM EC50','comparator':'Increasing ligand concentration in calcium response assay','uncertainty':'EC50 uncertainty unavailable; plotted data use mean±SEM as generic Methods convention','donor_sample_basis':'n=3 independent experiments; unique donor count unavailable','locator':'Figure3E legend'})

S9='XCH_S009'
p['sources'].append(dict(source_id=S9,title='CXCR3 and Its Ligand CXCL10 Are Expressed by Inflammatory Cells Infiltrating Lung Allografts and Mediate Chemotaxis of T Cells at Sites of Rejection',authors='Carlo Agostini; Fiorella Calabrese; Federico Rea; Monica Facco; Alicia Tosoni; Monica Loy; Gianni Binotto; Marialuisa Valente; Livio Trentin; Gianpietro Semenzato',year=2001,url='https://pmc.ncbi.nlm.nih.gov/articles/PMC1891930/',doi='10.1016/S0002-9440(10)64126-0',pmid='11337368',source_type='primary_study',version='Published article2001 May;158(5):1703–1711',retrieved_at='2026-09-13 17:51:33 UTC',access_level='full_text_chrome_selected_passages',snapshot_path=snap('Agostini2001_chrome.txt'),species='Homo sapiens',ingestion_status='extracted',notes='Full Methods and Results inspected in Chrome; selected exact visible passages saved. Human BAL T-cell migration is distinct from300-19 cell-line bioassays. Source has56 versus58 biopsy-count discrepancy, preserved below.'))
C10=cohort(10,S9,'24 lung allograft recipients:14 men,10 women','lung allograft; bronchoalveolar lavage','pulmonary CD3-positive T cell','ex vivo purified BAL T cells; acute rejection A1–A3 or BOS','acute lung allograft rejection or bronchiolitis obliterans syndrome','Recombinant human CXCL10 with or without antiCXCR3 antibody',donors='24 recipients in parent study; Figure3A–D shows four representative patients',samples='Source Methods says56 consecutive biopsy/BAL procedures, then58 biopsy samples; counts unresolved',notes='Figure3A–D human pulmonary T cells from A1,A2,A3 and BOS representatives; Figure3E300-19 line excluded. Repeated surveillance samples and assay-panel overlap unresolved; no-rejection/normal migration could not be tested because too few T cells, which is missingness rather than a null.')
tx='Postoperative rabbit antithymocyte globulin, then cyclosporinA or tacrolimus, azathioprine or RAD, and prednisone; exact patient doses unavailable'
assertion(20,'CXCL10',C10,S9,'lung-allograft BAL T-cell chemotaxis','induces_chemotaxis_sensitive_to_CXCR3_blockade','CXCL10 induced migration of rejection-associated human BAL T cells, and antiCXCR3 markedly inhibited the response.','Agostini2001 Methods sec2,sec3,sec8; Results sec13 and Figure3A–D; Agostini2001_chrome.txt.',tier='P3',reviewed=True,sex='Parent cohort14 men/10 women; Figure3 participant sex unavailable',cell_state='Ex vivo BAL T cells, >99%CD3-positive after purification',disease_severity='Acute rejection gradesA1–A3 or active BOS',treatment_status=tx,stimulation='Recombinant human CXCL10 ± anti-human CXCR3 mAb',dose='CXCL10 200 ng/mL; antiCXCR3 20 μg/mL',duration='Antibody30 min at4°C, then migration2 h at37°C',time_point='2 h migration endpoint',assay='48-well Boyden chamber; fibronectin-coated3 μm filter;50 μL of5 million cells/mL; three fields per well, technical triplicates',causal_directness='Direct ligand perturbation with receptor-antibody inhibition in primary human cells; no in vivo therapeutic effect established.',limitations='Figure3 shows four representative patients, not cohort-wide effect estimates. No-rejection T-cell migration was unavailable because of low recovery. Antibody does not establish receptor exclusivity in other cell types. CXCR3 also has other ligands. No quantitative effect transcribed from graphs.')
C11=cohort(11,S9,'Same lung allograft study; biopsy and BAL macrophage subsets','lung-allograft biopsy and bronchoalveolar lavage','alveolar macrophage','graft-infiltrating macrophages during rejection','acute rejectionA1–A3 or BOS','Observational antiCXCL10 protein staining',parent=C10,notes='Macrophage and T-cell samples belong to the same parent study. Figure4 is representativeA2 biopsy; Figure5 BAL macrophage flow panels include rejection,BOS,no-rejection and control examples. Specific overlap unavailable.')
a=assertion(21,'CXCL10',C11,S9,'CXCL10','protein_localizes_in_graft_infiltrating_macrophages','CXCL10 protein was detected in graft-infiltrating macrophages during lung-allograft rejection.','Agostini2001 Methods sec5–6; Results sec14; Figures4–5; Agostini2001_chrome.txt.',tier='P1',direction='association',measurement='protein_abundance',reviewed=True,cell_state='Graft-infiltrating alveolar macrophages',treatment_status=tx,time_point='Rejection-associated biopsy/BAL; exact time after transplant unavailable',assay='AntiCXCL10 immunohistochemistry and cytoplasmic flow staining; Figure4A2 representative',causal_directness='Observational protein localization; this assertion does not measure extracellular secretion.',limitations='Representative panels; donor/sample overlap unresolved. Conditioned-medium assays elsewhere use300-19 cell-line recipients and are not imported as primary-human target experiments.')
a.update(subject='graft-infiltrating alveolar macrophage',subject_type='cell',subject_layer='C');a['scoring_annotation']['tested_hypothesis']='CXCL10 protein is present in graft-infiltrating alveolar macrophages during the recorded lung-rejection context'
C12=cohort(12,'XCH_S003','Human peripheral-blood monocyte-derived macrophages','blood-derived cell culture supernatant','monocyte-derived macrophage','Plastic-adherent differentiation for6 d; unstimulated day6/day9 controls',NA,'Macrophage differentiation and culture-supernatant Western blot',notes='Distinct source-cell experiment family from DC chemotaxis. Donor number and relationship to healthy-buffy-coat chemotaxis donors unavailable. Day6/day9 conditions and LDL arms are not independent biological replication.')
a=assertion(22,'CCL22',C12,'XCH_S003','CCL22','secretes_extracellular_CCL22_protein','CCL22 protein was recovered from cultured human monocyte-derived macrophage supernatants by Western blot.','Godiska1997 Cell Culture sec5; Results sec11; Figure5 lanes4–5 and legend; Godiska1997_chrome.txt.',tier='P1',direction='association',measurement='secreted_protein',reviewed=True,cell_state='Human monocytes differentiated on plastic into macrophages',stimulation='No additional cytokine in the imported day6/day9 control conditions',duration='6 d differentiation; day6 and day9 supernatant observations',time_point='Culture day6 and day9',assay='Heparin–Sepharose concentration of cell-free supernatant, SDS-PAGE and antiMDC monoclonal Western blot',causal_directness='Direct extracellular protein detection; no source manipulation demonstrating a cytokine-dependent target effect.',limitations='No secretion rate, calibrated concentration, donor count or detection limit reported. LDL and epithelial-line null comparisons are retained in source but do not prove absence or equivalence. Macrophage-source donors are not presumed identical to recipient DC donors.')
a.update(subject='cultured human monocyte-derived macrophage',subject_type='cell',subject_layer='C');a['scoring_annotation']['tested_hypothesis']='Human monocyte-derived macrophages release extracellular CCL22 protein in the recorded culture context'

# Structured-context repair XCH-REV002; original review remains immutable.
aa['XCH_A010']['stimulation']='Soluble recombinant human CCL17 concentration series'
aa['XCH_A011']['stimulation']='Soluble recombinant human CCL22 concentration series'

# Provost full methods recovered after the apparently timed-out Chrome tab loaded.
ss['XCH_S002'].update(authors='Véronique Provost; Marie-Chantal Larose; Anick Langlois; Marek Rola-Pleszczynski; Nicolas Flamand; Michel Laviolette',access_level='full_text_chrome_selected_passages',snapshot_path=snap('Provost2013_chrome.txt'),retrieved_at='2026-09-13 18:07:42 UTC',notes='Complete Methods and relevant Results/Figures2,3,5 inspected in Chrome after initially timed-out navigation. Selected exact visible passages saved. Both alternative receptor use and an unantagonized CCR3 conformation remain possible; receptor independence is not established by the antibody-insensitive late component.')
cc['XCH_CO002'].update(participants='Eight recruited nonsmoking healthy volunteers with no allergy/asthma history and methacholine PC20>16 mg/mL',donor_count=8,sample_count='Figure5 four independent experiments; Figure4 four experiments; unique per-panel donor counts unavailable',notes='Study-wide recruited healthy count is eight, not four. No respiratory infection for at least1month. IL5 maintained during all migration assays. Limited cell yield allowed only18h healthy blockade measurements; not absence of earlier migration. Repeated panel donor overlap unavailable.')
cc['XCH_CO003'].update(participants='Thirty recruited nonsmoking mild allergic asthma volunteers; positive allergen prick test and asthma history≥6months',donor_count=30,disease='mild allergic asthma; methacholine PC20≤8 mg/mL',intervention='Human CCL26 after IL5 priming, with IL5 maintained; antiCCR3 clone61828/7B11 comparison',sample_count='Figure2 CCL26 kinetics seven experiments; Figure5 blockade four experiments; technical duplicates; per-panel unique donors unavailable',notes='Thirty is study recruitment, not sample size of each result. No respiratory infection for≥1month; only beta2 agonists on demand as therapy. Figure2 resolves12–18h second phase; Figure5 antibody-blockade comparison observes9–18h late interval. Panel donor overlap unresolved.')
for i in (5,6,7):
    a=aa[f'XCH_A{i:03}']
    upgrade(a,cell_state='Blood eosinophils purified by CD16 negative selection, >98.5%purity; IL5-primed and IL5 maintained throughout migration',assay='24-well BioCoat Matrigel invasion chamber,8 μm pores;500 μL of1million cells/mL inRPMI10%FBS;Scepter counts; vehicle-subtracted percent net migration; technical duplicates',dose='CCL26 100 nM; IL5 10 ng/mL; antibody when used10 μg/mL in both chambers',source_locator='Provost2013 Methods jlb0213-sec-0005–0007; Results Figure2C for kinetics or Figure5C for blockade; Provost2013_chrome.txt.',treatment_status='No respiratory infection for≥1month; asthma donors used beta2 agonists on demand only' if i!=5 else 'No allergy/asthma history; no respiratory infection for≥1month; medications unavailable',disease='mild allergic asthma' if i!=5 else 'healthy',disease_severity='mild' if i!=5 else NA,limitations='Study recruitment30 asthma/8 healthy is distinct from experimental replicates. Figure2C n=7; Figure5 n=4 per group, each in duplicate; unique donors and overlap unavailable. IL5 is continuously present and may alter response context. The late antibody-insensitive component does not establish another receptor: unantagonized CCR3 conformations remain an explicit alternative.')
aa['XCH_A005'].update(stimulation='CCL26 with or without antiCCR3 clone61828/7B11 after IL5 priming',duration='IL5 priming15min; Figure5 antibody added10min before ligand;18h migration endpoint',time_point='18 h only for healthy-donor Figure5 blockade')
aa['XCH_A006'].update(stimulation='CCL26 after15min IL5 priming, with IL5 maintained',duration='18h kinetic observation',time_point='Figure2C: early0–6h,plateau6–12h,and second phase12–18h')
aa['XCH_A007'].update(stimulation='CCL26 with antiCCR3 clone61828/7B11 and continuous IL5',duration='Figure5 antibody added10min before ligand;late blockade interval9–18h',time_point='9–18h in Figure5;12–18h second phase resolved separately by Figure2C',evidence_summary='A late increase in CCL26-induced migration remained during9–18h despite antiCCR3 treatment in mild-allergic-asthma eosinophils.',causal_directness='An antagonist-insensitive late component was observed. Possible unblocked CCR3 conformations preclude asserting complete receptor independence.')
aa['XCH_A007']['scoring_annotation'].update(evidence_relation='inconclusive',rationale='The antibody-insensitive component is directly reported, but no equivalence/precision test establishes absence of CCR3 contribution; an unblocked receptor conformation remains possible.')
for i in (5,7):aa[f'XCH_A{i:03}']['limitations']+=' Figure5 specifies10min antibody preincubation; generic Methods describe antagonist/IL5 addition together with15min priming. Figure-specific timing retained.'
ss['XCH_S006'].update(authors='DD Taub; ML Key; D Clark; SM Turcovski-Corrales',doi='10.1016/0022-1759(95)00087-q',pmid='7544817',additional_snapshot_paths=[snap('followup_search8.json')])

# Preserve actual new queries and candidate appearances with query IDs.
for qi,fn in [(5,'followup_search5.json'),(6,'followup_search6.json'),(7,'followup_search7.json')]:
    d=json.loads((OUT/'snapshots'/fn).read_text());qid=f'XCH_Q{qi:03}'
    q=dict(search_id=qid,lane='chemokine_expansion',query=json.dumps(d['queries']),database='public web search of primary sources',searched_at=d['retrieved_at']['current_time'],result_source_ids=[],screening_notes='Exact batched follow-up queries; ranked results are not exhaustive.',snapshot_path=snap(fn));p['searches'].append(q)
    for title,url in re.findall(r'^(.+?) \((https?://[^\n]+)\)$',d['result'],re.M):
        z=urlsplit(url);url=urlunsplit((z.scheme,z.netloc,z.path,'',''));sid=None
        for s in p['sources']:
            if s['url']==url or s['pmid']!=NA and f'pubmed.ncbi.nlm.nih.gov/{s["pmid"]}' in url:sid=s['source_id'];break
        decision='await_full_text';reason='Candidate screened; primary methods/host or scope unresolved, no assertion imported from this result.'
        if sid:
            q['result_source_ids'].append(sid);s=next(x for x in p['sources'] if x['source_id']==sid)
            decision='include' if s['access_level'].startswith('full_text') else 'await_full_text';reason='Same study reused for methods upgrade; not independent replication.'
        elif any(x in title.lower() for x in ['skin tissue memory','comprehensive review','terminology']):decision='exclude';reason='Background or peripheral scope; no selected primary ligand-specific assertion.'
        u['screening'].append(dict(candidate_id=f'XCH_CAN{len(u["screening"])+1:03}',query_id=qid,title=title,url=url,doi=next((s['doi'] for s in p['sources'] if s['source_id']==sid),NA),pmid=next((s['pmid'] for s in p['sources'] if s['source_id']==sid),NA),decision=decision,reason=reason))
    q['result_source_ids']=sorted(set(q['result_source_ids']))
for qi,sid,fn in [(8,'XCH_S009','Agostini2001_chrome.txt'),(9,'XCH_S007','Viney2014_chrome.txt'),(10,'XCH_S003','Godiska1997_chrome.txt')]:
    s=next(s for s in p['sources'] if s['source_id']==sid);qid=f'XCH_Q{qi:03}'
    p['searches'].append(dict(search_id=qid,lane='chemokine_expansion',query='Direct Chrome retrieval of already discovered candidate: '+s['url'],database='PMC via Chrome',searched_at=s['retrieved_at'],result_source_ids=[sid],screening_notes='Direct retrieval, not a new search or an independent study. Exact selected visible passages archived.',snapshot_path=snap(fn)))
    u['screening'].append(dict(candidate_id=f'XCH_CAN{len(u["screening"])+1:03}',query_id=qid,title=s['title'],url=s['url'],doi=s['doi'],pmid=s['pmid'],decision='include',reason='Full relevant Methods and Results inspected after Chrome retrieval; narrowly scoped assertions upgraded or added.'))
# Earlier candidate decisions describe their actual screening stage; follow-up rows record upgrades.
p['gaps']=[g for g in p['gaps'] if g['entity'] not in ('CXCL10','CCL17','all eight assigned chemokines')]
p['gaps'] += [dict(entity='CXCL10',status='remaining_bridge_gap',description='Primary human receptor-sensitive BAL T-cell migration and macrophage protein localization now extracted. Conditioned-medium300-19 cell-line bioassays show incomplete CXCL10 neutralization46–79%; no exclusive CXCL10 source-to-human-recipient route is claimed.'),dict(entity='CCL17',status='calcium_context_resolved_migration_gap',description='Primary cultured-human Th2 calcium responses now extracted separately from Hut78 chemotaxis. Exact chronic Th2 culture recipe referenced by calcium Methods remains unavailable, and transfectant receptor-blockade experiments are not relabeled primary human chemotaxis.'),dict(entity='CCL22 and other chemokines',status='partial_source_secretion_coverage',description='Human macrophage CCL22 secretion is now directly supported by supernatant Western blot. Remaining assigned chemokines lack extracted source-secretion assays; localization/RNA do not fill these gaps.'),dict(entity='CCL26',status='chrome_navigation_timeout',description='Chrome direct Wiley navigation also timed out after the earlier web403. No new full text obtained from that attempt; no assertion upgraded from this failure.')]
p['synthesis']='Primary human/context-specific chemokine expansion:22 assertions across all eight assigned ligands. Full-method extractions distinguish fresh eosinophils, cultured primary Th2 cells, Hut78 cells, monocyte-derived DCs and lung-allograft BAL T cells. Direct CCL22 macrophage secretion is separate from protein localization. CCL26 and CCL3/CCL4 preparation contrasts remain provisional; no receptor exclusivity, complete route, calibrated probability or human adjudication is claimed.'
p['gaps']=[g for g in p['gaps'] if g.get('status') not in ('chrome_navigation_timeout','mechanism_unresolved')]
p['gaps'].append(dict(entity='CCL26',status='mechanism_unresolved_after_full_methods',description='Full methods now recovered. Late antibody-insensitive migration could involve another receptor or an unantagonized CCR3 conformation. No equivalence or proof of receptor independence; study30/8 recruitment differs from per-panel experiments.'))
p['synthesis']=p['synthesis'].replace('CCL26 and CCL3/CCL4 preparation contrasts remain provisional','CCL26 full methods recovered; CCL3/CCL4 preparation contrasts remain provisional')
for qi,fn in [(11,'followup_search8.json'),(12,'followup_search9.json'),(13,'followup_search10.json')]:
    d=json.loads((OUT/'snapshots'/fn).read_text());qid=f'XCH_Q{qi:03}'
    p['searches'].append(dict(search_id=qid,lane='chemokine_expansion',query=json.dumps(d['queries']),database='public web primary-source retrieval',searched_at=d['retrieved_at']['current_time'],result_source_ids=[],screening_notes='Actual follow-up batched query; ranked candidates not exhaustive.',snapshot_path=snap(fn)))
    for title,url in re.findall(r'^(.+?) \((https?://[^\n]+)\)$',d['result'],re.M):
        z=urlsplit(url);url=urlunsplit((z.scheme,z.netloc,z.path,'',''));sid=None
        if 'jlb.0212074' in url:sid='XCH_S002'
        if '7544817' in url:sid='XCH_S006'
        if '7682337' in url:sid='XCH_S005'
        s=ss.get(sid,{});decision='include' if sid=='XCH_S002' else 'await_full_text' if sid else 'exclude'
        reason='Primary study reused for methods recovery; not independent replication.' if sid else 'Screened peripheral/background citation or unrelated study; no primary ligand-specific assertion imported.'
        u['screening'].append(dict(candidate_id=f'XCH_CAN{len(u["screening"])+1:03}',query_id=qid,title=title,url=url,doi=s.get('doi',NA),pmid=s.get('pmid',NA),decision=decision,reason=reason))
        if sid:p['searches'][-1]['result_source_ids'].append(sid)
    p['searches'][-1]['result_source_ids']=sorted(set(p['searches'][-1]['result_source_ids']))
p['searches'].append(dict(search_id='XCH_Q014',lane='chemokine_expansion',query='Re-selected existing Chrome tab1487303548: '+ss['XCH_S002']['url'],database='Wiley primary publisher through Chrome',searched_at=ss['XCH_S002']['retrieved_at'],result_source_ids=['XCH_S002'],screening_notes='Previously timed-out navigation had completed; full Methods/Results inspected.',snapshot_path=snap('Provost2013_chrome.txt')))
u['screening'].append(dict(candidate_id=f'XCH_CAN{len(u["screening"])+1:03}',query_id='XCH_Q014',title=ss['XCH_S002']['title'],url=ss['XCH_S002']['url'],doi=ss['XCH_S002']['doi'],pmid=ss['XCH_S002']['pmid'],decision='include',reason='Full Methods and Results recovered; three assertions upgraded with context and mechanistic uncertainty retained.'))
p['searches'].append(dict(search_id='XCH_Q015',lane='chemokine_expansion',query='Direct PDF retrieval of previously discovered Heath1997 primary source; open requests at lines80 and245',database='Primary JCI publisher PDF via web tool',searched_at='2026-09-13 17:44:23 UTC',result_source_ids=['XCH_S001'],screening_notes='Methods/Results retrieval documented in followup_fullmethods1.json; explicit include follow-up preserves original provisional screening history.',snapshot_path=snap('followup_fullmethods1.json')))
u['screening'].append(dict(candidate_id=f'XCH_CAN{len(u["screening"])+1:03}',query_id='XCH_Q015',title=ss['XCH_S001']['title'],url=ss['XCH_S001']['url'],doi=ss['XCH_S001']['doi'],pmid=ss['XCH_S001']['pmid'],decision='include',reason='Relevant full Methods and Results/Figures3–4 inspected; four narrow eosinophil assertions upgraded, with OCR and donor-overlap limits explicit.'))
write('pack.json',p);write('screening.json',u['screening'])
r=json.loads((OUT/'run.json').read_text());r.update(timestamp_end=END,retrieval_queries=[q['query'] for q in p['searches']],retrieval_dates=[q['searched_at'] for q in p['searches']],source_versions={s['source_id']:s['version'] for s in p['sources']},output_hash=hashlib.sha256((OUT/'pack.json').read_bytes()).hexdigest(),source_hashes={s['snapshot_path']:hashlib.sha256((u['ROOT']/s['snapshot_path']).read_bytes()).hexdigest() for s in p['sources']},followup='Chrome full-method upgrades and CXCL10 gap closure; source snapshots sanitized in place; rerun upgrade_pack.py to reproduce consolidated pack.')
r['source_hashes'].update({str(f.relative_to(u['ROOT'])):hashlib.sha256(f.read_bytes()).hexdigest() for f in (OUT/'snapshots').iterdir() if f.is_file()})
write('run.json',r)
assert len(p['assertions'])==22
assert all(c['query_id'] in {q['search_id'] for q in p['searches']} for c in u['screening'])
assert all((u['ROOT']/s['snapshot_path']).is_file() for s in p['sources'])
print(json.dumps({'sources':len(p['sources']),'cohorts':len(p['cohorts']),'assertions':len(p['assertions']),'screening_candidates':len(u['screening']),'reviewed':sum(a['qc_status']=='reviewed_extraction' for a in p['assertions']),'hash':r['output_hash']}))
