#!/usr/bin/env python3
"""Serialize bounded chemokine extraction from already saved public source responses."""
import datetime,hashlib,json,re
from pathlib import Path
from urllib.parse import urlsplit,urlunsplit

ROOT=Path(__file__).resolve().parents[2]
OUT=Path(__file__).resolve().parent
NA='unavailable'
LANE='chemokine_expansion'
START='2026-09-13 14:48:48 UTC'
END='2026-09-13 17:43:03 UTC'
def write(name,obj):
    (OUT/name).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def snap(name):return 'research/chemokine_expansion/snapshots/'+name

sources=[]
def source(i,title,authors,year,url,doi,pmid,access,file,notes,ingestion='extracted'):
    retrieval=json.loads((OUT/'snapshots'/file).read_text()).get('retrieved_at',{})
    when=retrieval.get('current_time',NA) if isinstance(retrieval,dict) else retrieval
    d=dict(source_id=f'XCH_S{i:03}',title=title,authors=authors,year=year,url=url,doi=doi,pmid=pmid,source_type='primary_study',version='published_article; exact source revision unavailable',retrieved_at=when,access_level=access,snapshot_path=snap(file),species='Homo sapiens',notes=notes,ingestion_status=ingestion)
    sources.append(d);return d['source_id']

S1=source(1,'Chemokine receptor usage by human eosinophils. The importance of CCR3 demonstrated using an antagonistic monoclonal antibody.','H Heath; S Qin; P Rao; L Wu; G LaRosa; N Kassam; PD Ponath; CR Mackay',1997,'https://pubmed.ncbi.nlm.nih.gov/9005985/','10.1172/JCI119145','9005985','abstract_and_primary_methods_excerpts','search3.json','Complete indexed PubMed abstract plus an indexed publisher PDF methods excerpt were inspected. The PDF open response in open3.json reports its existence but does not contain a complete inspected article. Primary human eosinophil results only; mouse L1.2 receptor-transfectant experiments are not imported.')
S2=source(2,'CCL26/eotaxin-3 is more effective to induce the migration of eosinophils of asthmatics than CCL11/eotaxin-1 and CCL24/eotaxin-2','Provost et al.; complete author list unavailable',2013,'https://jlb.onlinelibrary.wiley.com/doi/full/10.1189/jlb.0212074','10.1189/jlb.0212074','23532518','primary_article_excerpts_and_abstract','search3.json','Indexed publisher methods, figure-caption and results excerpts plus PubMed abstract in search1.json. Direct full-page open returned 403. The late CCR3-blockade contrast does not identify an alternative receptor.')
S3=source(3,'Human macrophage-derived chemokine (MDC), a novel chemoattractant for monocytes, monocyte-derived dendritic cells, and natural killer cells','R Godiska; D Chantry; CJ Raport; S Sozzani; P Allavena; D Leviten; A Mantovani; PW Gray',1997,'https://pubmed.ncbi.nlm.nih.gov/9151897/','10.1084/jem.185.9.1595','9151897','abstract_excerpt','search3.json','Narrow primary human monocyte-derived dendritic-cell migration result in indexed PubMed abstract. Direct PMC open returned a browser challenge; full methods were not inspected.')
S4=source(4,'Macrophage-Derived Chemokine (MDC/CCL22) and CCR4 Are Involved in the Formation of T Lymphocyte-Dendritic Cell Clusters in Human Inflamed Skin and Secondary Lymphoid Tissue','F Katou; H Ohtani; T Nakayama; K Ono; K Matsushima; A Saaristo; H Nagura; O Yoshie; K Motegi',2001,'https://pmc.ncbi.nlm.nih.gov/articles/PMC1891894/','10.1016/S0002-9440(10)64077-1','11290544','full_text_tool_response','open1.json','Methods, results and figure legends were inspected in the saved full-text browser response. Protein localization is imported; extracellular secretion and causal recruitment are not inferred from tissue proximity.')
S5=source(5,'Preferential migration of activated CD4+ and CD8+ T cells in response to MIP-1 alpha and MIP-1 beta.','DD Taub; K Conlon; AR Lloyd; JJ Oppenheim; DJ Kelvin',1993,'https://pubmed.ncbi.nlm.nih.gov/7682337/','10.1126/science.7682337','7682337','abstract','open3.json','Complete indexed PubMed abstract was inspected. Activation and subset contrasts are descriptive and condition-bound. A later methods study reports purification-dependent recovery of resting-cell mobility; this limits a general requirement for CD3 activation.')
S6=source(6,'Chemotaxis of T lymphocytes on extracellular matrix proteins: Analysis of the in vitro method to quantitate chemotaxis of human T cells',NA,1995,'https://www.sciencedirect.com/science/article/pii/002217599500087Q',NA,NA,'primary_article_excerpt','open3.json','Publisher abstract/results excerpt contrasts rapid purification with prolonged 37-degree incubation. Full methods, donor identity, concentrations and quantitative response estimates unavailable. Possible relation to the earlier Taub study is not assumed independent.')
S7=source(7,'Distinct conformations of the chemokine receptor CCR4 with implications for its targeting in allergy',NA,2014,'https://pmc.ncbi.nlm.nih.gov/articles/PMC3965571/',NA,'24563252','primary_article_results_excerpt','open3.json','Results heading and first paragraph explicitly describe endogenous-CCR4 human Hut78 lymphoma-cell chemotaxis. This is a human cell-line response, not a primary healthy Th2-cell result. Murine L1.2 transfectants and receptor assays elsewhere in the paper are not imported.')
S8=source(8,'Chemokine receptor specific for IP10 and mig: structure, function, and expression in activated T-lymphocytes.','M Loetscher; B Gerber; P Loetscher; SA Jones; L Piali; I Clark-Lewis; M Baggiolini; B Moser',1996,'https://rupress.org/jem/article/184/3/963/50973/Chemokine-receptor-specific-for-IP10-and-mig','10.1084/jem.184.3.963',NA,'abstract','search2.json','CXCL10 candidate only. Abstract describes a cloned human receptor and calcium/chemotaxis responses, but does not resolve the host for each functional experiment. No primary-human CXCL10 functional assertion is extracted from this abstract.','await_full_text')

cohorts=[]
def cohort(i,source_id,participants,tissue,cell,state,disease,intervention,donors=NA,samples=NA,parent=NA,notes='Donor overlap with other reports unavailable; do not count as independent replication.'):
    cid=f'XCH_CO{i:03}'
    cohorts.append(dict(cohort_id=cid,dataset_id=NA,accession=NA,study_id=source_id,participants=participants,ancestry=NA,species='Homo sapiens',tissue=tissue,cell_type=cell,disease=disease,intervention=intervention,sample_count=samples,donor_count=donors,parent_cohort=parent,related_publications=[source_id],independence_status='unresolved',notes=notes+' Cell state: '+state))
    return cid
C1=cohort(1,S1,'Human eosinophil donors; abstract includes allergic and eosinophilic individuals','peripheral blood','eosinophil','Fresh and IL5-primed conditions are discussed; exact condition per extracted response unavailable','allergic/eosinophilic and other donor groups; unresolved separation','Recombinant chemokines with anti-CCR3 7B11',notes='Same donor pool reused across ligand/readout assertions. The number tested for each functional experiment was not extracted; transfectant data excluded.')
C2=cohort(2,S2,'Healthy human subjects','peripheral blood','eosinophil','IL5-primed','healthy','Recombinant eotaxins; anti-CCR3 antibody',samples='Four independent experiments for the 18-h comparison; donor count not equated to experiments')
C3=cohort(3,S2,'Human subjects with asthma','peripheral blood','eosinophil','IL5-primed','asthma','Recombinant eotaxins; anti-CCR3 antibody',samples='Seven independent experiments for the 18-h comparison; donor count not equated to experiments',notes='Healthy and asthma groups are separated. Overlap of donors across comparison and kinetic panels is unavailable; late and total responses remain one study pool.')
C4=cohort(4,S3,'Human monocyte-derived dendritic cells; donor recruitment unavailable','blood-derived culture','monocyte-derived dendritic cell','differentiated in vitro; exact protocol unavailable',NA,'Recombinant human MDC/CCL22')
C5=cohort(5,S4,'Oral-cancer patients with autotransplanted forearm skin; infected inflamed skin-flap subset','intraoral autotransplanted forearm skin','CD1a-positive or CD83-positive dendritic cell','in situ inflamed dermis','Candida-associated inflammation after oral-cancer surgery','Observational immunostaining; no chemokine perturbation',samples='23 skin-flap biopsies, 17 severely inflamed; selected figure experiments used subsets',notes='Skin biopsies obtained about two years after surgery. Eight representative cases used for double enzyme staining; immunoelectron Methods mention four cases whereas Figure 7 legend says five. Exact overlap unavailable; do not sum panel counts.')
C6=cohort(6,S5,'Human T lymphocytes; donor details unavailable','peripheral blood; isolation details unavailable','T lymphocyte','anti-CD3-activated or unstimulated comparators',NA,'Recombinant human MIP1alpha/CCL3 or MIP1beta/CCL4',notes='Activated and unstimulated assertions are conditions from one report, not independent donor cohorts. Purification dependence is an explicit unresolved confound informed by XCH_S006.')
C7=cohort(7,S6,'Human T lymphocytes; donor details unavailable','peripheral blood; purification protocol comparison','T lymphocyte','rapidly purified, without anti-CD3 stimulation',NA,'Recombinant chemokines in microchemotaxis assays',notes='Possible donor/study relation to XCH_S005 unresolved. Rapid isolation and prolonged 37-degree incubation are distinct experimental contexts.')
C8=cohort(8,S7,'Hut78 human T-cell lymphoma line','cell culture','Hut78 T-cell lymphoma cell','endogenous CCR4 expression','T-cell lymphoma-derived cell line','Soluble CCL17 or CCL22',donors='not applicable; immortalized cell line',notes='Hut78 is human. Primary Th2 cells and murine receptor-transfected L1.2 cells elsewhere in the article are not treated as this cohort; repeated ligand assays are not independent biological replication.')

FIELDS='species ancestry age sex tissue disease disease_severity treatment_status cell_type cell_state developmental_state stimulation dose duration assay genomic_background time_point effect_size effect_unit uncertainty causal_directness limitations contradiction_group candidate_path'.split()
assertions=[]
def assertion(i,chem,co,source_id,obj,predicate,summary,locator,tier='P2',direction='increase',measurement='cellular_phenotype',reviewed=False,**extra):
    ctx=next(c for c in cohorts if c['cohort_id']==co)
    a={k:NA for k in FIELDS}
    a.update(assertion_id=f'XCH_A{i:03}',subject=chem,subject_type='protein',subject_layer='P',subject_species='Homo sapiens',object=obj,object_type='cellular_phenotype' if measurement=='cellular_phenotype' else 'protein',object_layer='F' if measurement=='cellular_phenotype' else 'P',object_species='Homo sapiens',predicate=predicate,measurement=measurement,direction=direction,source_id=source_id,cohort_id=co,evidence_tier=tier,evidence_summary=summary,source_locator=locator,species='Homo sapiens',tissue=ctx['tissue'],cell_type=ctx['cell_type'],disease=ctx['disease'],qc_status='reviewed_extraction' if reviewed else 'needs_full_text',qualitative_confidence='moderate' if reviewed else 'low',causal_directness='Ligand-response experiment limited to the stated cells and assay; receptor identity not assigned without direct blockade.',limitations='Full methods and donor-level precision were not recovered; no in vivo or cross-context generalization.')
    a.update(extra)
    a['scoring_annotation']={'tested_hypothesis':f'{chem} affects {obj} in the explicitly recorded context of {a["assertion_id"]}', 'evidence_relation':'inconclusive' if direction=='null' else 'supports','null_adequacy':NA,'rationale':'Nonsignificant/undetected response is not equivalence or evidence of biological absence.' if direction=='null' else 'Supports only the stated directly reported response; full-text and independent review gates remain applicable.'}
    assertions.append(a);return a

# No priming/dose/readout condition is invented from the pooled eosinophil abstract.
assertion(1,'CCL11',C1,S1,'eosinophil chemotaxis','induces_chemotaxis_blocked_by_CCR3_antibody','Eotaxin-induced eosinophil migration was inhibited by anti-CCR3 7B11.','PubMed abstract: pretreatment/chemotaxis sentences; search3.json. Publisher PDF methods excerpt: Chemokines, chemotaxis assays, and ligand-binding assay.',tier='P3',stimulation='CCL11 with or without anti-CCR3 7B11',assay='ECV304 transendothelial migration assay with migrated-cell flow counts',causal_directness='Pharmacological CCR3 dependence in primary human eosinophils; not receptor exclusivity in other cells.')
assertion(2,'CCL11',C1,S1,'eosinophil intracellular calcium mobilization','induces_calcium_flux_blocked_by_CCR3_antibody','Anti-CCR3 pretreatment inhibited the eosinophil calcium response to eotaxin.','PubMed abstract: pretreatment/calcium-flux sentence; search3.json.',tier='P3',stimulation='CCL11 with or without anti-CCR3 7B11',assay='Intracellular calcium flux; full ligand-specific protocol unavailable',causal_directness='CCR3 antagonist-sensitive proximal response; no downstream transcription inferred.')
assertion(3,'CCL13',C1,S1,'eosinophil chemotaxis','induces_chemotaxis_blocked_by_CCR3_antibody','MCP4-induced eosinophil chemotaxis was inhibited by CCR3 blockade.','PubMed abstract: all CCR3-ligand chemotaxis sentence and named MCP4 response sentence; search3.json.',tier='P3',stimulation='CCL13 with or without anti-CCR3 7B11',assay='ECV304 transendothelial migration assay with migrated-cell flow counts',limitations='Same donor pool as CCL11 observations. CCR3 dependence in eosinophils does not exclude CCR2-mediated CCL13 responses in other cellular systems.')
assertion(4,'CCL13',C1,S1,'eosinophil intracellular calcium mobilization','induces_calcium_flux_blocked_by_CCR3_antibody','The MCP4 eosinophil calcium response was sensitive to anti-CCR3 pretreatment.','PubMed abstract: all-ligand calcium-flux and named MCP4 sentences; search3.json.',tier='P3',stimulation='CCL13 with or without anti-CCR3 7B11',assay='Intracellular calcium flux; full ligand-specific protocol unavailable',limitations='CCR3 dependence is cell-specific. Distinct CCR2/CCR3 transfectant results in candidate Garcia-Zepeda 1996 await full-text extraction.')
assertion(5,'CCL26',C2,S2,'healthy-donor eosinophil migration','induces_migration_sensitive_to_CCR3_blockade','CCL26-induced migration in healthy-donor eosinophils was blocked by anti-CCR3.','Publisher Figure 5 discussion and PubMed abstract healthy-subject blockade sentence; search3.json and search1.json.',tier='P3',cell_state='IL5-primed',stimulation='CCL26 after IL5 priming; anti-CCR3 comparison',dose='100 nM CCL26; 10 ng/mL IL5 priming for 15 min',duration='18 h migration',time_point='18 h',assay='In vitro migration apparatus; complete setup not inspected',limitations='Healthy comparison uses four independent experiments, not an established four-donor cohort. Antibody concentration and per-panel donor overlap unavailable.')
assertion(6,'CCL26',C3,S2,'asthma-donor eosinophil migration','induces_biphasic_migration','Asthmatic-donor eosinophils showed early and delayed migration phases with CCL26.','PubMed abstract 0–6 h/12–18 h sentences; publisher late-phase Results excerpt; search1.json and search3.json.',cell_state='IL5-primed',stimulation='CCL26 after IL5 priming',dose='100 nM CCL26; 10 ng/mL IL5 priming for 15 min',duration='18 h observation',time_point='early 0–6 h and delayed 12–18 h',assay='In vitro migration kinetics',limitations='Temporal pattern is an observed phenotype, not a temporal prior or a newly identified receptor. Comparison-caption experiment counts are not substituted for kinetic-panel donor counts.')
assertion(7,'CCL26',C3,S2,'late asthma-donor eosinophil migration','late_phase_not_detectably_inhibited_by_CCR3_antibody','Anti-CCR3 did not inhibit the reported delayed CCL26 migration phase in asthma donors.','Publisher Results heading: CCR3 blockade does not inhibit the late phase; PubMed abstract; search3.json and search1.json.',direction='null',cell_state='IL5-primed',stimulation='CCL26 with anti-CCR3 antibody',dose='100 nM CCL26; antibody concentration unavailable',duration='12–18 h late phase within 18-h assay',time_point='12–18 h',assay='In vitro migration kinetics with receptor-blocking antibody',causal_directness='An antagonist-insensitive component was observed; neither complete absence of CCR3 contribution nor a named alternative receptor is established.',limitations='No equivalence margin, confidence interval or blockade-efficiency estimate extracted. Antagonist selectivity limitations are reported for other tested small molecules.',contradiction_group='XCH_CCL26_CCR3_CONTEXT')
assertions[-1]['scoring_annotation']['tested_hypothesis']='CCR3 antibody blockade modifies CCL26-induced late migration in the specified asthma-donor eosinophil context'
assertion(8,'CCL22',C4,S3,'monocyte-derived dendritic-cell migration','induces_migration','Human monocyte-derived dendritic cells migrated to MDC in microchamber assays.','Indexed PubMed abstract: microchamber migration sentence; search3.json.',dose='Maximal response reported at 1 ng/mL CCL22',assay='Microchamber migration assay',cell_state='differentiated monocyte-derived dendritic cells; maturation conditions unavailable',limitations='Receptor dependence is not established by this excerpt. Cell preparation, donor count, migration time and uncertainty unavailable.')
a=assertion(9,'CCL22',C5,S4,'CCL22','protein_localizes_in_inflamed_skin_dendritic_cells','CCL22 protein was localized within CD1a-positive or CD83-positive dermal dendritic cells.','Results Immunohistochemical Localization and Figure 7 B–D legend; open1.json lines 187–191 and 223–225.',tier='P1',direction='association',measurement='protein_abundance',reviewed=True,assay='Double immunostaining and immunoelectron microscopy',cell_state='in situ dendritic cells in infected inflamed skin-flap dermis',stimulation='Candida-associated tissue inflammation; no experimental cytokine treatment',time_point='Skin-flap biopsies approximately two years after primary surgery',causal_directness='Observational protein localization; extracellular secretion and T-cell recruitment were not directly measured.',limitations='Immunoelectron microscopy subset counts differ between Methods and legend. Localization in secretory compartments is not a secretion-rate assay.')
a.update(subject='CD1a-positive or CD83-positive dermal dendritic cell',subject_type='cell',subject_layer='C')
a['scoring_annotation']['tested_hypothesis']='CCL22 protein is present in CD1a-positive or CD83-positive dendritic cells in the specified inflamed human skin context'
assertion(10,'CCL17',C8,S7,'Hut78 T-cell lymphoma-cell chemotaxis','induces_dose_dependent_chemotaxis','Hut78 cells migrated toward soluble CCL17 with a bell-shaped concentration response.','Results first subsection, first paragraph and Figure 1A reference; open3.json.',cell_state='Endogenous CCR4-positive human lymphoma line',assay='Chemotaxis assay; detailed protocol not inspected',limitations='Hut78 is a human cancer cell line, not primary Th2 cells. No antagonist dependence or donor transportability imported from other experiments.')
assertion(11,'CCL22',C8,S7,'Hut78 T-cell lymphoma-cell chemotaxis','induces_dose_dependent_chemotaxis','Hut78 cells also migrated toward soluble CCL22.','Results first subsection, first paragraph and Figure 1A reference; open3.json.',cell_state='Endogenous CCR4-positive human lymphoma line',assay='Chemotaxis assay; detailed protocol not inspected',limitations='Same cell-line experiment family as CCL17; not independent replication. Relative potency is not quantified from the excerpt.')
for chem,start,subset in [('CCL3',12,'predominantly CD8-positive'),('CCL4',15,'CD4-positive')]:
    assertion(start,chem,C6,S5,f'{subset} T-cell chemotaxis','induces_migration_in_CD3_activated_T_cells',f'{chem} attracted {subset} T cells in the anti-CD3-activated condition.','PubMed abstract: activation requirement and phenotype-analysis sentences; open3.json.',cell_state='anti-CD3-activated',stimulation=f'Recombinant human {chem} after anti-CD3 activation',assay='T-cell chemotaxis with migrated-cell phenotyping',limitations='Subset tendency is not exclusivity. Activation duration, ligand dose and purification protocol unavailable; purification dependence described in XCH_S006.')
    assertion(start+1,chem,C6,S5,'unstimulated T-cell chemotaxis','no_attraction_reported_in_unstimulated_condition',f'Unstimulated T cells did not show attraction to {chem} under the reported preparation conditions.','PubMed abstract: did not attract unstimulated lymphocytes sentence; open3.json.',direction='null',cell_state='unstimulated comparator; isolation/culture history unavailable',stimulation=f'Recombinant human {chem}; no anti-CD3 stimulation',assay='T-cell chemotaxis',limitations='No equivalence or detection-threshold evidence. A later purification study reports unstimulated-cell responses after rapid isolation, so this is not a universal resting-cell nonresponse.',contradiction_group=f'XCH_{chem}_PREPARATION_CONTEXT')
    assertion(start+2,chem,C7,S6,'rapidly purified unstimulated T-cell chemotaxis','induces_migration_after_rapid_purification_without_CD3',f'Rapidly purified T cells responded to {chem} without anti-CD3 stimulation.','Publisher excerpt: Rapidly purified T cells sentence; open3.json.',cell_state='rapidly purified; no anti-CD3 stimulation',stimulation=f'Recombinant human {chem}',assay='Microchemotaxis assay with extracellular-matrix/purification comparison',limitations='Exact ligand-specific dose, donor count and magnitude unavailable. Prolonged 37-degree incubation reduced mobility in this methods study; no intrinsic activation requirement is inferred.',contradiction_group=f'XCH_{chem}_PREPARATION_CONTEXT')

searches=[]
query_files=[('XCH_Q001','search1.json'),('XCH_Q002','search2.json'),('XCH_Q003','search3.json'),('XCH_Q004','open3.json')]
for qid,fn in query_files:
    data=json.loads((OUT/'snapshots'/fn).read_text());queries=data.get('queries',[])
    if fn=='search1.json':queries=[x.get('q',x) if isinstance(x,dict) else x for x in queries]
    retrieved=data.get('retrieved_at',{});when=retrieved.get('current_time',NA) if isinstance(retrieved,dict) else retrieved
    searches.append(dict(search_id=qid,lane=LANE,query=json.dumps(queries,ensure_ascii=False),database='public web search; primary publisher/PubMed/PMC indexed results',searched_at=when,result_source_ids=[],screening_notes='One batched search with the exact component queries listed. Ranked results are not exhaustive; screening below preserves repeated candidate appearances by query.',snapshot_path=snap(fn)))

# Preserve every returned candidate heading actually screened. Strip query strings
# from citation URLs: signed delivery parameters are not scientific identifiers.
screening=[]
included={s['url']:s['source_id'] for s in sources if s['ingestion_status']=='extracted'}
alias_sources={'https://pmc.ncbi.nlm.nih.gov/articles/PMC2196293/':S3,'https://pubmed.ncbi.nlm.nih.gov/23532518/':S2,'https://pubmed.ncbi.nlm.nih.gov/24563252/':S7}
for qid,fn in query_files:
    text=json.loads((OUT/'snapshots'/fn).read_text())['result']
    matches=re.findall(r'^(.+?) \((https?://[^\n]+)\)$',text,re.M)
    for title,url in matches:
        parsed=urlsplit(url);url=urlunsplit((parsed.scheme,parsed.netloc,parsed.path,'',''))
        sid=included.get(url,alias_sources.get(url))
        host=parsed.netloc.lower()
        if sid:
            s=next(s for s in sources if s['source_id']==sid)
            decision='include' if s['access_level']=='full_text_tool_response' else 'await_full_text'
            reason='Included narrow protein-localization extraction from inspected full text.' if decision=='include' else 'Narrow reported results retained as provisional assertions; full methods/context review remains required.'
        elif any(x in host for x in ('wikipedia.org','patent','rndsystems.com','leinco.com','catalogimages.wiley.com')):
            decision='exclude';reason='Encyclopedia, patent, commercial reagent information or book excerpt; not selected primary experimental evidence.'
        elif any(x in title.lower() for x in ('surrogate antibod','engagement of two distinct binding','chemokines enhance immunity')):
            decision='exclude';reason='Inspected description concerns mouse ligands/mouse chemotaxis or nonhuman in vivo work; not used as primary human functional evidence.'
        elif any(x in title.lower() for x in ('comprehensive review','regulation and modulation','regulation of eosinophil recruitment','eotaxin-1 (ccl11)')):
            decision='exclude';reason='Review/background result; no new primary assertion extracted.'
        else:
            decision='await_full_text';reason='Potentially relevant candidate or contextual method study; full text, assay host and exact ligand-specific primary results not resolved within the bounded retrieval.'
        d=dict(candidate_id=f'XCH_CAN{len(screening)+1:03}',query_id=qid,title=title,url=url,doi=NA,pmid=NA,decision=decision,reason=reason)
        if sid:
            d.update(doi=s['doi'],pmid=s['pmid']);next(q for q in searches if q['search_id']==qid)['result_source_ids'].append(sid)
        elif 'pubmed.ncbi.nlm.nih.gov' in host:
            d['pmid']=parsed.path.strip('/') if parsed.path.strip('/').isdigit() else NA
        screening.append(d)
for q in searches:q['result_source_ids']=sorted(set(q['result_source_ids']))

gaps=[
 {'entity':'CXCL10','status':'await_full_text','description':'No directly extracted primary-human functional assertion. Loetscher1996 receptor abstract does not assign host/context to each functional experiment; Agostini lung-allograft candidate contains an accessible assay-method snippet but inspected result content was insufficient.'},
 {'entity':'CCL17','status':'primary_human_gap','description':'The retained human Hut78 response is a lymphoma-cell-line result. Primary human Th2 chemotaxis, donor context and receptor-blockade experiments remain unextracted.'},
 {'entity':'CCL13','status':'receptor_redundancy_gap','description':'Eosinophil CCR3 blockade does not establish exclusive receptor use. Garcia-Zepeda1996 CCR2/CCR3 and Stellato1997 CCR2 transfectant candidates await host-specific full-text extraction.'},
 {'entity':'CCL26','status':'mechanism_unresolved','description':'The late asthma-specific antagonist-insensitive component is not assigned to another receptor. Blockade adequacy, antibody dose and panel donor overlap remain incomplete.'},
 {'entity':'CCL3; CCL4','status':'preparation_context_gap','description':'1993 activation contrast and 1995 rapid-purification response are retained separately. They cannot establish a universal activation prerequisite; cohort overlap and exact purification details await full text.'},
 {'entity':'all eight assigned chemokines','status':'source_secretion_gap','description':'No new extracellular source-cell secretion assay was extracted. Tissue protein localization and transcript expression are not relabeled secretion.'},
 {'entity':'all','status':'bounded_access','description':'Entrez and PMC helper scripts failed with missing requests in both system and bundled Python; direct public shell retrieval hit sandbox DNS failure and stalled approval. No file was downloaded by that attempted call. Several browser opens returned challenges/403; only actual saved response access levels are claimed.'},
 {'entity':'all','status':'independence_unresolved','description':'Donor counts, ancestry, repeated-donor overlap and experimental precision were incompletely accessible. All cohort independence statuses remain unresolved; cell-line repeats are not donor replication.'}
]
pack=dict(sources=sources,cohorts=cohorts,assertions=assertions,searches=searches,gaps=gaps,synthesis='Bounded primary-source extraction for seven of eight assigned chemokines: 17 assertions, most provisional pending full methods. CCR3-sensitive eosinophil responses and disease/preparation-dependent contrasts are retained. Human tissue CCL22 localization is distinct from secretion; Hut78 chemotaxis is distinct from primary-cell evidence. CXCL10 remains a source-backed retrieval gap. No numerical prior, complete pathway, receptor exclusivity or human adjudication is claimed.')
write('pack.json',pack);write('screening.json',screening)
write('retrieval_limits.json',dict(timestamp_start=START,timestamp_end=END,transport_attempts=[{'transport':'ncbi-entrez-skill helper, system Python','result':'missing_dependency: requests'},{'transport':'ncbi-entrez-skill helper, bundled Python','result':'missing_dependency: requests'},{'transport':'ncbi-pmc-skill helper, bundled Python','result':'missing_dependency: requests'},{'transport':'public PMC curl in sandbox','result':'Could not resolve host; exit code 6'},{'transport':'escalated public PMC curl','result':'Stalled approval/tool turn interrupted; no downloaded snapshot present'}],snapshot_policy='Existing real browser/search responses referenced in place; no duplicate raw snapshot created. Coordinator may sanitize irrelevant signed URL metadata and re-hash bundles before review.'))
write('run.json',dict(run_id='XCH_RUN_20260913_01',agent_role='chemokine_expansion_extractor',timestamp_start=START,timestamp_end=END,timezone='America/New_York',LLM_provider='OpenAI',LLM_model=NA,model_snapshot_if_available=NA,reasoning_mode=NA,protocol_version='0.2.0',agent_prompt_version='EXTRACTION_CONTRACT_0.2',instruction_bundle_hash=hashlib.sha256(b''.join((ROOT/p).read_bytes() for p in ['README.md','research/EXTRACTION_CONTRACT.md','research/EXTRACTION_CONTRACT_0.2.md'])).hexdigest(),source_versions={s['source_id']:s['version'] for s in sources},retrieval_queries=[q['query'] for q in searches],retrieval_dates=[q['searched_at'] for q in searches],source_hashes='Computed centrally after any source metadata sanitation; exact snapshot paths in source registry.',code_commit=NA,environment_hash=NA,output_hash=sha(OUT/'pack.json'),critic_run_ids=[],human_edits=NA,skills_used=['research-router-skill','ncbi-entrez-skill','ncbi-pmc-skill'],transport_limits='See retrieval_limits.json. Runtime clock advanced during interrupted/stalled tools; start/end are observed UTC readings, not inferred durations.',human_adjudication_status='pending'))

# Deliberately shallow local integrity checks; all biology remains independently reviewable.
assert len({a['assertion_id'] for a in assertions})==len(assertions)
assert all(c['query_id'] in {q['search_id'] for q in searches} for c in screening)
assert all((ROOT/s['snapshot_path']).is_file() for s in sources)
assert all(a['scoring_annotation']['evidence_relation']=='inconclusive' for a in assertions if a['direction']=='null')
print(json.dumps({'sources':len(sources),'cohorts':len(cohorts),'assertions':len(assertions),'screening_candidates':len(screening),'qc_counts':{q:sum(a['qc_status']==q for a in assertions) for q in ['reviewed_extraction','needs_full_text']}}))
