import json, hashlib, xml.etree.ElementTree as ET
from pathlib import Path
U="unavailable"
BASE=Path("research/cytokine")
DATE="2026-09-12"
def metadata(pmc):
    a=ET.parse(BASE/"snapshots"/(pmc+".xml")).getroot()
    ids={i.attrib.get("pub-id-type"):i.text for i in a.findall("./front/article-meta/article-id")}
    names=[]
    for n in a.findall("./front/article-meta/contrib-group/contrib/name"):
        names.append(" ".join(n.findtext(k,"") for k in ["given-names","surname"]).strip())
    return ids,names
sources=[]
def source(i,title,year,url,doi,pmid,kind,version,snapshot,species,notes,authors=U,access="full_text"):
    sources.append(dict(source_id=i,title=title,authors=authors,year=year,url=url,doi=doi,pmid=pmid,source_type=kind,version=version,retrieved_at=DATE,access_level=access,snapshot_path="research/cytokine/snapshots/"+snapshot,species=species,notes=notes))
source("C-S01","Dictionary of immune responses to cytokines at single-cell resolution",2024,"https://www.nature.com/articles/s41586-023-06816-9","10.1038/s41586-023-06816-9","38057668","primary_study","Online 2023-12-06; Nature 625 (2024); PMC10781646.1","PMC10781646.xml","Mus musculus","Mouse in-vivo atlas. Human applications are inferred transport, not human perturbation replication.",metadata("PMC10781646")[1])
source("C-S02","A single-cell cytokine dictionary of human peripheral blood",2025,"https://pmc.ncbi.nlm.nih.gov/articles/PMC12724453/","10.64898/2025.12.12.693897",U,"preprint","bioRxiv v1, 2025-12-15","open1.json","Homo sapiens","bioRxiv API snapshot hcd_biorxiv_api.json: version 1, published=NA. Same 12-donor experiment as C-S09. Primary retrieved bioRxiv text includes Fig.1 results; Research Square mirror full text separately retained.","Lukas Oesinghaus et al.","full_text_sections_via_web_tool")
source("C-S03","Systematic investigation of cytokine signaling activity at the tissue and single-cell levels",2021,"https://pmc.ncbi.nlm.nih.gov/articles/PMC8493809/","10.1038/s41592-021-01274-5",U,"resource","Nature Methods 18, 1181–1191 (2021); author manuscript PMC8493809","open6.json",["Homo sapiens","Mus musculus"],"CytoSig signatures are computational estimates. Extracted wet-lab validation concerns human A549 cancer cells; exclude mouse validation and pooled 20,591 profiles from independent human cohort counts.","Peng Jiang et al.","full_text_sections_via_web_tool")
source("C-S04","Interleukin 10(IL-10) inhibits cytokine synthesis by human monocytes: an autoregulatory role of IL-10 produced by monocytes",1991,"https://pubmed.ncbi.nlm.nih.gov/1940799/","10.1084/jem.174.5.1209","1940799","primary_study","J Exp Med 174(5):1209–1220; PMC2119001.1","PMC2119001.xml","Homo sapiens","Full article supplied as OCR preformatted text in XML; abstract cross-checked. Exact OCR numeric table values not used as estimates.",["R de Waal Malefyt","J Abrams","B Bennett","C G Figdor","J E de Vries"],"full_text_OCR")
source("C-S05","Activated signal transducer and activator of transcription-3 (STAT3) is a poor regulator of tumour necrosis factor-α production by human monocytes",2007,"https://pmc.ncbi.nlm.nih.gov/articles/PMC1810496/","10.1111/j.1365-2249.2006.03291.x","17302908","primary_study","Clin Exp Immunol 147(3):564–572; PMC1810496.1","PMC1810496.xml","Homo sapiens","NCBI XML contains front matter and abstract only; web full-text access returned CAPTCHA. Search excerpts do not replace full-text review.",metadata("PMC1810496")[1],"abstract_metadata")
source("C-S06","Transpresentation of interleukin-15 by IL-15/IL-15Rα mRNA-engineered human dendritic cells boosts antitumoral natural killer cell activity",2015,"https://pmc.ncbi.nlm.nih.gov/articles/PMC4792546/","10.18632/oncotarget.6536","26675759","primary_study","Oncotarget 6(42):44123–44133, 2015-12-09","open2.json","Homo sapiens","Full-text methods and metadata also in metadata.json. Healthy-donor experiments extracted; AML remission validation is registered separately and not pooled. IFNG method is intracellular staining, despite abstract secretion wording.","Johan Van den Bergh et al.","full_text_sections_via_web_tool")
source("C-S07","Distinct roles of IL-12 and IL-15 in human natural killer cell activation by dendritic cells from secondary lymphoid organs",2004,"https://pmc.ncbi.nlm.nih.gov/articles/PMC534504/","10.1073/pnas.0407522101","15536127","primary_study","PNAS 101(47):16606–16611; PMC534504.1","PMC534504.xml","Homo sapiens","NCBI XML contains abstract only. Detailed Fig.4/5 excerpts retained in search3.json, still flagged for full-text review.",metadata("PMC534504")[1],"abstract_plus_search_excerpts")
source("C-S08","Residual Type 1 Immunity in Patients Genetically Deficient for Interleukin 12 Receptor β1 (IL-12Rβ1): Evidence for an IL-12Rβ1–Independent Pathway of IL-12 Responsiveness in Human T Cells",2000,"https://pmc.ncbi.nlm.nih.gov/articles/PMC2193232/","10.1084/jem.192.4.517","10952721","primary_study","J Exp Med 192(4):517–528; PMC2193232.1","PMC2193232.xml","Homo sapiens","Expanded T-cell clones and PHA blasts are separate contexts. Patients P1/P3/P4 were previously reported, so later publications must not count them again.",metadata("PMC2193232")[1])
source("C-S09","A single-cell cytokine dictionary of human peripheral blood",2025,"https://pmc.ncbi.nlm.nih.gov/articles/PMC12776526/","10.21203/rs.3.rs-8337240/v1","41510257","preprint","Research Square v1; PMC12776526.1","PMC12776526.xml","Homo sapiens","Duplicate preprint of C-S02, resolved by same title/authors, 12 donors, 9,697,974 cells, 90 cytokines, methods and Fig.1 findings. No independent assertion weight.",metadata("PMC12776526")[1])
cohorts=[]
def cohort(i,study,**kw):
    d={k:U for k in ["cohort_id","dataset_id","accession","study_id","participants","ancestry","species","tissue","cell_type","disease","intervention","sample_count","donor_count","parent_cohort","related_publications","notes"]}
    d.update(cohort_id=i,study_id=study,species="Homo sapiens",independence_status="unresolved",related_publications=[study]);d.update(kw);cohorts.append(d)
cohort("C-CO01","C-S01",dataset_id="C-D01",accession="GSE202186",species="Mus musculus",participants="female C57BL/6 mice",tissue="skin-draining inguinal lymph node",cell_type="multiple immune cell types",disease="healthy",intervention="86 recombinant cytokines; PBS controls",sample_count="3 mice per cytokine; 14 PBS mice",donor_count="3 independent mice per cytokine",notes="Biological replicates are mice, not 386,703 sequenced cells. HCD reanalysis is not replication.")
cohort("C-CO02","C-S02",dataset_id="C-D02",participants=12,tissue="peripheral blood",cell_type="PBMC",disease="healthy",intervention="90 individual cytokines or PBS, 24 hours",sample_count="9,697,974 QC-passing cells; cells are not independent donors",donor_count=12,related_publications=["C-S02","C-S09"],independence_status="resolved",notes="C-S02/C-S09 are duplicate preprints for one experiment. Donor identifiers D1–D12; 6 males and 6 females, ages 34–75. Resolution limited to this known duplicate pair.")
cohort("C-CO03","C-S03",dataset_id="C-D03",participants="A549 cell line",tissue="lung",cell_type="A549 lung epithelial carcinoma cells",disease="lung cancer cell line",intervention="IL1B and BMP6, alone or combined",sample_count="3 independent experiments for soluble protein ELISA",notes="Cohort for original validation only; not CytoSig's reused repository studies. No human donor replication.")
cohort("C-CO04","C-S04",dataset_id="C-D04",tissue="peripheral blood",cell_type="elutriated monocytes",intervention="LPS, IL10, IL4, or IL10 neutralization",notes="Table1 and Fig6/Fig7 are distinct readouts of one publication; donor count and cross-publication overlap unavailable. Seven-hour and 24-hour RNA results are separate time contexts.")
cohort("C-CO05","C-S05",dataset_id="C-D05",tissue="peripheral blood",cell_type="monocytes",intervention="adenoviral STAT3 or inactive STAT3; LPS and IL10",notes="Abstract-limited extraction. Donor independence cannot be resolved.")
cohort("C-CO06","C-S06",dataset_id="C-D06",participants="anonymous blood donors",tissue="peripheral blood",cell_type="monocyte-derived mature DC; autologous NK cells",intervention="IL15 and/or IL15RA mRNA electroporation; coculture",donor_count="Fig1A:3; Fig1B:6; unique total unavailable",notes="Antwerp Red Cross blood samples; within-study donor overlap across figures unavailable.")
cohort("C-CO07","C-S07",dataset_id="C-D07",tissue="lymph node, spleen and peripheral blood",cell_type="DC; CD56brightCD16-negative NK cells",intervention="DC maturation and cytokine neutralization",notes="Anatomical donor matching described in Fig4 excerpt; individual identities/counts unresolved. Do not count each tissue as independent without confirmation.")
cohort("C-CO08","C-S08",dataset_id="C-D08",participants="patients P1 and P3",tissue="peripheral blood",cell_type="expanded mycobacterium-reactive CD4 Th1 T-cell clones",disease="IL12RB1 deficiency with mycobacterial/Salmonella infections",intervention="IL12 plus mitogenic or antigen stimulation",donor_count=2,parent_cohort="C-CO09",notes="10 tested clones derive from 2 patients, not 10 independent people. P1/P3 are a verified participant subset of C-CO09; parent link represents participant overlap, not derivation of clones from the assayed blasts. P1/P3 also overlap prior studies cited as reference9; additional reuse remains unresolved.")
cohort("C-CO09","C-S08",dataset_id="C-D09",participants="P1, P3, P4, P17 and healthy controls",tissue="peripheral blood",cell_type="PHA-activated T-cell blasts",disease="IL12RB1 deficiency or healthy controls",intervention="IL12; IFNA positive control",donor_count="4 patients; 2 controls in STAT4 assay",notes="Expanded participant set contains P1/P3 from C-CO08. The child cohort link records this known overlap; different assay/cell-preparation contexts remain distinct and are not independent donor replication. Sample-level matching and additional historical reuse remain unresolved.")
cohort("C-CO10","C-S06",dataset_id="C-D10",participants="3 AML patients in remission",tissue="peripheral blood",cell_type="monocyte-derived DC and autologous NK cells",disease="acute myeloid leukemia in remission",intervention="IL15/IL15RA mRNA DC engineering",donor_count=3,parent_cohort=U,notes="Fig5 validation registered but not extracted as a duplicate healthy-donor assertion; prior stem-cell transplantation excluded.")
fields="assertion_id subject subject_type predicate object object_type subject_layer object_layer measurement evidence_tier direction source_id cohort_id source_locator evidence_summary species ancestry age sex tissue disease disease_severity treatment_status cell_type cell_state developmental_state stimulation dose duration assay genomic_background time_point effect_size effect_unit uncertainty causal_directness limitations contradiction_group candidate_path qc_status qualitative_confidence".split()
assertions=[]
def assertion(i,src,co,sub,obj,pred,meas,direction,sl,ol,summary,locator,**kw):
    d={k:U for k in fields}
    d.update(assertion_id=f"C-A{i:02d}",source_id=src,cohort_id=co,subject=sub,subject_type="cytokine_protein",object=obj,object_type="gene",predicate=pred,measurement=meas,direction=direction,subject_layer=sl,object_layer=ol,evidence_summary=summary,source_locator=locator,species="Homo sapiens",evidence_tier="perturbational",qc_status="reviewed_extraction",qualitative_confidence="moderate")
    d.update(kw);assertions.append(d)
mouse=dict(species="Mus musculus",age="11–15 weeks",sex="female",tissue="inguinal lymph node",disease="healthy",treatment_status="experimental cytokine injection",dose="5 µg cytokine per mouse",duration="4 hours",time_point="4 hours",assay="10x Genomics scRNA-seq",genomic_background="C57BL/6",developmental_state="young adult",causal_directness="In-vivo cytokine intervention; cell-intrinsic versus secondary response unresolved.",limitations="Mouse lymph node; single dose/time; RNA only.",uncertainty="Magnitude unavailable; cannot transport directly to human blood.")
assertion(1,"C-S01","C-CO01","Il4","Il4i1","increases_transcript_abundance","RNA_abundance","increase","C","T","IL4 exposure increased Il4i1 expression in lymph-node B cells.","Cell-type-specific polarization; Fig3a and Extended Data Fig5",cell_type="B cell",stimulation="Il4 injection",**mouse)
assertion(2,"C-S01","C-CO01","Il1b","Ifngr1","increases_transcript_abundance","RNA_abundance","increase","C","T","IL1B induced Ifngr1 transcripts in an NK-cell state; receptor function was not measured.","Cell-type-specific polarization; Fig3p and Extended Data Fig6",cell_type="NK cell",cell_state="NK-c",stimulation="Il1b injection",**mouse)
human=dict(age="34–75 years",sex="6 male; 6 female donors",tissue="peripheral blood",disease="healthy",cell_type="B cell (naive and intermediate pooled)",treatment_status="in-vitro cytokine exposure",duration="24 hours",time_point="24 hours",assay="Parse GigaLab scRNA-seq; donor-level pseudobulk consensus",causal_directness="Cytokine added to mixed PBMC culture; secondary mediators possible.",limitations="Preprint; mixed culture; receptor blockade absent; no IgE protein or class-switch phenotype measured.",uncertainty="Gene-specific effect estimate not extracted.")
for i,g in [(3,"IGHE"),(4,"IL4R"),(5,"IL4I1")]:
    assertion(i,"C-S02","C-CO02","IL4",g,"increases_transcript_abundance","RNA_abundance","increase","C","T",f"IL4 exposure increased {g} transcripts in B cells.","Results: Cytokine-induced responses include expected marker genes; Fig1e",stimulation="IL4",**human)
for i,g in [(6,"CXCL8"),(7,"CCL2")]:
    assertion(i,"C-S03","C-CO03","BMP6",g,"decreases_secreted_protein","secreted_protein","decrease","C","P",f"BMP6 plus IL1B yielded lower soluble {g} than IL1B alone in A549 cultures.","Results: BMP6 Antagonizes Pro-Inflammatory Cytokine Target Genes; Extended Data Fig4d; ELISA Methods",object_type="secreted_protein",evidence_tier="P2",tissue="lung",disease="lung cancer cell line",cell_type="A549",stimulation="IL1B with BMP6",dose="IL1B 10 ng/mL; BMP6 10 ng/mL",duration="24 hours",time_point="24 hours",assay="supernatant ELISA",causal_directness="Purified cytokine cotreatment; no receptor confirmation.",uncertainty="3 experiments; individual effect size unavailable.",limitations="Transformed epithelial cells; not primary immune cells or human donors.",contradiction_group="C-CG01")
mono=dict(tissue="peripheral blood",cell_type="elutriated monocyte",cell_state="LPS activated",stimulation="LPS",dose="LPS 1 µg/mL",duration="24 hours",time_point="24 hours",assay="cytokine-specific supernatant ELISA",limitations="Donor count unavailable; OCR checked against abstract; exact numeric effects not transcribed.",uncertainty="Qualitative direction only.")
assertion(8,"C-S04","C-CO04","monocyte","IL10","secretes","secreted_protein","increase","C","P","LPS-stimulated monocytes released IL10 into culture supernatant.","Table1; Fig1 kinetics; Methods cytokine ELISAs",subject_type="cell",object_type="secreted_protein",evidence_tier="P1",causal_directness="Direct extracellular protein measurement following LPS.",**mono)
m=mono|dict(dose="LPS 1 µg/mL; IL10 100 U/mL")
assertion(9,"C-S04","C-CO04","IL10","TNF","decreases_secreted_protein","secreted_protein","decrease","C","P","Added IL10 reduced TNF in LPS-stimulated monocyte supernatants.","Table1 and Fig3D",object_type="secreted_protein",evidence_tier="P2",causal_directness="Purified IL10 perturbation; receptor not tested.",**m)
m=mono|dict(dose="LPS 1 µg/mL; IL4 100 U/mL")
assertion(10,"C-S04","C-CO04","IL4","IL10","decreases_secreted_protein","secreted_protein","decrease","C","P","IL4 reduced LPS-induced monocyte IL10 secretion.","Table1; Results: IL4 inhibits IL10 production",object_type="secreted_protein",evidence_tier="P2",causal_directness="Purified IL4 perturbation; receptor not tested.",**m)
m=mono|dict(dose="LPS 1 µg/mL; IL10 100 U/mL",duration="24 hours",time_point="24 hours",assay="Northern blot; RT-PCR followed by Southern blot confirmation")
assertion(11,"C-S04","C-CO04","IL10","IL10","decreases_transcript_abundance","RNA_abundance","decrease","C","T","Added IL10 strongly reduced IL10 mRNA after 24 hours of LPS activation; the separate seven-hour experiment showed no or minimal inhibition.","Fig7A–B and Results: IL10 Regulates IL10 mRNA but not TGFB mRNA Expression in Activated Monocytes",evidence_tier="P2",causal_directness="RNA perturbation response; direct transcriptional binding not tested.",contradiction_group="C-CG06_IL10_autoregulation_time",**m)
assertion(12,"C-S05","C-CO05","STAT3","TNF","does_not_reduce_secreted_protein","secreted_protein","null","P","P","Increasing activated STAT3 did not directly reduce LPS-induced TNF production.","Abstract, sentences describing adenoviral manipulation and TNF",subject_type="signaling_protein",object_type="secreted_protein",tissue="peripheral blood",cell_type="monocyte",stimulation="LPS; adenoviral STAT3 overexpression",assay=U,evidence_tier="perturbational",causal_directness="STAT3 manipulation; secretion assay details not recovered.",limitations="Abstract only; adenoviral transduction efficiency and dose unresolved.",uncertainty="Failure to show suppression, not proof of universal absence.",qc_status="needs_full_text",qualitative_confidence="low",contradiction_group="C-CG02")
dc=dict(tissue="peripheral blood",disease="unavailable",cell_type="monocyte-derived mature dendritic cell",cell_state="7-day differentiated DC; mRNA electroporated",dose="10 µg IL15 mRNA with or without 10 µg IL15RA mRNA",stimulation="mRNA electroporation",limitations="Engineered human cells; total unique donors and natural exposure equivalence unavailable.",uncertainty="Small donor experiments; quantitative effect unavailable.")
assertion(13,"C-S06","C-CO06","monocyte-derived dendritic cell","IL15","secretes","secreted_protein","increase","C","P","IL15-mRNA-transfected DC released soluble IL15.","Fig1B; Cytokine secretion assays",subject_type="cell",object_type="secreted_protein",evidence_tier="P1",duration="2–72 hours",time_point="peak 2–8 hours",assay="supernatant IL15 ELISA; eBioscience 88-7158-88",causal_directness="Direct extracellular protein measurement after source engineering.",**dc)
assertion(14,"C-S06","C-CO06","IL15 mRNA electroporation","IL15","does_not_increase_surface_protein","protein_abundance","null","T","P","IL15 mRNA alone did not significantly increase surface IL15 over mock DC.","Fig1A; Results first section",subject_type="experimental_intervention",object_type="surface_protein",duration="2–72 hours",time_point="2,4,8,24,48,72 hours",assay="surface flow cytometry; anti-IL15-PE",causal_directness="Source engineering with measured surface protein.",contradiction_group="C-CG03",**dc)
assertion(15,"C-S06","C-CO06","IL15RA mRNA co-electroporation","IL15","increases_surface_protein","protein_abundance","increase","T","P","Adding IL15RA mRNA to IL15 mRNA increased DC surface IL15, peaking at eight hours.","Fig1A; Results first section",subject_type="experimental_intervention",object_type="surface_protein",duration="2–72 hours",time_point="8-hour peak",assay="surface flow cytometry; anti-IL15-PE",causal_directness="IL15RA co-expression perturbation with surface readout.",contradiction_group="C-CG03",**dc)
nk=dc|dict(cell_type="autologous NK cell with engineered DC",cell_state="resting NK cells before coculture",duration="44-hour priming then 4-hour killing assay",time_point="48 hours",assay="flow cytometric Daudi-cell killing")
assertion(16,"C-S06","C-CO06","IL15:IL15RA-expressing dendritic cell","NK-cell cytotoxicity","increases","cellular_phenotype","increase","C","F","IL15/IL15RA-engineered DC enhanced NK killing; transwell separation removed the additional benefit and IL15 neutralization reduced killing.","Fig4A–B",subject_type="cell",object_type="cellular_process",evidence_tier="P4",causal_directness="Source engineering, contact separation and cytokine neutralization support source-to-target causality.",candidate_path="C-S06 engineered DC surface IL15/IL15RA -> autologous NK cytotoxicity; proximal signaling unmeasured",**nk)
nk=dc|dict(cell_type="autologous NK cell with engineered DC and Daudi targets",cell_state="resting before coculture",duration="24 hours",time_point="24 hours",assay="intracellular IFNG flow cytometry with GolgiPlug")
assertion(17,"C-S06","C-CO06","IL15:IL15RA-expressing dendritic cell","IFNG","increases_intracellular_protein","protein_abundance","increase","C","P","Co-engineered DC increased intracellular IFNG in gated NK cells relative to IL15-only DC.","Fig3C; Intracellular staining Methods",subject_type="cell",object_type="intracellular_protein",causal_directness="Source-engineered coculture; IFNG endpoint not itself neutralization-tested.",**nk)
older=dict(tissue="peripheral blood",cell_type="NK cell with autologous monocyte-derived DC",cell_state="CD56brightCD16-negative enriched response",uncertainty="Donor count and detailed assay conditions unresolved.",limitations="Abstract plus figure search excerpts; requires full-text review.",qc_status="needs_full_text",qualitative_confidence="low",evidence_tier="perturbational")
assertion(18,"C-S07","C-CO07","IL12 neutralization","IFNG","decreases_protein_production","protein_abundance","decrease","C","P","IL12 blockade reduced DC-induced NK IFNG production. The authors describe secretion, but the accessible abstract and Figure4A excerpt do not verify an extracellular assay for this blood-NK result.","Abstract; Fig4A excerpt in search3.json",subject_type="experimental_intervention",object_type="protein",stimulation="mature DC coculture; anti-IL12",causal_directness="Cytokine neutralization in coculture; protein compartment and assay unavailable; source-specific IL12 manipulation not demonstrated.",**(older|dict(limitations="Abstract plus figure search excerpts; protein compartment unavailable. Do not infer extracellular secretion or intracellular localization until full methods are verified. Withhold from mechanistic paths; requires full-text review.")))
assertion(19,"C-S07","C-CO07","IL15 neutralization","NK-cell proliferation","decreases","cellular_phenotype","decrease","C","F","Blocking IL15 reduced DC-induced NK proliferation.","Fig4D; Abstract",subject_type="experimental_intervention",object_type="cellular_process",stimulation="mature DC coculture; anti-IL15",duration="6 days",time_point="6 days",assay="CFSE dilution",causal_directness="Neutralization and contact-separation contrast in coculture.",**older)
o=older|dict(cell_type="immature monocyte-derived DC",cell_state="immature")
assertion(20,"C-S07","C-CO07","immature dendritic cell","IL15","lacks_detectable_surface_protein","protein_abundance","null","C","P","Surface IL15 was undetectable on immature DC despite total cellular IL15.","Fig5 and Results: Mature, but Not Immature, DCs Present IL15",subject_type="cell",object_type="surface_protein",assay="surface staining; total-protein Western blot comparison",causal_directness="Localization contrast; not absence of intracellular IL15.",contradiction_group="C-CG03",**o)
clone=dict(tissue="peripheral blood",cell_type="expanded mycobacterium-specific CD4 Th1 T-cell clone",cell_state="mitogen activated",disease="IL12RB1 deficiency",genomic_background="biallelic IL12RB1 loss-of-function; P1/P3",stimulation="anti-CD2 plus anti-CD28 with or without IL12",dose="IL12 5 U/mL or 2.5 ng/mL",duration="72 hours",time_point="72 hours",assay="supernatant IFNG ELISA",evidence_tier="P2",uncertainty="Clone observations not independent donors.",limitations="Expanded clones from 2 patients; not resting T cells or all IL12RB1 deficiency.",contradiction_group="C-CG04")
assertion(21,"C-S08","C-CO08","IL12","IFNG","increases_secreted_protein","secreted_protein","increase","C","P","IL12 increased IFNG secretion in responding receptor-deficient T-cell clones after mitogenic activation.","Fig1B–D; Results: Myc-reactive Th1 TCCs ... Can Still Respond to IL12",object_type="secreted_protein",causal_directness="Purified cytokine in activated clone cultures without accessory cells.",**clone)
c=clone|dict(cell_state="K4D8 and K3F12 clones under tested activation modes",stimulation="antigen or CD2/CD28 or CD3/CD28 activation")
assertion(22,"C-S08","C-CO08","IL12","IFNG","does_not_increase_secreted_protein","secreted_protein","null","C","P","Two deficient clones, K4D8 and K3F12, repeatedly lacked an IL12 response under the tested stimulation modes.","Fig1A–E; Results immediately following definition of response",object_type="secreted_protein",causal_directness="Purified cytokine perturbation with repeated clone-specific null responses.",**c)
blast=dict(tissue="peripheral blood",cell_type="PHA-activated T-cell blast",cell_state="day3 after PHA stimulation",stimulation="IL12",dose="2.5 ng/mL IL12",duration="20 minutes",time_point="20 minutes",assay="EMSA with STAT4 supershift",evidence_tier="P3",uncertainty="Small patient/control series; assay measures DNA-binding complexes, not phosphorylation.",limitations="Natural receptor deficiency; linked background differences; PHA blasts differ from T-cell clone secretion assay.",contradiction_group="C-CG05")
assertion(23,"C-S08","C-CO09","IL12","STAT4 DNA-binding complex","does_not_induce","protein_activity","null","C","P","IL12 did not induce detectable STAT4-containing DNA-binding complexes in IL12RB1-deficient blasts.","Fig7A–C; Stat4 Activation Methods",object_type="protein_complex",disease="IL12RB1 deficiency",genomic_background="biallelic IL12RB1 loss-of-function",causal_directness="Receptor-deficient versus control response; IFNA positive control.",**blast)
assertion(24,"C-S08","C-CO09","IL12","STAT4 DNA-binding complex","induces","protein_activity","increase","C","P","IL12 induced STAT4-containing DNA-binding complexes in healthy-control blasts.","Fig7A–C; Stat4 Activation Methods",object_type="protein_complex",disease="healthy",genomic_background="control; IL12RB1 surface expression",causal_directness="Control arm of receptor-deficiency comparison.",**blast)
m=mono|dict(dose="LPS 1 µg/mL; IL10 100 U/mL",duration="7 hours",time_point="7 hours",assay="Northern blot",uncertainty="Authors report no or minimal inhibition; no numeric estimate, confidence interval or equivalence bound extracted.",limitations="Qualitative Northern-blot contrast, not proof of zero effect or equivalence. Donor count unavailable. A distinct 24-hour experiment shows stronger inhibition and must remain a separate temporal context.")
assertion(25,"C-S04","C-CO04","IL10","IL10","has_no_or_minimal_inhibitory_effect_on_transcript_abundance","RNA_abundance","null","C","T","After seven hours of LPS activation, added IL10 had no or only minimal inhibitory effect on IL10 mRNA, according to the authors' qualitative description.","Fig6 caption and Results: IL10 Regulates IL10 mRNA but not TGFB mRNA Expression in Activated Monocytes; PMC2119001.txt lines 515–519 and 594–603",evidence_tier="P2",causal_directness="Purified cytokine perturbation with qualitative RNA readout; direct promoter regulation untested.",contradiction_group="C-CG06_IL10_autoregulation_time",qualitative_confidence="low",**m)
gaps=[
{"gap_id":"C-GAP01","topic":"Coverage","detail":"Bounded pilot, not an exhaustive systematic review. Many priority cytokines have no narrow extracted human assertions: CSF2, IL16, IL17A, IL5, IL7, LTA, VEGF identity, IL13, IL1A, IL2, IL6, CCL11, CCL26, CCL13, CCL22, CCL3, CCL4, CCL17. Anchor inclusion does not certify coverage."},
{"gap_id":"C-GAP02","topic":"Access","detail":"C-S05 and C-S07 remain needs_full_text; NCBI API supplied only abstracts and browser full text returned CAPTCHA. C-S04 OCR contains errors; numeric results deliberately not copied."},
{"gap_id":"C-GAP03","topic":"Transportability","detail":"Human PBMC 24h versus mouse lymph-node 4h, different doses/tissues/species; no direct pooled prior or cross-species path. A549 findings are a separate transformed-cell context."},
{"gap_id":"C-GAP04","topic":"Mechanism","detail":"No inferred receptor availability from RNA; no secreted cytokine from RNA; no proliferation/cytotoxicity from gene programs. HCD and CytoSig communication predictions not entered as causal edges."},
{"gap_id":"C-GAP05","topic":"Versions","detail":"bioRxiv published=NA is repository linkage status, not proof no journal publication exists. Exact-title search plus two preprint records support preprint classification as of retrieval."},
{"gap_id":"C-GAP06","topic":"Publication and cohort bias","detail":"Older assays have unavailable independent donor totals. P1/P3/P4 patient data overlap historical publications. CytoSig reused primary studies require accession-level deduplication before expansion."},
{"gap_id":"C-GAP07","topic":"IL12 and VEGF identities","detail":"IL12 perturbation reagent label retained as IL12; do not equate unknown clinical IL12 assay channel with IL12p70. VEGF and high-range CXCL8 assay definitions require user/platform documentation."},
{"gap_id":"C-GAP08","topic":"Missing scope","detail":"No receptor-binding biochemistry, phosphoproteomic dose/time grids, ancestry stratification or full priority-set citation chaining completed in this pilot."}
]
# Queries below were actually issued to the web search tool, in the recorded order.
groups=[
['"Immune Dictionary" cytokine Nature 2023','"Human Cytokine Dictionary"','"CytoSig" cytokine signaling 2021 Nature Methods','human monocytes interleukin 10 inhibits LPS cytokine production receptor STAT3 study'],
['"Dictionary of immune responses to cytokines" PMC','"Activated signal transducer" "poor regulator" STAT3','human interleukin 12 receptor beta 1 deficiency interferon gamma production 1998','IL-15 trans-presentation human dendritic cells NK cells IL15R alpha study'],
['"A single-cell cytokine dictionary of human peripheral blood" 2026 publication journal','"Systematic investigation of cytokine signaling activity" PMC'],
['"Distinct roles of IL-12 and IL-15" Ferlazzo 2004','"Residual type 1 immunity" 10952721 IL-12','"Activated signal transducer" "poor regulator" 2007 DOI','"Interleukin 10(IL-10) inhibits cytokine synthesis" 1991'],
['"STAT3" "poor regulator" "Williams" "2007"','"Distinct roles of IL-12 and IL-15" "IL-12" "blocked"','"Residual Type 1 Immunity" "Stat4" "MAP"','"Dictionary of immune responses to cytokines" "Il1b" "Il1r1"'],
['site:pmc.ncbi.nlm.nih.gov/articles/PMC12776526/ "Version"','site:pmc.ncbi.nlm.nih.gov/articles/PMC1810496/ "IL-6" "IL-10" "Abstract"','site:pmc.ncbi.nlm.nih.gov/articles/PMC2193232/ "Abstract"','site:pmc.ncbi.nlm.nih.gov/articles/PMC10781646/ "4 h" "IL-1β"'],
['"Activated signal transducer" "SOCS3" "IL-10" "5" monocytes','"Transpresentation of interleukin-15 by IL-15/IL-15Rα" doi']]
files=["search1.json","search2.json","open2.json","open3.json","search3.json","search4.json","open7.json"]
searches=[]
for group,f in zip(groups,files):
 for q in group:
  searches.append(dict(search_id=f"C-Q{len(searches)+1:02d}",lane="cytokine/signaling and perturbation transcriptomics",query=q,database="web search; primary publications and repositories screened",searched_at=DATE,result_source_ids=[],screening_notes="Actual batched search response retained in research/cytokine/snapshots/"+f+"; result mapping documented by selected source registry, not an exhaustive search."))
searches += [
dict(search_id="C-Q27",lane="preprint status",query="details/biorxiv/10.64898/2025.12.12.693897/na/json",database="bioRxiv API",searched_at=DATE,result_source_ids=["C-S02"],screening_notes="Version1, date2025-12-15, published=NA; raw JSON saved."),
dict(search_id="C-Q28",lane="full-text retrieval",query="efetch db=pmc id=1810496,534504,2193232,10781646,2119001,12776526 retmode=xml",database="NCBI Entrez EUtilities",searched_at=DATE,result_source_ids=["C-S01","C-S04","C-S05","C-S07","C-S08","C-S09"],screening_notes="Mixed full-text/metadata response. Explicit access classification retained per source.")
]
# Populate only directly known selected-result matches; empty means no selected result.
mapping={1:["C-S01"],2:["C-S02"],3:["C-S03"],4:["C-S04","C-S05"],5:["C-S01"],6:["C-S05"],7:["C-S08"],8:["C-S06","C-S07"],9:["C-S02","C-S09"],10:["C-S03"],11:["C-S07"],12:["C-S08"],13:["C-S05"],14:["C-S04"],15:["C-S05"],16:["C-S07"],17:["C-S08"],18:["C-S01"],21:["C-S08"],22:["C-S01"],23:["C-S05"],24:["C-S06"]}
for n,ids in mapping.items():
 if n<=len(searches): searches[n-1]["result_source_ids"]=ids
# The four site-filtered queries occupy positions 19–22 and the last pair 23–24.
pack=dict(sources=sources,cohorts=cohorts,assertions=assertions,searches=searches,gaps=gaps,synthesis="The bounded cytokine pilot retains human perturbation evidence, measured secretion and functional coculture effects, and explicit null contrasts. Human and mouse dictionaries remain separate RNA resources. Engineered IL15/IL15RA presentation is distinguished from soluble IL15 and from intracellular IFNG. IL12RB1-deficient activated clones can retain responses while acute STAT4 DNA-binding induction is absent in PHA blasts. These are distinct contexts, not a resolved universal pathway. No complete multi-omic path or scientifically calibrated probability is claimed.")
for a in pack['assertions']:
    if a['assertion_id']=='C-A12':
        a.update(measurement='protein_abundance',object_type='protein',predicate='does_not_reduce_protein_production',causal_directness='STAT3 manipulation; extracellular compartment and assay details not recovered.')
    if a['assertion_id'] in ['C-A13','C-A14','C-A15','C-A16','C-A17']:
        a['disease']='healthy'
    if a['assertion_id']=='C-A18':
        a['duration']='unavailable'; a['time_point']='unavailable'
    if a['assertion_id']=='C-A20': a['evidence_tier']='observational'
    if a['assertion_id'] in ['C-A21','C-A22']:
        a['sex']='female'; a['age']='P1:27 years; P3:4 years'
    if a['assertion_id']=='C-A22':
        a['limitations']+=' Study defined a response as >50% increase; null means no response by this criterion, not exact zero effect.'
for c in pack['cohorts']:
    if c['cohort_id']=='C-CO06': c['disease']='healthy'
(BASE/"pack.json").write_text(json.dumps(pack,indent=2,ensure_ascii=False)+"\n")
